Cargo.toml
src/handlers/mod.rs
src/handlers/proxy.rs
src/main.rs
src/providers/infura.rs
src/providers/mod.rs

Implements a basic strategy pattern with an Infura strategy for Ethereum to support multiple RPC providers depending on the desired chain in the future.
Manually tested

feat: implement provider strategy

---

README.md
src/env.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/main.rs
src/providers/infura.rs
src/providers/mod.rs

Supports all chains that Infura currently supports expected to be specified as CAIP2 e.g. eip155:1.
`curl -vvv -X POST -H "Content-Type:application/json" "http://localhost:3000/v1?chainId=eip155:5&projectId=someid" -d '{"id":"1660887896683","jsonrpc":"2.0","method":"eth_chainId","params":[]}'`

feat: supports chains other than mainnet

---

Cargo.lock
Cargo.toml
src/handlers/metrics.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/main.rs
src/state.rs

Installs a call counter that let's us know how many calls we received split up by chain id.
Next step: add a prometheus instance and create a Grafana dashboard.
Tested the `/metrics/` endpoint locally.

feat: install metrics and export via prometheus

---

src/main.rs
src/state.rs

Currently we can't distinguish the response codes of the proxy hence we cannot do availability.
Not tested

feat(o11y): add http metrics

---

src/main.rs
terraform/monitoring/main.tf

* Fix: Status code graph was broken before
* Feat: add latency widget
Not tested.

feat: plot code/latency

---

Dockerfile

We need at least Rust `1.65` to run the app. Hence, pinning the version.
Not tested

feat: pin rust version

---

Dockerfile

We recently changed config parameters. The `Dockerfile` one wasn't updated causing the app to run on `127.0.0.1`.

fix(ci): application not exposed

---

Cargo.lock
README.md
docker-compose.yaml
src/handlers/proxy.rs
src/main.rs
src/project/mod.rs
src/project/storage/mod.rs
terraform/main.tf
terraform/monitoring/main.tf
terraform/monitoring/variables.tf

- Add a `docker-compose` definition to run locally with a Redis instance
- Add a dashboard panel and alert in Grafana for the Redis instance.
Resolves #40 
Deployed manually to `staging`.

feat: Add docker-compose and Redis dashboards

---

.github/workflows/cd.yaml

Add running environment to all CD tasks to enable access to secrets.

fix: add run environments to CD tasks

---

Cargo.toml
src/main.rs

fix: don't use ansi in logs

---

terraform/analytics.tf
terraform/ecs/iam.tf
terraform/ecs/variables.tf
terraform/main.tf

Add the `kms:GenerateDataKey` permission to the ECS role bucket policy

fix: Add access to analytics KMS key to ECS role policy

---

terraform/analytics.tf

Enable `bucket key` for analytics buckets encryption.
Not tested.

fix: enable bucket keys for encryption

---

src/analytics/config.rs
src/analytics/message_info.rs
src/analytics/mod.rs
terraform/analytics.tf
terraform/ecs/iam.tf
terraform/ecs/main.tf
terraform/ecs/variables.tf
terraform/main.tf

- Remove legacy analytics export
- Rename analytics to `rpc_requests`
`terraform plan` on staging

fix: remove legacy analytics exports

---

terraform/ecs/main.tf
terraform/ecs/network.tf

Open up the security group for the ECS task to internet since the load balancer forwards the client IP.
Deployed and tested on staging

fix: open sg for ecs to internet

---

terraform/monitoring/main.tf

Set the auth method to the correct value (`ec2_iam_role`) for Grafana authentication to Prometheus.
The manual "Save & Test" that used to be required before should not be necessary anymore.
Deployed on `staging`.

fix: set Prometheus auth method to correct value

---

.github/workflows/ci.yaml

Project id not modeled. Not sure this worked before.

fix: project id env variable not set

---

.env.example
.github/workflows/ci.yaml
src/env/zksync.rs
tests/context/server.rs

Solves recent problems with tests after zksync addition.
Renames PROJECT_ID to TEST_RPC_PROXY_PROJECT_ID to give it more context.
Mentions TEST_RPC_PROXY_PROJECT_ID in .env.example.
Integ tests ran locally.

fix: removed unnecesary requirement for zksync project_id

---

terraform/backend.tf
terraform/ecs/main.tf
terraform/ecs/network.tf
terraform/ecs/variables.tf
terraform/main.tf
terraform/private_zone/main.tf
terraform/redis/main.tf

Exposes the RPC via `.org` for frens who cannot access `.com` if it's blocked.
Tested in staging.

feat: expose via backup DNS

---

terraform/monitoring/main.tf

Terraform was not parsing the string with notification configuration we were providing, later escaping it when putting it in json. I lead to broken connection grafana <-> opsgenie. Changed string to array so it is properly encoded in json.
Resolves #112 
Deployed to staging.

fix: change string to array for proper parsing

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml
.github/workflows/validate.yaml
Cargo.toml
src/env/server.rs
src/lib.rs
terraform/ecs/main.tf
terraform/ecs/variables.tf
terraform/main.tf
tests/context/mod.rs
tests/context/server.rs
tests/functional/connection/binance.rs
tests/functional/connection/infura.rs
tests/functional/connection/pokt.rs
tests/functional/connection/zksync.rs
tests/functional/metrics.rs

Moving metrics to private endpoint for prometheus. 
Also integ testing on staging and prod. 
Changed tests to use `/v1/` endpoint to track the issue we had recently.
With all comments addressed.
Resolves #81  and #99 
Integ tests. Will require manual verificaiton.

feat: moving metrics to private endpoint and better testing

---

src/env/infura.rs
tests/functional/websocket/infura.rs

Infura restricted ws functionality for polygon rendering it currently not useful for our proxy purposed. Removing it for now. We still support it over HTTP.
Failing tests lead to contact with infura and information from them.
Now tests pass.

fix: remove polygon ws - no longer supported by infura 

---

src/analytics/message_info.rs
src/handlers/proxy.rs
src/metrics.rs

Added more metrics to track both how many calls are successful and how many fail per provider, as well as status codes per provider.
Also added `provider` to data lake exports.
Resolves #122 
This is initial work in the subject, currently tested by running locally and forcing two kinds of error: in the service and in the provider, with the following result
```
curl -X POST \
'http:///localhost:3000/v1/?projectId=<project_id>3&chainId=eip155:2' \
--header 'Content-Type: application/json' \
--data-raw '{"id":"1","jsonrpc":"2.0","method":"eth_chainId","params":[]}'
```
where eip155:2 is not supported -> results in: 
```
400 BAD REQUEST
{
"status": "FAILED",
"reasons": [
{
"field": "chainId",
"description": "We don't support the chainId you provided: eip155:2"
}
]
}
```
while 
```
curl -X …
```

feat: distinguish between provider and service errors

---

src/error.rs

When provided with an invalid project id, the service would return 500 instead of 401.
Not it will return proper error to user, as well as leaving log for us to investigate if needed.
Ran and verified locally.

fix: return 401 instead of 500 for unauthorized

---

Cargo.toml
src/env/infura.rs
src/env/mod.rs
src/lib.rs
src/main.rs
src/metrics.rs
src/providers/mod.rs
src/providers/weights.rs
src/state.rs
tests/context/mod.rs
tests/context/server.rs
tests/functional/http/infura.rs
tests/functional/http/mod.rs
tests/functional/websocket/infura.rs
tests/functional/websocket/mod.rs
tests/utils/mod.rs

I was investigating why the tests are failing so oftenly, I though it was because half-baked system. Turns out Infura changed their handling of one decomissioned chain (from proper error to forbidden).
I think it's good idea to get rid of decomissioned chains. This way instead of giving strange error to user, we just inform them we don't support this chain with our message.
Ran tests.

fix: remove decomissioned chains

---

src/handlers/proxy.rs
tests/context/mod.rs

Bugfix - wrong error code being returned to users on provider failure
Verified locally with custom provider.

fix: change response on provider rate limit from 400 to 502

---

.github/workflows/cd.yaml
.github/workflows/ci_terraform.yaml

Allowing image version selection for quicker rollbacks in case something is wrong with new deployment. 
Also removed `deploy_staging` as we always deploy to staging before prod, I think possibility to not deploy to prod is enough.
Resolves #155 
GA actions change- didn't test.

fix: enable image version selection in cd

---

src/error.rs
src/handlers/proxy.rs

Seems like the 500's still happening in proxy are all transport errors caused by our providers mishandling our connection.
Converting them to 502's as we do with rate limiting (marking downstream provider error).
Resolves #157 
Not tested, will need to monitor the changes.

fix: account for 500 errors

---

src/env/pokt.rs

We have equal quotas with Infura/Pokt now (10mio/day).
Hence, align the Pokt weights for mainnet chains with the Infura chains.
Also give Pokt more BSC weight.
Not tested

feat(weights): move more traffic to Pokt

---

src/env/pokt.rs

Wrong DNS names used for some chains
Resolves https://github.com/orgs/WalletConnect/discussions/2674
Not tested

fix: wrong Pokt RPC endpoints used

---

tests/utils/mod.rs

Currently it's unclear why Infura is failing aka doesn't contain an `id` parameter. Hopefully this will add some color.
Not tested

feat(test): log more req/response when failing to parse response

---

src/handlers/proxy.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/mod.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/zksync.rs

We don't need to pass path, query params, or headers to the RpcProxy. Refactoring to increase separation of concerns and futureproof re-use by ENS caching layer.
Not tested

refactor: minimize function params

---

src/handlers/proxy.rs

Log anytime a non-POST method takes place as JSON RPC should be POST-only.
Not tested

chore: log non-POST messages to know if we can disable non-POSTs

---

src/env/binance.rs
src/env/infura.rs
src/env/omnia.rs
src/env/pokt.rs
src/env/publicnode.rs
src/env/zksync.rs
src/providers/mod.rs
src/providers/weights.rs
terraform/ecs/main.tf

Separate weights and priorities so that we have more granular control over weights.
Resolves #179 
Tested locally using local prometheus.

179 use initial weight configuration as multiplier instead of overwriting it

---

terraform/ecs/main.tf

Proxy was using prometheus url instead of proxy url -> leading to 403 instead of data.
Changed to use local address with sigproxy port.
Resolves #187 
Applied to staging, terraform works. Need to redeploy app to confirm.

fix: prometheus url replaced with proxy url

---

src/providers/mod.rs
terraform/ecs/main.tf
terraform/ecs/variables.tf
terraform/main.tf

The rpc was at first trying to connect directly to prometheus instead of sigv4 proxy, and later was hitting proxy without proper header and workspace. This should fix it. Have no way of testing locally thought. This is still non-breaking change - if it fails, the app will default to static weights.
Resolves #188 
Terraform deployed to staging.

fix: connection to sigv4 proxy

---

src/env/binance.rs
src/env/omnia.rs

Adjusting priorities for Pokt (with unblocked eth-mainnet)
Moving some traffic back to binance, as even thought they are quite limited, dynamic weights should handle that.
Resolves #194 
Untested, just priority adjustement.

fix: priorities adjustement

---

src/env/omnia.rs
src/providers/mod.rs
src/providers/weights.rs

Adjusting timeframe values for longer `memory` of failing provider.
Also decreasing priority for omniatech for `eip155:137` which seems to have increased traffic recently, while Omniatech has low traffic allowance.
Also - currently we decrease weight of chain exponentialy from the failures, but overall provider availability linearly. 
Changing to both exponential:
The initial assumption was - when a provider starts failing for one chain, it may still work properly for others. But in reality the most common issue we have is - provider reaching rate limit. We don't want to still try other chains then, when we can definitely see it's failing. So changing to more "aggresive" approach.
Resolves #201 
Dynamic weights fine tuning - untested

fix: timeframe and priority for omniatech:eip155:137

---

src/lib.rs

Log request data for more debugging possibilities.
This will help debugging both weird HTTP errors we see (524, 520) as well as missing `origin` info
Resolves #206 
Tested locally

feat: more logging info

---

terraform/monitoring/panels/identity/latency.libsonnet
terraform/monitoring/panels/identity/usage.libsonnet

Fix the latency metric names (latency chart was empty).
Fix the name of the Usage chart since it is not avatar-specific.
Manually by editing prod Grafana charts. PR not tested.

fix: metrics charts

---

terraform/backend.tf
terraform/ecs/main.tf
terraform/ecs/network.tf
terraform/ecs/variables.tf
terraform/main.tf
terraform/monitoring/terraform.tf
terraform/private_zone/main.tf
terraform/redis/main.tf
terraform/redis/variables.tf
terraform/variables.tf

See https://www.notion.so/walletconnect/Postmortem-RPC-Down-June-30-f4a6ee010b2544fe82ece0fe38ba3f10
RPC proxy now runs in its own VPC.
Also adding some more VPC endpoints.
Applied to staging

fix(hotfix): migrate to dedicated VPC

---

terraform/main.tf
terraform/redis/main.tf
terraform/redis/outputs.tf
terraform/redis/variables.tf

The DNS hosted zone was no longer in the default VPC. Hence it would have to be added to the VPC explicitly. However, this was a bad solution in the first place. Hence, removing.
Applied

fix: Redis DNS not discoverable

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/weights/provider.libsonnet

Adding weight graphs pernamently.
Resolves #217 
Deployed to staging.

217 add pernament weight graphs to grafana

---

Cargo.lock
Cargo.toml
src/debug/alloc.rs
src/lib.rs
src/metrics.rs
src/project/metrics/mod.rs

Changing from ValueRecorder to Gauge. Migrating to newest opentelemetry.
Resolves #217 
Tested locally, confirmed data is exported
I don't think it should, but it may cause issues with grafana board. Will monitor deployment and act asap if I see any problems.

fix: migrate to newest version of opentelemetry

---

src/lib.rs

We spend $600/month on RPC Logging. These request/response logs we've never actioned so removing. However, better would be a config to only log them for non-HTTP2XX but I don't know how.
Not tested

feat: remove request/response logger

---

terraform/monitoring/panels/ecs/availability.libsonnet

We had a regression where we stopped getting metrics. We didn't get an alarm for that. After this change we will get an alarm for such scenarios.
Not tested

feat: add no data alert

---

src/providers/mod.rs
terraform/monitoring/panels/ecs/availability.libsonnet
terraform/monitoring/panels/identity/availability.libsonnet
terraform/monitoring/panels/identity/cache.libsonnet
terraform/monitoring/panels/identity/requests.libsonnet
terraform/monitoring/panels/identity/usage.libsonnet
terraform/monitoring/panels/proxy/calls.libsonnet
terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
terraform/monitoring/panels/proxy/errors_provider.libsonnet
terraform/monitoring/panels/proxy/http_codes.libsonnet
terraform/monitoring/panels/proxy/rejected_projects.libsonnet
terraform/monitoring/panels/status/provider.libsonnet
terraform/monitoring/panels/usage/provider.libsonnet

Fixing grafana boards
Temporarely disabling no-data alarm which is breaking, tracked in different issue:
https://github.com/WalletConnect/rpc-proxy/issues/228
Resolves #227 
Manually deployed and verified

227 grafana broken after changing the opentelemetry version

---

src/providers/mod.rs
src/providers/weights.rs

After downtime of metrics we accumulated a lot of failures -> we overflowed on squaring failures count. 
Changed from u32 -> u64 and added checked multiplication.
Resolves #230 
Ran test.

fix: checked mul

---

src/handlers/identity.rs
src/lib.rs
src/state.rs

No longer return a 404 when the name cannot be found. Instead, the `name` field in the response is now optional and you'll get back `{ name: null, avatar: null }`.
Consumers of this API should assume that a `null` name will also result in a `null` avatar, but this isn't enforced by the types. This was simpler than `{ name: string, avatar: string | null } | null`
Resolves #215 
Locally with Web3Modal

feat: no more 404 for name not found

---

terraform/monitoring/panels/ecs/availability.libsonnet
terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
terraform/monitoring/panels/proxy/errors_provider.libsonnet

Removing the provider/non-provider alarms. Configuring `availability` alarm instead.
I'm not sure what's the issue, but grafana didn't want to accept alarm on math expression, but for the same expression, but in query it seems to work.
Resolves #233 
Deployed by hand and verified.

233 better availability alarms

---

src/handlers/ws_proxy.rs
src/metrics.rs

Adding metric there so we can see if websockets are used at all.
Relay had similar mem leak problem, and the team tracked it down to tungstenite. 
This will confirm if it's worth to go down that road
Resolves #238 
test ran

feat: add metrics for number of ws connections

---

src/lib.rs
src/server.rs

This adds a forced timeout on hyper's service tasks. Ported from [the relay](https://github.com/WalletConnect/rs-relay/blob/master/src/http/mod.rs#L41).
Untested.

fix: force timeout on service tasks

---

src/error.rs
src/handlers/identity.rs

Fix couple of errors that I'm seeing in CloudWatch logs.
This also explicitly prefixes RpcErrors to make it easier to identity problems coming from the rpc-proxy later in the future.
Also identify if error comes from name or avatar lookup.
Resolves #250 
Not tested

chore: handle more errors

---

src/error.rs
src/handlers/identity.rs

Most errors come from looking up avatar information (e.g. NFT data) after the contract data was already retrieved. These appear to be all user errors in configuring their ENS profile.
Simplifying the code to not single out individual ENS-configuration problems, and instead assume all non-provider related errors are from various ENS-configuration problems. Only errors originating from SelfProvider will return a non-2xx status code for identity API.
The new error handling code appears a little non-DRY, but this will be able to be simplified once the identity endpoint does its own project ID validation in #264 and we will be able to convert all errors into either NameError or AvatarError.
Resolves #268
Not tested

chore: only treat SelfProviderErrors as errors

---

src/handlers/identity.rs
src/handlers/proxy.rs
src/lib.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/mod.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/zksync.rs

Only allow POSTing on RPC endpoints (`/v1` and `/v1/`). Non-POST requests are not used for any legitimate traffic as determined [here](https://walletconnect.slack.com/archives/C03SCF66K2T/p1689286049171369?thread_ts=1687284476.715569&cid=C03SCF66K2T) and potentially impact our own rate limits/quotas.
Resolves #266 
Not tested

chore: only POST for RPC

---

src/lib.rs

Re-enable support for HTTP/2 that was removed in #245 
Resolves #270
Not tested

fix: reenable HTTP/2 and assume http1 tuning didn't fix memory leaks

---

.env.example
src/lib.rs

Decreases the service executor timeout to terminate connections after 15 seconds.
Resolves #272 
Not tested

chore: decrease service executor timeout

---

Cargo.lock
Cargo.toml

Bumps the cerberus version to include this fix: https://github.com/WalletConnect/cerberus/pull/20
Resolves #278
Not tested

chore: handle invalid formatted project IDs

---

SUPPORTED_CHAINS.md
src/env/binance.rs
src/env/infura.rs
src/env/omnia.rs
src/env/pokt.rs
src/env/publicnode.rs
src/env/zksync.rs
src/lib.rs

Adds a public list of supported chains and the intention of keeping this up-to-date.
Resolves #281
This is a manual process for now. In the future if we get SLAs it would be desirable and easy to automate this process so we make sure it's correct and don't accidentally remove chain support. I experimented with an automated process on [this](https://github.com/WalletConnect/rpc-proxy/blob/feat/abandoned-automated-chain-list/src/bin/generate-chain-list.rs) branch. Idea is to run this script to generate the Markdown file which would pull from [ethereum-lists/chains](https://github.com/ethereum-lists/chains) to get the chain name. We would also run it in CI to make sure it is correct. Reason I didn't continue with this approach was:
- Some chains were named weird e.g. Mumbai instead of …

docs: add supported chains list

---

README.md
SUPPORTED_CHAINS.md
src/env/infura.rs
src/env/omnia.rs
src/env/pokt.rs

- Add support for Ethereum Sepolia via Infura and Pokt
- Update README to be more public-facing
- Remove support for Optimism Kovan as this network was decommissioned last year and my curl and websocket tests demonstrate this
- Remove Celo Websocket as this didn't work with my test (see JS commands below)
```
% curl -X POST https://optimism-kovan.infura.io/v3/<infura-key> --data '{"id":"1660887896683","jsonrpc":"2.0","method":"eth_chainId","params":[]}'
{
"id":null,
"error": {
"code":-32601,
"message":"Network decommissioned, please use Goerli",
"data": {
"see":"https://blog.infura.io/post/deprecation-timeline-for-rinkeby-ropsten-and-kovan-testnets"
}
}
}
```
- All networks via WebSocket except the 3 Ethereum ones are actually unofficially supported by Infura. Their dashboard says not …

feat: Ethereum Sepolia & update docs

---

.env.example
src/env/mod.rs
src/lib.rs
src/profiler/mod.rs
terraform/ecs/main.tf
terraform/ecs/variables.tf
terraform/main.tf
terraform/variables.tf

DEBUG_SECRET is no longer used as of https://github.com/WalletConnect/rpc-proxy/pull/249. Removing it now
Resolves #288 
Not tested

chore: remove debug_secret

---

README.md
src/providers/infura.rs

🤦 I used the `supported_ws_providers` in the wrong place, so integration tests became flaky (as the "infura" tests don't actually test Infura exclusively), resulting in internal server errors from whatever provider was in-use. Luckily they never passed by chance in the number of times I retried the pipeline...
Resolves #297
Locally

fix: Infura supported chains

---

src/handlers/proxy.rs

Logs an `error` level log for failing providers plus the payload. This will help investigations such as lately when we wanted to investigate "non-provider errors" but weren't able to do so.
Closes #212 
Not tested

feat: log proxy errors

---

SUPPORTED_CHAINS.md

WebSockets aren't implemented with as much care as HTTP RPC is. And it isn't clear if there are plans to improve this in the future.
- Only useful for watching events to avoid polling. Other performance/efficiency benefits can be already achieved with HTTP/2
- No load balancing/weighting during WebSocket sessions
- Weights for WebSockets are never adjusted
- No monitoring setup for WebSockets
- Not built with as much care as relay for handling many concurrent WebSockets
- Far fewer supported chains due to limited support from providers
- No 15-second forced disconnection for memory protection
Resolves #303
N/A

docs: disclaim WebSocket use

---

Dockerfile

Docker build is failing because `cargo-chef` version isn't locked: https://github.com/WalletConnect/rpc-proxy/actions/runs/5967919903/job/16190688151
Docs say to lock this: https://github.com/LukeMathWalker/cargo-chef#how-to-install
Resolves #309
Not tested

fix: Docker build

---

src/env/base.rs
src/env/infura.rs
tests/functional/http/infura.rs

Use Infura for Base Goerli and reduce priority of public RPC as it is rate limited.
Resolves #299 
Locally

feat: use Infura for Base Goerli

---

README.md

Adding the `Requirements` section to the `README.md` with the requirements below:
- [Rust](https://www.rust-lang.org/tools/install) >= 1.56 version,
- [Just](https://github.com/casey/just#packages) as a command runner,
- [Docker](https://www.docker.com/) for building and running Docker containers.
`Curl` and `Nano` which are used in the `README.md` are pretty common and can be pre-installed on some distributions. On the other side `Rust`, `Just`, and `Docker` are not (especially `Just` is not a common bird), so it's good to let the developer know to install the requirements for building the project.
Resolves #318
N/A: Doesn't require a test as it's a documentation update.

docs: adding requirements

---

terraform/ecs/main.tf

Lower autoscaling thresholds so they trigger before the monitoring alerts.
Since the alerts and monitoring are configured with the same levels, alerts are fired before and more often than when autoscaling events are happening.
Looking at the charts, 50% usage for autoscaling seems to be the sweet spot.

fix: lower autoscaling thresholds

---

Dockerfile

Update rust to `1.72` in Dockerfile.
Resolves #329 
Local tests

fix: update rust version in docker build

---

terraform/vars/dev.tfvars
terraform/vars/prod.tfvars
terraform/vars/staging.tfvars

We observe some shenanigans with cloudflare because of which our rate limiting doesn't work, as registry API always returns `isValid: true`. 
@Cali93's proposed solution was to use `.org`
Existing tests

feat: use registry.walletconnect.org

---

.github/workflows/ci.yaml
deny.toml

Make sure using only permissive open source licenses.
Resolves #343 
```bash
cargo deny check license
```
And CI

chore: add license check

---

src/handlers/mod.rs
src/lib.rs
src/providers/mod.rs
src/providers/zerion.rs
tests/functional/http/mod.rs

This PR adds `transfers` object to the account history response format to add:
* Fiat value of transaction
* Crypto value of transaction
* Url(s) to token(s) images
* Url(s) to nft image
* NFT name / Collection name
The new response format is:
```
data: [
{
"id": "1a5a22ea3cb35fdb9080c09fe7b57ecc",
"metadata": {
"operationType": "mint", // Enum: approve, borrow, burn, cancel, claim, deploy, deposit, execute, mint, receive, repay, send, stake, trade, unstake, withdraw
"hash": "0x70783a3580f2eb63f3c35fdcdc8feffbe591eea1beaaec6eb4592b19bfb73e45",
"minedAt": "2023-10-29T14:25:29Z",
"sentFrom": "0x66eeb19f3ef93312541009f855ff4c900adb3450",
"sentTo": "0xa2a829f1fd922f283282d0d2367f69a13167a9b1",
"status": "confirmed", // Enum: confirmed, failed, pending
"nonce": 3126
}
// New object …
```

feat: add transactions and nft info to the history response

---

src/providers/zerion.rs

Zerion history response sometimes has a `null` as values for the `value` and `price` fields.
In this case, we have deserialization errors like:
```
rpc_proxy::providers::zerion: Error on parsing zerion transactions response: Error("invalid type: null, expected usize", line: 248, column: 37)
```
To handle `null` value for the `usize` type on serde deserialization we should mark it as an `Option`.
Resolves #339 
Dogfooding Zerion response with the `null` value to the `get_transactions` function. 
The expected result is no deserialization error.
Also, it's covered in by the integration test.

fix: adding `Option` to the value and price to handle `null` value

---

src/handlers/mod.rs
src/providers/zerion.rs

`value` and `price` fields in the `transfer` object in the Zerion response for the history can be **float** type (not just an integer) in some responses (ex. `191.2148374268388`).
This PR converts the type from `usize` to `f64` and removing `Hash` and `Eq` derives from structures that uses `f64`.
Resolves #339
1. Dogfooding Zerion fake response with the `123`, `123.12345`, `null` values to the `get_transactions` function.
The expected result is no deserialization error.
2. CI build and test workflow.

fix: changing price and value to f64 type

---

src/analytics/history_lookup_info.rs
src/analytics/mod.rs
src/handlers/history.rs

This PR adds the following analytics for the transaction history:
* timestamp
* lookup address: address for the history
* project_id
* transactions_count: number of `transactions` in a history reply
* latency_secs
* transfers_count: total number of transfer objects
* fungibles_count: total number of fungible objects
* nft_count: total number of nft objects
* origin
* region
* country
* continent
Resolves #361 
Not tested, only successful build test.

feat(analytics): adding analytics for transactions history

---

.env.example
src/providers/pokt.rs

Pokt returning rate limit errors. It doesn't return 429 status code so this will parse the response and use that to determine rate limit status. The existing `is_rate_limited()` function doesn't automatically adjust weights, so modifying the response code instead.
Context: https://walletconnect.slack.com/archives/C03SCF66K2T/p1700511418157459

fix: Pokt rate limits

---

integration/integration.test.ts

Implementation of the integration test for the history API.
The following checks are made:
- Fulfilled history check,
- Empty history check,
- Wrong address provided check.
Resolves #373
Passing tests by running
```
PROJECT_ID=xxx RPC_URL=https://rpc.walletconnect.com  yarn integration
```

chore(tests): adding integration tests for the history

---

src/providers/base.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/zksync.rs
src/providers/zora.rs

Logs all provider responses that contain a JSON RPC error, but use the OK status code. This is strange, and we may want to consider automatically retrying them in the future, and factoring them into the weighting.
Context: https://walletconnect.slack.com/archives/CB247BW9F/p1700522001797329?thread_ts=1700521059.160949&cid=CB247BW9F
Not tested

fix: log JSON RPC errors with OK status code

---

terraform/ecs/main.tf
terraform/vars/prod.tfvars

Decrease scaling threshold from 50% to 25% to allow more burstiness without maxing out CPU/MEM like it does sometimes.
Also increase max instances from 5 to 10. Looks like past couple of days this only got to 4, but not sure if there is a bug here where 4 is the actual limit and I don't see why this shouldn't be higher anyway to accommodate more scale. We need it to double anyway if the scaling threshold is halved.
Not tested

fix: double scaling capacity

---

src/env/mod.rs
src/providers/base.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/zksync.rs
src/providers/zora.rs

Fixes the Pokt PR https://github.com/WalletConnect/blockchain-api/pull/369/files#diff-aceb22d366624f307c6cbe4a2ffcc3efe0b342432b722d97257176b80789dccfR97 and re-adds strange error logging previously added in https://github.com/WalletConnect/blockchain-api/pull/370.
Fix is to not return all `parts` because Hyper will add a second content-length header, which will then be duplicated.
Context: https://walletconnect.slack.com/archives/C03SCF66K2T/p1700659169053979?thread_ts=1700647203.176389&cid=C03SCF66K2T
Automated tests

fix: fix Pokt rate limit fix PR & log strange JSON RPC errors

---

src/providers/base.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/zksync.rs
src/providers/zora.rs

Before we returned the raw response from the provider, but now we re-construct the response. But didn't add `Content-Type: application/json` header.
Context: https://walletconnect.slack.com/archives/C03SCF66K2T/p1700666765949029?thread_ts=1700647203.176389&cid=C03SCF66K2T
Not

fix: missing Content-Type: application/json

---

tests/utils/mod.rs

Tests that the response header is `Content-Type: application/json`
Removing the header response and checking that it failed

fix: test content-type header

---

Cargo.lock
Cargo.toml
integration/integration.test.ts
src/handlers/identity.rs
src/lib.rs
src/state.rs

Using a Google Sheet to mimic an ENS offchain resolver reverse lookup. If the app fails to read the Google Sheet only this feature breaks.
No. It just disables the feature if anything is wrong. Only uses the feature for the users in the allowlist.
Covered in integ test.

feat: offchain

---

src/providers/infura.rs
src/providers/pokt.rs

Annotates [`Internal Error`](https://docs.infura.io/networks/ethereum/json-rpc-methods) RPC code as such and translates to HTTP5XX for our failover algorithm to take it into account.
Not tested but confirmed that these are legit internal errors.

feat: annotate HTTP5XX

---

SUPPORTED_CHAINS.md
src/env/zora.rs
tests/functional/websocket/zora.rs

Removing Zora Goerli eip155:999 websocket API from providers.
The reason: WebSocket API constantly returns empty responses for any requests.
Resolves #367 
Sending the request to the Zora websocket rpc using `wscat` CLI command:
```
wscat -c wss://rpc.zora.energy -x '{"id":"1","jsonrpc":"2.0","method":"eth_chainId","params":[]}'
```
response:
```
{"jsonrpc":"2.0","result":"0x76adf1","id":"1"}
```
Sending the request to the [Zora Goerly websocket rpc](https://github.com/WalletConnect/blockchain-api/blob/master/src/env/zora.rs#L75) using `wscat`:
```
wscat -c wss://testnet.rpc.zora.energy -x '{"id":"1","jsonrpc":"2.0","method":"eth_chainId","params":[]}'
```
response:
```
empty response
```
It seems that this RPC is not working so it should be removed until resolution.

chore(providers): removing zora goerli websocket api

---

Cargo.lock
Cargo.toml
integration/integration.test.ts
src/handlers/mod.rs
src/lib.rs

This PR adds a request tracing mechanism based on the `x-request-id` header and [tower **request_id** middleware](https://docs.rs/tower-http/latest/tower_http/request_id/index.html).
* If the `x-request-id` is not provided in the request headers it's generated as an UUIDv4,
* The generated/provided `x-request-id` is added to the tracing info span,
* The `x-request-id` is exposed to the response headers set, so it can be get and traced after the request.
🚧 Additional tracing logs are stacked on top of this PR as #391 
Resolves #372
**Integration test**
An [integration test](https://github.com/WalletConnect/blockchain-api/pull/387/commits/13cb54a76c9e908247b824d087c54deefdb992c8) is added in this PR and passed locally.
**Testing manually**
Start the service locally and run the curl command …

chore: adding the span with request-id for handlers

---

.github/workflows/ci.yaml

This PR adds an ECR image version tag as a short SHA commit (eg. `d6ee36e`) instead of always be `latest`.
With this change, we can track what version was shipped and can ship a certain version to revert.
[GITHUB_SHA](https://docs.github.com/en/actions/learn-github-actions/variables) GitHub CI variable is used to get the commit SHA and shorten it by the `::7`.
Resolves #53 
Not tested, but should babysit it when merging and test it.

fix(ci): image tag version as a short commit SHA instead of `latest`

---

integration/integration.test.ts
src/handlers/health.rs
src/state.rs

This PR adds exposing of the following states to the `/health` endpoint:
* Build commit hash - to track what version is alive on the current deployment,
* Features - to track what features are on,
* Uptime - to track the uptime of the service and to know when the instance was restarted.
The updated `/health` response should look like:
```
OK v0.1.0, commit hash: d6ee36e, features: test_localhost, uptime: 294 seconds
```
Tested by the included in this PR integration test.

feat(health): exposing commit hash, features, uptime to the health

---

integration/integration.test.ts

This PR adds a check for the UUIDv4 format for the `x-request-id` header for the OK response and for the Not OK responses and fixing a nit `header` -> `headers`.
Start a local server with `cargo run`.
Run integration test with `RPC_URL=http://localhost:3000  yarn integration`.
Also passing tests on staging:
`RPC_URL=https://staging.rpc.walletconnect.com  yarn integration`

test(integration): fixing check for UUIDv4 format and check on errors

---

src/handlers/history.rs

Fixes the below panels which depend on `add_history_lookup` which is not called anywhere.
Not tested

fix(o11y): history lookup not tracked

---

src/handlers/history.rs
src/handlers/identity.rs
src/handlers/portfolio.rs
src/handlers/proxy.rs
src/handlers/ws_proxy.rs
src/providers/base.rs
src/providers/binance.rs
src/providers/infura.rs
src/providers/mod.rs
src/providers/omnia.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/weights.rs
src/providers/zerion.rs
src/providers/zksync.rs
src/providers/zora.rs
src/state.rs
src/ws.rs

This PR adds additional tracing `instruments` to handlers and providers for the additional span logs in case of errors and for proper debugging.
Resolves #372 
🚧 Stacked on top of the #387 
Logs are exposed with proper tracing instrument spans.

chore: adding tracing instrument spans to handlers and providers

---

integration/integration.test.ts
src/handlers/identity.rs

Removes the mocked reverse ENS lookup until we actually ship the feature.
Not tested

feat(identity): remove ENS demo

---

terraform/ecs/cluster_iam.tf

Change the IAM policy used by ECS role to access Prometheus to read and write access to unblock weight updates.
N/A

fix: change ECS role Prometheus permission to read+write access

---

terraform/monitoring/panels/ecs/availability.libsonnet
terraform/monitoring/panels/proxy/calls.libsonnet
terraform/monitoring/panels/proxy/http_codes.libsonnet

Some widgets were broken as the `ecs task family` name changed. We can remove that entirely as the prometheus datasources this data comes from is already scoped to specific domains.
Not tested

fix(o11y): dashboards broken

---

terraform/ecs/cluster.tf

- Missing `/workspaces` in query URL
Manually

fix: missing workspaces in query URL

---

.github/workflows/event_release.yml

Fix the ECS task name in the version retrieval of the release flow.
Checked the call to `release-get_deployed_version` separately.

fix: ECS task name in version retrieval

---

migrations/20231209213851_init-names.sql
migrations/20231209213904_init-addresses.sql
migrations/README.md

This PR adds the SQL database tables schema migration files for the sqlx according to the [SPECS](https://walletconnect-specs-git-max-feathexlessspec-walletconnect1.vercel.app/2.0/specs/servers/blockchain/blockchain-server-api).
Resolves #405 
When the server is started the migration procedure is invoked in #412 . The expected result is a successful server start.

feat: add sql schema and migrations for the ENS

---

terraform/ecs/cluster.tf
terraform/ecs/network.tf
terraform/ecs/variables.tf
terraform/postgres/context.tf
terraform/postgres/main.tf
terraform/postgres/outputs.tf
terraform/postgres/password.tf
terraform/postgres/terraform.tf
terraform/postgres/variables.tf
terraform/res_db.tf
terraform/res_ecs.tf
terraform/res_postgres.tf

This PR adds the Amazon RDS Postgres engine to the AWS terraform configuration and exposes the `database_uri` to the ECS cluster instances to connect to the Database.
Resolves #405 
Tested only by the `terraform plan`.

chore(terraform): adding Postgres

---

terraform/postgres/main.tf

This PR changes the rds aurora postgres engine version `16` -> `15.5`.
Despite its presence in the documentation, the new engine version [is not present](https://github.com/WalletConnect/blockchain-api/actions/runs/7260015231/job/19778451096#step:9:582) in the engines list for the region yet. 
To get the list of the available engine versions
`aws rds describe-db-engine-versions --engine aurora-postgresql --query '*[].[EngineVersion]' --output text --region eu-central-1`
Version `15.5` is the latest in the list.
Not tested.

chore(terraform): downgrade rds aurora version

---

.env.example
Cargo.lock
Cargo.toml
docker-compose.yaml
src/database/config.rs
src/database/mod.rs
src/env/mod.rs
src/error.rs
src/lib.rs
src/state.rs

This PR adds sqlx to the server, invoking migration at the bootstrap, and adds the `RPC_PROXY_POSTGRES_URI` environment variable for the Postgres URI configuration.
Resolves #405 
Run functional database tests in #413. The expected result is successfully passing all database tests.

feat: scaffold sqlx and add `RPC_PROXY_POSTGRES_URI` env variable

---

.dockerignore

This PR removes ignoring of the `migrations` directory from the ignoring paths in the `.dockerignore`.
This should fix the [build error where the `migrations` directory is required for the sqlx](https://github.com/WalletConnect/blockchain-api/actions/runs/7260672209/job/19782875952#step:8:1594).
The `migrations` directory should be copied into the container after this change by [copying all files in the Dockefile](https://github.com/WalletConnect/blockchain-api/blob/master/Dockerfile#L53).
Built the local Docker image by running `docker build . -t rpc `.

chore(docker): removing `migrations` directory from the ignoring paths

---

src/handlers/history.rs
src/handlers/identity.rs
src/handlers/proxy.rs
src/utils/network.rs
terraform/context.tf
terraform/inputs.tf
terraform/main.tf
terraform/res_ecs.tf

Since the migration moved the service behind an ALB, we cannot retrieve the client IP directly for geo-location.
This leverages the `X-Forwarded-For` header injected by the LB instead.
Unit tests

fix: retrieve client IP from `X-Forwarded-For` header

---

Dockerfile

This PR moving the `COPY . .` before the `cargo chef cook` to copy necessary build files before the build itself, since the `cargo chef cook` invokes the build process.
This should fix the [not found error on build](https://github.com/WalletConnect/blockchain-api/actions/runs/7260672209/job/19782875952#step:8:1594) for the `migrations`.
Successfully [built from this PRs branch](https://github.com/WalletConnect/blockchain-api/actions/runs/7263994163/job/19790969549#step:8:772).

chore(docker): moving `COPY` before the `cargo chef cook`

---

src/database/error.rs
src/database/helpers.rs
src/database/mod.rs
src/database/types.rs
src/database/utils.rs
tests/functional/database.rs
tests/functional/mod.rs
tests/utils/mod.rs

This PR adds database helpers function implementations for the tables schema in #411 and according to the [SPEC](https://walletconnect-specs-git-max-feathexlessspec-walletconnect1.vercel.app/2.0/specs/servers/blockchain/blockchain-server-api) that should be further used in the server endpoint handlers for names and addresses manipulations.
The functional tests to cover helpers are added to this PR.
Resolves #405 
* 8: profile names …

feat: implement database helpers

---

.github/workflows/dispatch_validate.yml

This PR fixes the prod URL for the validation CI workflow. The validation was only using the staging URL for the prod as well.
The workflow can be tested by invoking the CI validation workflow.

chore(ci): fixing production validation url

---

.gitignore

This PR adds the `node_modules` directory to the `.gitignore`.
We are using the `yarn` for our integration/validation tests, which causes creating a `node_modules` directory with the yarn cache.
Not tested.

chore: adding `node_modules` to the `.gitignore`

---

Dockerfile

This PR reverts the #429 changes because it affects the `cargo-chief` caching strategy and doesn't provide any fix. 
To fix the [image build error](https://github.com/WalletConnect/blockchain-api/actions/runs/7260672209/job/19782875952#step:8:1594), #427 changes was enough.
Successfully built the image by the CI and `docker build .` with this reverted commit.

chore(docker): Revert: moving `COPY` before the `cargo chef cook`

---

.github/workflows/dispatch_validate.yml
.github/workflows/sub-validate.yml

This PR changes the `stage-url` variable to be the host URL without an additional route. 
By passing the variable with the `/health` route the integration tests fail because the testing routes were appended to the `/health` and the server returns `404` as a result. 
As a fix, we should pass the host URL without the `/health` route and append it only where the health check occurs.
Pass the [Validation CI action from this PR branch](https://github.com/WalletConnect/blockchain-api/actions/runs/7275661793/job/19823933620#step:5:11).

fix(ci): fixing the `stage-url` variable for the validation

---

src/handlers/mod.rs
src/handlers/profile/lookup.rs
src/handlers/profile/mod.rs
src/handlers/profile/reverse.rs
src/lib.rs

This PR implements the following lookup handlers according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/179):
* Forward lookup `/v1/profile/account/:name`: name -> addresses,
* Reverse lookup `/v1/profile/reverse/:address`: address -> names.
Resolves #405
Run local integration tests in #419

feat: add lookup handlers

---

src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/lib.rs

This PR implements the name registration handler according to the [registration SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/184).
The `verify_message_signature` function is introduced to verify the Ethereum message signature.
Resolves #405
Local unit tests for the `verify_message_signature` function.
Run the integration tests at …

feat: name registration handler

---

Cargo.lock
Cargo.toml
src/lib.rs
src/state.rs

This PR removes the usage of the Google Sheets ens allowlist and removes the `ens_allowlist` from the state and dependencies. 
ENS Allowlist was used for the demo and don't need anymore.
Start the server by `cargo run` and run the integration tests by `RPC_URL=http://localhost:3000 yarn integration`.

chore: removing `ens_allowlist`

---

.github/workflows/sub-cd.yml

Use the correct name in the staging CD flow (image name and task name are not the same for this repo).
N/A

fix: use task name instead of image name in ECS deploy on `staging`

---

.github/workflows/sub-cd.yml

This PR removes the `/health` route from the validation CI workflow, as it causes the [404 error](https://github.com/WalletConnect/blockchain-api/actions/runs/7287794249/job/19859609569#step:5:6) because we are adding routes inside of the integration tests.
Running the CD workflow from the branch.

fix(ci): removing `/health` from the sub-cd validation

---

.github/workflows/sub-validate.yml

This PR adds the Postgres container and `RPC_PROXY_POSTGRES_URI` to the CI `sub-validate` testing to fix the functional tests run.
[Successfully passed the Validate](https://github.com/WalletConnect/blockchain-api/actions/runs/7288508632/job/19861438226) tests from this branch.

fix(ci): adding Postgres requirements to the `sub-validate`

---

src/handlers/history.rs
src/providers/coinbase.rs
src/providers/mod.rs
src/providers/zerion.rs

This PR reverting to use the string-based `address` argument in `get_transactions`. Coinbase Pay SDK is case-sensitive when passing the address to get the transactions list. When we are using the `H160` type we don't know what exactly address type was used: checksum (mixed case) or not when passing it to the Coinbase API later in the function. To fix this we need to preserve the original address string.
As a security validation for the address format, the [check for the address correct format is used](https://github.com/WalletConnect/blockchain-api/pull/439/files#diff-7a388f4d3745ebf0928c4212d627020683b440683be6530f2c885293f475e146R49) in the handler.
1. Start the server with `cargo run`.
2. Get the transactions list with the `onramp=coinbase` parameter.
3. Expect the list of the onramp …

fix: back to string-based address in transactions list

---

integration/integration.test.ts
package.json
yarn.lock

This PR adds an implementation for the integration tests for the account names:
* Register a new name with the wrong signature
* Register a new name with correct signature
* Try registering already registered name
* Inconsistent payload
* Registered name forward lookup
* Address reverse lookup
Resolves #405 
* 2: add sql schema and migrations for ENS #411 
* Start the local Postgres: `docker run -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust …

feat(ci): profile names integration tests

---

src/env/zksync.rs

This PR changes the mainnet URL for the ZkSync to the `mainnet.era.zksync.io` to fix the rate-limiting issue and update it according to the [zksync docs](https://era.zksync.io/docs/dev/building-on-zksync/interacting.html#connecting-to-zksync-era-on-metamask).
1. Start the server locally by `cargo run`.
2. Request the RPC for the `eip155:324`:
```
curl 'http://localhost:3000/v1/?chainId=eip155:324&projectId=XXX'  --data-raw '{"jsonrpc":"2.0","id":0,"method":"eth_getBalance","params":["0x262f4f5DC82ad9b803680F07Da7d901D4F71d8D1","latest"]}'
```
3. The expected response is:
```
{"jsonrpc":"2.0","result":"0x0","id":0}
```

fix(providers): changing the mainnet URL for zksync

---

src/handlers/history.rs
src/handlers/identity.rs
src/handlers/mod.rs
src/handlers/portfolio.rs
src/handlers/proxy.rs
src/providers/coinbase.rs
src/providers/mod.rs
src/providers/zerion.rs
tests/functional/http/mod.rs

To extend our history endpoint with new providers and data it's a good point to move from the Zerion-specific structures and make the response structure owned by the `history` handler itself. 
This PR introduces the following refactorings:
* Moving the `history` handler response-related structures from the Zerion provider to the `history` handler itself.
* Moving handler-related structures to corresponding handler files.
The PR #442 is created on top of this refactoring.
Passing CI and integration tests.

chore(refactor): making history-related structures unite, arranging structures

---

src/providers/coinbase.rs

According to our UI requirements we need to expose the name and quantity for the onramp transactions history item.
This PR introduces changes to the Coinbase transactions provider to expose the name and quantity.
1. Passing the CI and integration tests.
2. Locally:
* Start the server by `cargo run`
* Get the response for the onramp transactions from the Coinbase provider: `curl -v 'http://localhost:3000/v1/account/xxx/history?projectId=xxx&onramp=coinbase' | jq .`
* The expected result:
* `data.transfers.quantity.numeric` is fulfilled,
* `data.transfers.fungible_info.name` is fulfilled.

feat(onramp): exposing name and quantity from Coinbase

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds Grafana panels for the history transactions that were lost during the migration in [commit 50f30](https://github.com/WalletConnect/blockchain-api/commit/50f30e96eecc7468d192d3e58b68e398afcc61fb#diff-d7597af1e267afe8593b70399773e045d6702a595ea85348ef041ab0e31f5b45).
Not tested.

fix(grafana): adding history requests panels

---

integration/integration.test.ts

This PR introduces the integration test for the onramp transactions history for the Coinbase provider and checks the response in case the wrong provider is requested.
* Successfully passing tests from the branch on the prod endpoint:
```
PROJECT_ID=xxx RPC_URL=https://rpc.walletconnect.com  yarn integration
``` 
* Successfully passing the `Validate` workflow from the branch.
* [Result](https://github.com/WalletConnect/blockchain-api/actions/runs/7300031969/job/19893937065#step:5:25)

chore(test): integration test for the onramp Coinbase history

---

src/handlers/history.rs
src/metrics.rs
src/providers/mod.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/history/availability.libsonnet
terraform/monitoring/panels/history/latency.libsonnet
terraform/monitoring/panels/history/requests.libsonnet

This PR changing the current metrics for the transactions history to be per-provider instead of sticking to the one (Zerion) as we have a few history providers now.
* `provider` tag is added to history metrics,
* `add_history_lookup` functions modified to pass the provider argument,
* Grafana panels modified to reflect per `provider` tag data.
Validation only-tested.

chore(monitoring): making history metrics per provider

---

src/handlers/proxy.rs
src/providers/mod.rs
src/state.rs

This PR reduces the logging noise for the proxy requests.
The number of logs for the proxy request declined from 6 records to 2 per request to include just valuable info (what provider is used for the request_id) and dropped other logs to the `DEBUG` level. 
We can turn the all logs back if we start the server with the `DEBUG` logging level.
The `provider` span variable includes the used provider name is added to the handler span for proper tracing.
1. Start the server locally by `cargo run`
2. Run the proxy query e.g. `curl 'http://localhost:3000/v1/?chainId=eip155:324&projectId=XXX'  --data-raw '{"jsonrpc":"2.0","id":0,"method":"eth_getBalance","params":["0x262f4f5DC82ad9b803680F07Da7d901D4F71d8D1","latest"]}'`
The expected logs for the request:
```
INFO http-request{method=POST …
```

chore(logging): reducing logging for proxy requests

---

Cargo.lock
Cargo.toml

This PR bumps the [ethers-rs](https://github.com/gakonst/ethers-rs) version to the current `2.0.11`.
Also, minor versions of dependencies were updated in the `Cargo.lock`.
Start the server with the `cargo run` and run the functional and integration tests.

chore: bumping the `ethers-rs` version

---

src/handlers/identity.rs

This PR reduces the logging noise for identity requests.
The number of logs for the identity request was declined twice, other logs were dropped to the `DEBUG` level.
We can turn all the logs back if we start the server with the `DEBUG` logging level.
The same is done in #447 for the proxy requests.
1. Start the server locally by `cargo run`
2. Call the identity request e.g. `curl 'http://localhost:3000/v1/identity/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63?chainId=eip155%3A1&projectId=XXX'`
The expected result is that logging messages will reduced as twice.

chore(logging): reducing logging for identity requests

---

Cargo.lock
Cargo.toml
integration/integration.test.ts
src/handlers/generators/mod.rs
src/handlers/generators/onrampurl.rs
src/handlers/mod.rs
src/lib.rs

This PR implements the on ramp url generator based on the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/190), [Coinbase js implementation](https://github.com/coinbase/cbpay-js/blob/08a4151a0aa3143e786876fcb7b993cc472a69d4/src/onramp/generateOnRampURL.ts#L9) and [generateOnRampURL](https://docs.cloud.coinbase.com/pay-sdk/docs/generating-url#generateonrampurl-parameters).
* Implements `OnRampURLRequest` according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/190),
* Implements `generate_on_ramp_url` function to generate the URL according to the [coinbase js implementation](https://github.com/coinbase/cbpay-js/blob/08a4151a0aa3143e786876fcb7b993cc472a69d4/src/onramp/generateOnRampURL.ts#L9),
* unit test for the `generate_on_ramp_url`,
* Implements …

feat: implementing on ramp url generator

---

.github/workflows/sub-validate.yml

This PR should resolve the [flaky integration test](https://github.com/WalletConnect/blockchain-api/actions/runs/7462693040/job/20317899316) for the Infura by using the Infura Project ID when running the test.
Not tested.

fix(ci): passing the infura project id to integration tests

---

tests/functional/http/infura.rs
tests/functional/websocket/infura.rs

Infura tests are flaky. This PR ignores the Infura tests until the resolution to unblock the CI/CD workflow.
Not tested.

fix: ignoring Infura tests until resolution

---

src/handlers/history.rs
src/handlers/portfolio.rs

This PR changes the `validate_project_access` to the `validate_project_access_and_quota` for the history and portfolio endpoints to check the project quota as well. 
Adds `validate_project_access` without a quota check for the onramp history.
Not tested.

fix: changing to `validate_project_access_and_quota` in history and portfolio handlers

---

src/handlers/identity.rs

Temporary enabling logging for the avatar lookup to catch the panic condition for the `ethers-rs` while it's not reproduced locally.
This change will be rolled back soon when the issue will be resolved.
Not tested.

fix: adding temporary instrument logging for the avatar lookup

---

.github/workflows/sub-providers.yml
tests/functional/README.md
tests/functional/http/base.rs
tests/functional/http/binance.rs
tests/functional/http/pokt.rs
tests/functional/http/zksync.rs
tests/functional/http/zora.rs
tests/functional/websocket/infura.rs
tests/functional/websocket/zora.rs

The context of the issue (#464):
> At the moment we are running providers integration tests on all changes. Sometimes some of the providers are unavailable (rate-limited etc.) that results in a blocking of the CI/CD process.
> We should run the provider tests only when the provider implementation is changed and run the test only for that provider that was changed.
This PR introduces the following changes:
* Making all provider tests optional by making them `#[ignore]`
* Unifying providers test names to the `{provider_name}_provider` pattern
* Adding the [sub-providers.yml](https://github.com/WalletConnect/blockchain-api/pull/465/commits/fac3317f9dd7de15e369313652e47766fca83bc1) workflow that:
* Determining what provider was changed
* Run the specific provider test (or multiple providers …

feat(ci): per provider integration tests

---

.github/workflows/sub-providers.yml

Removing the trailing slash from the RPC URL from the manual workflow call for the `Providers`.
The trailing slash causes the test to fail if a user is not modifying it. It's better to fix it to be valid by default.
With trailing slash - [Fail](https://github.com/WalletConnect/blockchain-api/actions/runs/7526690884/job/20485346285)
Without trailing slash - [Success](https://github.com/WalletConnect/blockchain-api/actions/runs/7527159789)

fix(ci): removing the trailing slash from the RPC url

---

.github/workflows/sub-validate.yml

This PR introduces changes to the sub-validate CI workflow to run the `sub-providers` workflow for provider-specific integration tests during the CI/CD validation.
* Sub-providers workflow context #465 
Resolves #464
Not tested.

feat(ci): run provider specific tests from sub-validate

---

src/providers/binance.rs

This PR is a noop change in providers code to check the new provider-specific tests from #465, #466 that runs from
* Manual call for the new CI [was tested and successfully can be run from the CI dashboard](https://github.com/WalletConnect/blockchain-api/actions/workflows/sub-providers.yml).
* `workflow_call` is not tested and should be tested by this noop PR.

fix(noop): this is noop change to check the new provider tests in CI

---

.github/workflows/sub-validate.yml

This PR adds the branch tag to the reusable workflow that should possibly fix the [error](https://github.com/WalletConnect/blockchain-api/actions/runs/7529681429/job/20494837706#step:6:1) where the workflow is treated as action and GitHub Actions throws a following error despite [checkout](https://github.com/WalletConnect/blockchain-api/blob/7cd36df407a78cec72f1bfff752e20a3f83773e0/.github/workflows/sub-validate.yml#L55) and the file [is present](https://github.com/WalletConnect/blockchain-api/blob/master/.github/workflows/sub-providers.yml):
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/blockchain-api/blockchain-api/.github/workflows/sub-providers.yml'. Did you forget to run actions/checkout before running your local action?
```
Not tested.

fix(ci): adding the branch tag for the sub workflow

---

src/providers/binance.rs

This PR is a noop change in providers code to check the new provider-specific tests from #465, #466, #470 that runs from
* Manual call for the new CI [was tested and successfully can be run from the CI dashboard](https://github.com/WalletConnect/blockchain-api/actions/workflows/sub-providers.yml).
* `workflow_call` is not tested and should be tested by this noop PR.

fix(noop): this is noop commit to check the provider tests new CI

---

.github/workflows/sub-providers.yml
.github/workflows/sub-validate.yml

This PR changes invoking the providers test sub-workflow as a job instead of as a step, to fix the issue where the local sub-workflow files are not supported as a step.
* [The error](https://github.com/WalletConnect/blockchain-api/actions/runs/7533463980/job/20506321806#step:6:1) that should fix this PR.
Resolves #464
Invoking the sub-workflow as a job is [tested on the forked repository](https://github.com/geekbrother/blockchain-api/blob/0f3952d565c58c285367c81a98bb88533ade5aa8/.github/workflows/test_subcd.yml#L15).

fix(ci): changing to invoke providers workflow as a job

---

src/providers/binance.rs

This PR is a noop change in providers code to check the new provider-specific tests from #465, #466, #470 that runs from
Test plan in #473

fix(ci): noop change in providers code to test the CI workflow

---

.github/workflows/sub-providers.yml

This PR removes the write permission for the sub-providers workflow (as we don't need it here) and fixes the permission error:
```
[Invalid workflow file: .github/workflows/event_release.yml#L75](https://github.com/WalletConnect/blockchain-api/actions/runs/7541637575/workflow)
The workflow is not valid. WalletConnect/blockchain-api/.github/workflows/sub-validate.yml@ae88560aba66eae1556d389344ab7cbf6dd9b839 (Line: 75, Col: 3): Error calling workflow 'WalletConnect/blockchain-api/.github/workflows/sub-providers.yml@ae88560aba66eae1556d389344ab7cbf6dd9b839'. The workflow is requesting 'contents: write', but is only allowed 'contents: read'.
```
Not tested.

fix(ci): removing write permissions from providers tests workflow

---

src/providers/binance.rs

This PR is a noop change in providers code to check the new provider-specific tests from #465, #466, #470 that runs from
The reason for this PR is a test.

fix(noop): checking the providers CI workflow

---

.github/workflows/sub-validate.yml

This PR adds `secrets: inherit` for the providers tests sub workflow.
We are using secrets inside of the sub-workflow, without passing this setting the [CI tasks are skipped](https://github.com/WalletConnect/blockchain-api/actions/runs/7541846605/job/20536188424).
Tested on the forked repo.

fix(ci): inherit secrets to providers validation workflow

---

src/providers/binance.rs

This PR is a noop change in providers code to check the new provider-specific tests from #465, #466, #470 that runs from
The reason for this PR is a test.

fix(noop): checking providers CI workflow

---

src/env/aurora.rs
src/env/mod.rs
src/providers/aurora.rs
src/providers/mod.rs
tests/functional/http/aurora.rs
tests/functional/http/mod.rs

This PR adds the [Aurora Mainnet and Testnet RPC](https://doc.aurora.dev/getting-started/network-endpoints) as a new `Aurora` provider.
Resolves #463
1. Manually:
* Start the server locally by `cargo run`.
* Request the Aurora RPC locally by 
```
curl -X POST "http://localhost:3000/v1?chainId=eip155:1313161554&projectId=XXX" --data '{"id":"1","jsonrpc":"2.0","method":"eth_chainId","params":[]}'
```
2. CI
* [Integration test for the Aurora provider](https://github.com/WalletConnect/blockchain-api/pull/469/files#diff-526d8d8490fc58b397fe439b115b1f7b71f8812d85da7aa1b7cc0e11b5d569daR10).

feat(providers): adding the Aurora native mainnet and testnet RPC

---

src/env/infura.rs
tests/functional/http/infura.rs

This PR removed the Aurora chain from the Infura provider as it's no longer supported, and we added the native Aurora RPC.
The Aurora-related subdomains in the Infura provider are not reachable any more:
```
curl -v https://aurora-mainnet.infura.io/v3/test
* Could not resolve host: aurora-mainnet.infura.io
```

fix(providers): removing Aurora from the Infura provider

---

.github/workflows/dispatch_deploy.yml
.github/workflows/sub-providers.yml

This PR fixes the error on the manual dispatch of the [`Deploy` workflow](https://github.com/WalletConnect/blockchain-api/actions/workflows/dispatch_deploy.yml) with the default `- current -` image tag by making the following changes:
* Making the `Release Version` as an option with the following options:
* `current` - current deployed image tag.
* `latest` - latest release tag.
* `manual` - manual image tag version to deploy.
* Using the manual tag only when the `manual` option is chosen.
Tested by invoking the workflow from the branch:
* [Current](https://github.com/WalletConnect/blockchain-api/actions/runs/7609402830)
* [Latest](https://github.com/WalletConnect/blockchain-api/actions/runs/7609486525/job/20720834815#step:1:37)
* …

fix(ci): using the `current`, `latest` or `manual` image tag in the manual deploy

---

SUPPORTED_CHAINS.md
src/env/omnia.rs
src/handlers/proxy.rs

We have two chain IDs for the Solana mainnet:
* [solana-mainnet](https://github.com/WalletConnect/blockchain-api/blob/12f813a52c34651a6b8f66454dee44596518275b/src/env/omnia.rs#L72)
* [solana:4sgjmw1sunhzsxgspuhpqldx6wiyjntz](https://github.com/WalletConnect/blockchain-api/blob/12f813a52c34651a6b8f66454dee44596518275b/src/env/pokt.rs#L43C14-L43C53)
We should unify the Solana mainnet chain IDs into the single standardized `solana:4sgjmw1sunhzsxgspuhpqldx6wiyjntz`.
This PR adds the `solana-mainnet` alias for the `solana:4sgjmw1sunhzsxgspuhpqldx6wiyjnt` to support clients that already using the `solana-mainnet`, but moving forward with the unified `solana:4sgjmw1sunhzsxgspuhpqldx6wiyjnt` for all providers.
This will solve the load balancing for the Solana chain as well.
Slack [thread …

fix(providers): unifying Solana chain_id

---

src/lib.rs
src/providers/mod.rs

This PR fixing the Aurora provider. On the initial adding of the Aurora native RPC in #469 the init part was missed so the native RPC is not in the list of providers.
This issue was not caught by the compilation, lint, and our integration tests, because tests use the weighted provider and we have a few providers for the Aurora (this issue in tests is also fixed in #487 ).
Tested using the Aurora integration test in #487 per provider tests.

fix(providers): adding Aurora to the init providers

---

SUPPORTED_CHAINS.md
src/env/infura.rs
tests/functional/websocket/infura.rs

This PR removing the Aurora chain (websocket) from the Infura provider as it's not supported anymore. 
Also Aurora is removed from the supported websocket chains list as we currently don't have a provider that support the Aurora by the websocket.
The HTTP was removed in #482 and this PR is a follow-up.
Not tested.

fix(providers): removing Aurora websocket from the Infura

---

integration/integration.test.ts
src/handlers/profile/mod.rs
src/handlers/profile/register.rs

According to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/184/files#diff-f64bf5c2b17c9c6d32ae9d85d9a1ce5a4aa07cb680c6f4085de94d3c4915b9d9R143) to avoid the repeating attack we should use the UNIX timestamp in the signature within the threshold interval (assuming clocks are not synced between this threshold). 
The threshold interval decreased to 10 seconds according to the discussion.
This PR implements the threshold check.
* New [unit tests](https://github.com/WalletConnect/blockchain-api/pull/491/files#diff-e382530ad7aeb0bbd6f4f0ac9bbddf4cc3944e24c387114ecc2dd640cf9e071fR108).
* Current integration tests for the name registration.

feat(ens): adding timestamp threshold check

---

integration/integration.test.ts
src/database/helpers.rs
src/database/types.rs
src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/utils/crypto.rs
src/utils/mod.rs
tests/functional/database.rs

This PR implementing changes to the ENS Gateway to address the updated [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/197).
The updated resolver response should be in the [ENSIP-11](https://alpha-docs.ens.domains/ensip/11) compatible format and should looks like:
```
{
"name": "maxim.connect.id",
"registered_at": "2024-01-23T18:50:02.083933Z",
"updated_at": "2024-01-23T18:50:02.083933Z",
"attributes": {
"bio": "im a test"
},
"addresses": {
"60": { // ENSIP-11 coin type. 60 - Ethereum Mainnet
"address": "0xAff392551773CCb2574fAE23195CC3aFDBe98d18",
"created_at": "2024-01-23T18:50:02.083933Z"
}
}
}
```
[Integration tests](https://github.com/WalletConnect/blockchain-api/pull/489/files#diff-29ee1e76a6651d33c3e1a5117e948675ccda1e60165c885696a9accdc1bf0bb9) for the name …

feat(ens): changes to ENSIP-11 compatible responses

---

src/database/helpers.rs
tests/functional/database.rs

This PR fixing the [database test fails](https://github.com/WalletConnect/blockchain-api/actions/runs/7660512571/job/20878285952#step:5:966) that was missed in #489 
1. Start the Postgres locally: `docker run -p 5432:5432 --name postgres -e POSTGRES_HOST_AUTH_METHOD=trust -d postgres`.
2. Run the database tests locally: `RPC_PROXY_POSTGRES_URI=postgres://postgres@localhost/postgres cargo test --test integration`.
3. Tests successfully passed.

fix(tests): fixing database test for the recent ENSIP-11 update

---

integration/integration.test.ts
src/handlers/history.rs
src/providers/coinbase.rs
src/providers/zerion.rs
src/utils/crypto.rs

This PR exposes the `chain` from the [Zerion history](https://developers.zerion.io/reference/listwallettransactions) `relationships` object and the dapp info from the `attributes.application_metadata`.
Following new objects were added into the history response:
* metadata.application
* name (Optional, String) - DApp name
* iconUrl (Optional, String) - DApp icon url
* metadata.chain (Optional, String) - String representation of the chain from the `relationships` Zerion response in CAIP-2 format.
The example response:
```
...
{
"id": "904c7ac7e1dc5ddd9aed4ceba06ee290",
"metadata": {
"operationType": "receive",
"hash": "0x0f12fde4d498ad01baa181f433ad46ff6ce760af5bfe388418c243f2e2fb168b",
"minedAt": "2023-12-04T11:02:25Z",
"sentFrom": "0xd09a341d601505b0c8a0377acc962802e5f3fb65",
"sentTo": …
```

feat(history): exposing dapp and chain info

---

integration/integration.test.ts
src/env/mod.rs
src/env/server.rs
src/error.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/lib.rs
src/providers/mod.rs
src/utils/crypto.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf
tests/functional/http/aurora.rs
tests/functional/http/base.rs
tests/functional/http/binance.rs
tests/functional/http/infura.rs
tests/functional/http/mod.rs
tests/functional/http/pokt.rs
tests/functional/http/zksync.rs
tests/functional/http/zora.rs

This PR adds an ability to request a certain provider in the proxy handler.
At the moment when we are querying the proxy for the certain `chain_id` the [weighted provider is used](https://github.com/WalletConnect/blockchain-api/blob/d093f9532a7e5dd89c964f111778aabbe375d0b8/src/handlers/proxy.rs#L60) and we can't test the request to the certain provider. 
Our integration tests uses the proxy requests and when we are requesting the certain `chain_id` the server requests a weighted provider and not the provider in tests itself. This makes tests flaky and unstable as we can't make sure what provider exactly was requested for test.
This PR making the following changes:
* Adds an optional `providerId` request parameter for the proxy handler.
* Adds …

feat(providers): proxy request for a certain provider

---

integration/integration.test.ts

This is a small change to fix the expected status code in the integration test from `400` to `401`. This fixing the [following error](https://github.com/WalletConnect/blockchain-api/actions/runs/7741353150/job/21109965889#step:5:51).
Integration test.

fix(ci): fixing the new integration test expected code from `400` to `401`

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR fixes the [Unused dependencies](https://github.com/WalletConnect/blockchain-api/actions/runs/7805473133/job/21289770733) check error by sticking to the exact Rust nightly version in the ci_workflow.
[Invoked CI action from this branch](https://github.com/WalletConnect/blockchain-api/actions/runs/7806551531/job/21293156131).

fix(ci): bump the ci_workflows version

---

Cargo.lock
Cargo.toml
integration/names.test.ts
src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/handlers/profile/utils.rs

This PR adds a check for the supported name attributes to prevent registration with the attributes that are not supported or in the wrong format. The following changes are made:
* [check_attributes](https://github.com/WalletConnect/blockchain-api/commit/ab4f9b9ac9b5b579dbf3ed578c24a324fecd83d4#diff-f8a4ed25bf7d7d3b6998382ac049bed43c3275bfb07ac13bc8f4c47be087fa76R44) function is added to check keys in the attributes map to contain [only supported attributes and check the attribute value format by regexp](https://github.com/WalletConnect/blockchain-api/commit/ab4f9b9ac9b5b579dbf3ed578c24a324fecd83d4#diff-e382530ad7aeb0bbd6f4f0ac9bbddf4cc3944e24c387114ecc2dd640cf9e071fR19) for the certain attribute type.
* minor refactoring: [moved all utilities functions to the …

feat(ens): check for supported attributes and value format

---

src/error.rs
src/handlers/proxy.rs
src/providers/mod.rs

At the moment when all provider weights for the chain are 0 because of rate limiting we are responding with the `Unsupported chain` to users which is confusing. 
This PR makes changes to respond with the `HTTP 503 Temporarily Unavailable` code and `Requested {chain_id} chain provider is temporarily unavailable` error message.
Not tested.

fix(rpc): respond with `temporarily unavailable` when no working providers found

---

src/analytics/mod.rs
src/analytics/onramp_history_lookup_info.rs
src/handlers/history.rs
src/providers/coinbase.rs

This PR extracts the onramp transactions history analytics.
The following fields are included in the [onramp transaction analytics object](https://github.com/WalletConnect/blockchain-api/pull/498/files#diff-11beafba26762442363d5775947e0edd9c71eb2d24696e09eacf659725a3f07eR8-R24):
Common:
* `timestamp`
* `latency_secs`
* `lookup_address`
* `project_id`
Geo data:
* `origin`
* `region`
* `country`
* `continent`
Transaction:
* `transaction_status`: Status of the transaction:
* `ONRAMP_TRANSACTION_STATUS_CREATED`
* `ONRAMP_TRANSACTION_STATUS_IN_PROGRESS`
* `ONRAMP_TRANSACTION_STATUS_SUCCESS`
* `ONRAMP_TRANSACTION_STATUS_FAILED`
* `purchase_currency`: Crypto currency being purchased. Example: `USDC` 
* `purchase_network`: Network used to deliver crypto to the user’s wallet in CAIP-2 format. …

feat(analytics): onramp transactions history analytics

---

src/env/pokt.rs
src/env/publicnode.rs
tests/functional/http/mod.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs

This PR adds Base (eip155:8453) chain support in Pokt/Grove and Publicnode providers. At the moment we are using only one provider for the Base, but we can spread the load across a few providers that support the Base chain.
* Base support for the Pokt/Grove provider,
* Base support for the Publicnode provider,
* Updating integration tests for the Pokt provider,
* Adding missed integration tests for the Publicnode provider.
* Updated integration tests in this PR.

feat(providers): adding Base chain support for Pokt and Publicnode providers

---

src/providers/mod.rs

This PR removes `unwrap()` from the `WeightedIndex` calculation and returns errors instead of panics.
[This is a followup](https://github.com/WalletConnect/blockchain-api/pull/507#pullrequestreview-1868202136).
Not tested.

fix: removing unwraps from the `WeightedIndex`

---

integration/names.test.ts
src/database/helpers.rs
src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/lib.rs
tests/functional/database.rs

This PR cleans up the name registration endpoint implementation according to the [SPEC](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-server-api#register-the-name).
* Removing `coin_type`, `chain_id `, `address` from the signing message payload to remove duplicating it. 
We have this data in the payload and the address is recovered from the signature, so we don't need to duplicate it.
* Storing the chain ID in the database in ENSIP-11 format without additional conversion from SLIP-44 to ENSIP-11 and vice versa. We are using the Ethereum namespace by default and agreed on the ENSIP-11 output format so we don't need to convert it to support future blockchains.
* Changing the name registration endpoint from `POST …

fix(ens): name registration endpoint cleanup

---

Cargo.lock
Cargo.toml
integration/names.test.ts
src/database/error.rs
src/database/helpers.rs
src/handlers/profile/attributes.rs
src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/lib.rs
src/utils/crypto.rs
tests/functional/database.rs

This PR adds an endpoint handler to update name attributes according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/203).
* `POST /v1/profile/account/:name/attributes` endpoint is added to handle the name attributes updating,
* Updated attributes map returns as a result. 
* [Integration test](https://github.com/WalletConnect/blockchain-api/pull/509/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1R129-R157) for the new endpoint to check attributes after updating.
The integration test was added to this PR.

feat(ens): updating name attributes handler

---

integration/names.test.ts
src/database/helpers.rs
src/handlers/profile/address.rs
src/handlers/profile/mod.rs
src/lib.rs
tests/functional/database.rs

This PR adds an endpoint handler to update the name address according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/204).
* `POST /v1/profile/account/:name/address` endpoint is added to handle the name address updating,
* Updated name address map returns as a result.
* [Integration test](https://github.com/WalletConnect/blockchain-api/pull/510/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1R160-R199) for the new endpoint to check the name addresses after updating.
The [integration test](https://github.com/WalletConnect/blockchain-api/pull/510/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1R160-R199) was added to this PR.

feat(ens): updating name address handler

---

src/error.rs
src/handlers/history.rs
src/handlers/identity.rs
src/handlers/portfolio.rs
src/handlers/profile/address.rs
src/handlers/profile/attributes.rs
src/handlers/profile/lookup.rs
src/handlers/profile/register.rs
src/handlers/profile/reverse.rs

This PR unifies errors in profile names handlers to use the `RpcError`.
This will deduplicate errors and unify them to handle in the frontend.
* Current integration tests are passed.

feat(ens): unifying errors

---

SUPPORTED_CHAINS.md
src/env/pokt.rs
tests/functional/http/pokt.rs

This PR adds the Klaytn Mainnet `eip155:8217` chain to the Pokt/Grove provider and to our supported chains for the RPC.
The full context: https://walletconnect.slack.com/archives/C03SMNKLPU0/p1707814841315879
This is a replacement for the #352 
- Integration test for the Pokt provider is passed.

feat(rpc): adding Klaytn mainnet to supported chains

---

Cargo.lock
Cargo.toml
src/lib.rs
src/metrics.rs

This PR introduces gathering and exporting of CPU and Memory usage metrics to the Prometheus.
System CPU(s) usage and Memory usage metrics are gathered by the app tokio task once per minute and record the data into the Prometheus exported metrics.
The reason for making this change is that we want to disable AWS CloudWatch ContainerInsights for the ECS.
The full context: https://walletconnect.slack.com/archives/C068RRL89HC/p1704549567804539
* Changing Grafana panels to use new metrics for CPU and Memory.
* Disabling `ContainerInsights` in the terraform ECS config.
Not fully tested, just run it locally.

feat(metrics): exporting CPU and Memory usage metrics to Prometheus

---

Cargo.lock
Cargo.toml
src/error.rs
src/handlers/history.rs
src/lib.rs
src/providers/coinbase.rs
src/providers/mod.rs
src/providers/zerion.rs
src/state.rs

This PR changes to use the shared `reqwest` client for the history endpoints instead of constructing the `hyper` client each time in the handler.
This change should provide the following benefits:
* (code) Making JSON requests using the `reqwest` is much easier than the hyper itself (it handles serialization and deserialization), the code is much clearer.
* (performance) When using the shared `reqwest` HTTP client we will use the internal connection pooling and reuse it ([suggested in the reqwest docs](https://docs.rs/reqwest/latest/reqwest/struct.Client.html#) to create it once and reuse it).
Tested locally:
1. Start the server locally with the `cargo run`.
2. Run the integration tests by `RPC_URL=http://localhost:3000  yarn integration`.
3. Tests successfully passed.

feat(history): using the shared `reqwest` http client

---

src/env/mod.rs
src/env/server.rs
src/state.rs

This PR adds new `RPC_PROXY_VALIDATE_PROJECT_ID` environment config parameter to disable project id validation check. 
This parameter is `true` by default and should be used for the local, staging debugging and tracing purposes.
Env config unit test.

feat(config): config parameter to disable project id check

---

integration/onramp.test.ts
src/error.rs
src/handlers/mod.rs
src/handlers/onramp/mod.rs
src/handlers/onramp/options.rs
src/lib.rs
src/providers/coinbase.rs
src/providers/mod.rs

This PR adds the new endpoint for getting buy options for the onramp payments from the [CB payment options endpoint](https://docs.cloud.coinbase.com/pay-sdk/docs/rest-api-reference#buy-options).
* `/v1/onramp/buy/options` GET parameters:
* `projectId` - project ID
* `country` - [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) two-digit country code string representing the purchasing user’s country of residence, e.g., US.
* `subdivision` (optional) - [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) two-digit country subdivision code representing the purchasing user’s subdivision of residence within their country, e.g. NY. Required if the country=“US” because certain states (e.g., NY) have state specific asset restrictions.
The new endpoint response object contains the following …

feat(onramp): adding onramp buy options endpoint

---

integration/onramp.test.ts
src/handlers/onramp/mod.rs
src/handlers/onramp/quotes.rs
src/lib.rs
src/providers/coinbase.rs
src/providers/mod.rs

This PR adds the new endpoint for getting buy quotes for the onramp payments from the [CB payment options endpoint](https://docs.cloud.coinbase.com/pay-sdk/docs/rest-api-reference#buy-quote).
* `/v1/onramp/buy/quotes` GET parameters:
* `projectId` - project ID
* `country` - [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) two-digit country code string representing the purchasing user’s country of residence, e.g., US.
* `subdivision` (optional) - [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) two-digit country subdivision code representing the purchasing user’s subdivision of residence within their country, e.g. NY. Required if the country=“US” because certain states (e.g., NY) have state specific asset restrictions.
* `purchaseCurrency` - ID of the crypto asset the user …

feat(onramp): adding onramp buy quotes endpoint

---

src/lib.rs

We have a rare 502 errors coming from the AWS Load Balancer. 
There are no 5xx server errors or any crashes on the app side. Investigation of the LB access logs and traffic dump showed that the 502 error was caused due to the TCP issue. Further investigation shows that the issue can be in the very low keep-alive timeout in our axum server. 
There are a few [#1](https://www.tessian.com/blog/how-to-fix-http-502-errors/), [#2](https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/) same issues found and possible solution is to increase the keep-alive to the AWS ALB default value of 60 seconds.
This PR increases keep-alive values to 65 seconds to fix the 502 Load Balancer errors.
Context: https://walletconnect.slack.com/archives/C03SCF66K2T/p1707949790838309
Not tested.

fix(server): increasing keep-alive timeouts

---

src/env/mod.rs
src/env/near.rs
src/env/pokt.rs
src/lib.rs
src/providers/mod.rs
src/providers/near.rs
tests/functional/http/mod.rs
tests/functional/http/near.rs
tests/functional/http/pokt.rs

[We have `Near` support in our Supported chains](https://github.com/WalletConnect/blockchain-api/blob/9a4c0b5efd7f8f975307a9e0e6f493adaf434766/SUPPORTED_CHAINS.md?plain=1#L26), but the only provider for it is Omnia which mostly always in a rate-limited state, so we don't have any `Near` successful requests for a long time.
This PR adds the following changes: 
* Adds the Near protocol public RPC to our providers list,
* Adds Near support for the Pokt/Grove provider.
* Adds tests for the Near protocol RPC.
* Functional integration tests are included in this PR for new Near public RPC provider and Pokt.

fix(providers): adding more `Near protocol` support

---

SUPPORTED_CHAINS.md
src/env/pokt.rs
src/env/publicnode.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs

Since Goerli's sunset is now planned for this year, we have requests for support Holesky in our RPC.
This PR adds support to the Holesky testnet `eip155:17000` in our RPC by using our Pokt and Publicnode providers.
Resolves #533
Tests for providers are updated.

feat: adding Holesky to the supported chains

---

terraform/monitoring/panels/ecs/cpu.libsonnet

This PR is changing to use Prometheus data for the CPU usage in Grafana instead of the AWS CloudWatch Container Insights data which should be disabled soon.
* Data source and query are changed
* Alert for the CPU usage greater than `70` is changed.
This is a followup for #514 
It is tested manually by putting the query into the Grafana UI.

feat(monitoring): changing to use Prometheus data for the CPU usage

---

terraform/monitoring/panels/ecs/cpu.libsonnet

This PR increases the CPU utilization alarm threshold to 25 minutes same as we have in the Relay to allow autoscaling provisioning and alarm if it's not scaled along with the high CPU usage.
Not tested.

fix(monitoring): increasing CPU alarm threshold

---

terraform/monitoring/panels/ecs/availability.libsonnet
terraform/monitoring/panels/proxy/errors_non_provider.libsonnet

This PR removes `HTTP 503 Temporary Unavailable` error from the availability chart/alert and from the non-provider errors chart.
The reason for this change is that we are returning 503 error to clients when we are rate-limited by the provider.
Put the updated Prometheus queries to the Grafana, the updated chart should appear.

fix(monitoring): removing 503 from non-providers errors

---

SUPPORTED_CHAINS.md
src/env/mantle.rs
src/env/mod.rs
src/env/publicnode.rs
src/lib.rs
src/providers/mantle.rs
src/providers/mod.rs
terraform/monitoring/dashboard.jsonnet
tests/functional/http/mantle.rs
tests/functional/http/mod.rs
tests/functional/http/publicnode.rs

This PR adds [Mantle](https://mantle.xyz) chain `eip155:5000` and testnet `eip155:5001` to supported chains.
* Mantle public RPC endpoints for the mainnet and testnet were added as a `Mantle` provider.
* Mantle mainnet added to the chains list for the `Publicnode` provider.
* Tests for the Mantle provider were added.
* Tests for the Publicnode provider were updated.
* Grafana panels for the Mantle chain were added.
* Supported chains list was updated.
Resolves #537 
Provider functional tests.

feat(providers): adding Mantle to supported chains

---

SUPPORTED_CHAINS.md
src/env/near.rs
src/env/omnia.rs
src/env/pokt.rs
tests/functional/http/mod.rs

This PR changes the chain Id for the `Near` to be CAIP-2 compatible and becomes `near:mainnet` instead of `near`.
According to the Grafana chain Ids requests, at the moment we don't have any Near traffic yet (we've added it recently), so we can switch it without migration.
Integration tests.

fix(providers): `Near` chain ID to be CAIP-2 compatible

---

terraform/monitoring/panels/ecs/availability.libsonnet

This PR fixed the typo in excluding HTTP 503 error from the availability (from #546 ). 
Instead of excluding 503, we were excluded 530.
Not tested.

fix(monitoring): fixing typo in excluding 503 from availability

---

SUPPORTED_CHAINS.md
src/env/omnia.rs
src/env/pokt.rs
src/handlers/proxy.rs
tests/functional/http/pokt.rs

Updates the Solana chain ID to be correct. [Slack conversation](https://walletconnect.slack.com/archives/C04SYT4LU2W/p1709656775702379?thread_ts=1709319338.504139&cid=C04SYT4LU2W)
Also removes `solana-mainnet` alias as there is no indication of traffic using this chain ID for last 30 days.
Removes `to_lowercase()` on chain ID as [chain IDs are case-sensitive](https://chainagnostic.org/CAIPs/caip-2#syntax).
New test

fix: correct Solana chain ID

---

Cargo.lock
Cargo.toml
integration/balance.test.ts
integration/history.test.ts
src/error.rs
src/handlers/balance.rs
src/handlers/mod.rs
src/lib.rs
src/providers/coinbase.rs
src/providers/mod.rs
src/providers/zerion.rs
src/utils/crypto.rs

This PR adds the new account balance endpoint `/v1/account/{address}/balance` according to the [specification](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-server-api#balance).
* A new `balance` provider trait was added,
* Zerion was added as a first account balance provider,
* Handler for the endpoint was implemented https://github.com/WalletConnect/blockchain-api/pull/563/commits/1dcd06ef90d7667da0d94687c57e717d177f3d1e,
* Fixing CAIP-2 to human readable chain IDs converter by using own enum list instead of Ethers-rs to be compatible with the Zerions chain-ids and Coinbase provider formats that is used for the filtering https://github.com/WalletConnect/blockchain-api/pull/563/commits/750c95f140dd78a1e85235277f65fb6c63cbf6d2,
* …

feat: account balance endpoint

---

src/providers/zerion.rs

This PR making changes to the handling of the Zerion provider responses to allow pass HTTP 202 code.
Zerion API documentation suggests handling 202 so we should pass it and handle it with the proper message in the frontend:
```
If the address was not added before it is possible that this endpoint will return 202 status. It means that positions for the wallet are not prepared yet, but will be available soon.
```
Current integration tests.

fix(zerion): allowing to pass HTTP 202 code

---

integration/convert.test.ts
src/env/mod.rs
src/error.rs
src/handlers/convert/mod.rs
src/handlers/convert/tokens.rs
src/handlers/mod.rs
src/lib.rs
src/providers/mod.rs
src/providers/one_inch.rs
src/utils/crypto.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR implements `/v1/convert/tokens` endpoint for the list of available tokens for the swap according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/207/files#diff-f64bf5c2b17c9c6d32ae9d85d9a1ce5a4aa07cb680c6f4085de94d3c4915b9d9R284-R306).
* A new `ConversionProvider` trait was added,
* 1inch provider implementation for the `ConversionProvider` trait,
* New endpoint handler implementation,
* `format_to_caip10` and `disassemble_caip2` utils were added.
*This is an Alpha release implementation to support only single-chain swaps*
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/567/commits/3be8a9b6f6b1e1b82e10fac12bf543f82f21dba3) for the endpoint and [unit …

feat(conversion): available tokens list endpoint implementation

---

integration/convert.test.ts
src/handlers/convert/mod.rs
src/handlers/convert/quotes.rs
src/lib.rs
src/providers/mod.rs
src/providers/one_inch.rs
src/utils/crypto.rs

This PR implements `/v1/convert/quotes` endpoint to get swap quotes between two assets (single chain) according to the [API SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/207/files#diff-f64bf5c2b17c9c6d32ae9d85d9a1ce5a4aa07cb680c6f4085de94d3c4915b9d9R308-R332).
* `1inch` provider implementation updates for the quotes provider agnostic trait,
* New endpoint handler implementation,
* `disassemble_caip10` utility was added.
*This is an Alpha release implementation to support only single-chain swaps*
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/568/files#diff-d2a40c4ae4e4965cd2ea19db3965e98a04e70177954587a2a3edecfcf1263ce0) for the endpoint and [unit tests](https://github.com/WalletConnect/blockchain-api/pull/568 …

feat(conversion): conversion quotes endpoint implementation

---

integration/convert.test.ts
src/handlers/convert/approve.rs
src/handlers/convert/mod.rs
src/handlers/convert/quotes.rs
src/lib.rs
src/providers/mod.rs
src/providers/one_inch.rs

This PR implements `/v1/convert/build-approve` endpoint to build the approval transaction for eip2612 incompatible tokens swap (single chain) according to the [API SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/207/files#diff-f64bf5c2b17c9c6d32ae9d85d9a1ce5a4aa07cb680c6f4085de94d3c4915b9d9R334-R364).
* `1inch` provider implementation updates for the approval transaction agnostic trait,
* New endpoint handler implementation.
*This is an Alpha release implementation to support only single-chain swaps*
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/570/files#diff-d2a40c4ae4e4965cd2ea19db3965e98a04e70177954587a2a3edecfcf1263ce0) for the endpoint.

feat(conversion): approve transaction endpoint implementation

---

integration/convert.test.ts
src/handlers/convert/mod.rs
src/handlers/convert/transaction.rs
src/lib.rs
src/providers/mod.rs
src/providers/one_inch.rs

This PR implements `/v1/convert/build-transaction` endpoint to build the conversion transaction for tokens swap (single chain) according to the [API SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/207/files#diff-f64bf5c2b17c9c6d32ae9d85d9a1ce5a4aa07cb680c6f4085de94d3c4915b9d9R366-R399).
* `1inch` provider implementation updates for the transaction builder,
* New endpoint handler implementation,
* Integration test was implemented for the new endpoint.
*This is an Alpha release implementation to support only single-chain swaps*
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/572/files#diff-d2a40c4ae4e4965cd2ea19db3965e98a04e70177954587a2a3edecfcf1263ce0R67-R96) for the endpoint.

feat(conversion): convert transaction builder endpoint implementation

---

SUPPORTED_CHAINS.md

This PR adds a footnote to RPC chains where we use only public providers and can't guarantee any SLA (availability).
We should link to this list in our SLA to exclude out-of-SLA chains.
It doesn't need a test.

feat(docs): adding a footnote for not guaranteed (availability) RPC chains

---

integration/supported-chains.test.ts
src/handlers/mod.rs
src/handlers/supported_chains.rs
src/lib.rs
src/providers/mod.rs

Adds a basic endpoint to return a list of supported CAIP-2 chain IDs.
Resolves #566 
New integration test

fix: supported chains endpoint

---

SUPPORTED_CHAINS.md
src/env/base.rs
src/env/infura.rs
src/env/pokt.rs
tests/functional/http/base.rs
tests/functional/http/infura.rs
tests/functional/http/pokt.rs

[The Base moved the test network from Goerli to Sepolia](https://base.mirror.xyz/kkz1-KFdUwl0n23PdyBRtnFewvO48_m-fZNzPMJehM4). Since the end of January 2024, Goerli shouldn't be used as a test network for the Base.
This PR fixing to use the Sepolia `eip155:84532` as the testnet for Base.
Tested by the updated providers test.

fix(providers): changing the Base testnet to Sepolia

---

SUPPORTED_CHAINS.md
src/env/infura.rs
src/env/publicnode.rs
src/env/zora.rs
tests/functional/http/infura.rs
tests/functional/http/publicnode.rs
tests/functional/http/zora.rs
tests/functional/websocket/infura.rs

This PR updates provider's supported chains list and tests to the up-to-date state:
* Infura
* `optimism-goerli` was removed in favor of `optimism-sepolia`,
* `arbitrum-goerli` was removed in favor of `arbitrum-sepolia`,
* `Base Sepolia` was removed as it's not supported by the provider anymore.
* Publicnode
* `Ethereum goerli` was removed as it's not supported by the provider anymore.
* Zora
* `Zora Goerli` was removed in favor of `Zora Sepolia`. 
Tested by running updated integration tests for each provider.

fix(providers): updating providers supported chains (removing Goerli)

---

src/handlers/identity.rs

This PR adds proper handling of the `0x` (method not exist) RPC responses on the avatar lookup passing the result to the `ethers-rs`.
At the current state, we have rare app panics from `ethers-rs` when the RPC responds with `0x` for some of the identity requests:
```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/40cc8cc/ethers-providers/src/rpc/provider.rs:1353:10
could not abi-decode bytes to address tokens: InvalidName("please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist")
```
Not tested.

fix(identity): handling `0x` RPC response for identity

---

integration/balance.test.ts
src/handlers/balance.rs
src/providers/zerion.rs

This PR adds a missed token contract address for the balances.
* Updated integration test.

fix(balance): adding token contract address

---

integration/balance.test.ts

This PR fixed the balance endpoint integration test by checking the `address` can be `undefined` but not `null`.
* Run integration test locally.

fix(tests): fixing address to be `undefined` and not `null`

---

src/providers/zerion.rs

This PR fixes the bug where we are using the only first address token implementation instead of using the actual chain in the Zerion response.
* Manually tested by comparing the address with the actual token contract address.

fix(balance): using the correct implementation chain address instead of just first

---

src/handlers/proxy.rs
terraform/variables.tf

If a provider returns a non-200 status code, we return this as-is instead of transforming into a 503 which we use to indicate a provider-side error. [Slack conversation](https://walletconnect.slack.com/archives/C03SCF66K2T/p1711134896606019?thread_ts=1711133669.730169&cid=C03SCF66K2T)
Also fixes that the default min/max autoscaling was set to 1 incorrectly. Also updated to match in Terraform.
Not tested

fix: provider-returned non-200s should be 503s & fix autoscaling

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/ecs/availability.libsonnet
terraform/monitoring/panels/ecs/cpu.libsonnet
terraform/monitoring/panels/ecs/memory.libsonnet
terraform/monitoring/panels/lb/error_5xx.libsonnet

Fixes that the alarm was named the wrong thing. Also that the alarm was mis-tuned for the current number of 5xx errors.
[Slack conversation](https://walletconnect.slack.com/archives/C058RS0MH38/p1711378395824369)
Not tested

fix: alarm config

---

terraform/monitoring/panels/ecs/cpu.libsonnet

This PR increases the CPU threshold interval for alarming to remove false alarms.
Not tested.

fix(monitoring): increasing the CPU alarm interval

---

src/lib.rs

This PR decreased system metrics sampling interval from `60` seconds to `10` seconds, for a better average accuracy.
Not tested.

fix(monitoring): decreasing system metrics sampling interval

---

src/providers/zerion.rs

According to our [API specification for balance](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-server-api#success-response-body-4) the token address should be null for the native tokens. Zerion endpoint returns `0x0000000000000000000000000000000000001010` for the Polygon native token that confusing our users. 
This PR adds the exception of handling the token address for the Polygon.

fix(zerion): handling properly `Polygon` native token address in balance

---

Cargo.lock
Cargo.toml
src/analytics/mod.rs
src/lib.rs

This PR updating the [utils-rs](https://github.com/WalletConnect/utils-rs) to the latest `0.8.0` tag.
The `0.8.0` version introduces [breaking changes in analytics](https://github.com/WalletConnect/utils-rs/pull/13) (introducing observers). 
This PR making appropriate changes in the blockchain-api to support the latest version. The changes made are the same as in the relay [#1406](https://github.com/WalletConnect/rs-relay/pull/1406) to update the analytics (converting to use observer).
Not tested.

feat(analytics): updating `utils-rs` to the `0.8.0` tag

---

src/analytics/onramp_history_lookup_info.rs
src/handlers/history.rs

This PR adds a unique transaction ID to the OnRamp analytics to give the ability to aggregate duplicates.
* Not tested.

feat(analytics): adding transaction ID to the onramp analytics

---

src/env/pokt.rs
tests/functional/http/pokt.rs

This PR removes the deprecated Ethereum Goerli and Polygon Mumbai endpoints from the Pokt/Grove provider and adds the Ethereum Sepolia endpoint.
* Tested by the updated provider's integration test.

fix(providers): removing deprecated endpoints from Grove/Pokt

---

src/env/getblock.rs
src/providers/mod.rs

This PR changing priorities to `Low` for the most used chains `eip155:1` and `eip155:56` for the GetBlock provider, since our quota drains very fast with the current priority.
Not tested, but should be tested by the current integration and canary tests.

fix(providers): varying priority for the GetBlock provider

---

terraform/ecs/cluster.tf

This PR disables AWS CloudWatch Container Insights for the ECS after the CPU #528  and Memory #529 metrics are migrated to the Prometheus and we don't need the Container Insights anymore.
* ~~Bump `ci_workflows` tag to `0.2.6`,~~
* Changing ECS `containerInsights` to `disable`.
Not tested.

feat(monitoring): disabling container insights

---

integration/fungible_price.test.ts
src/error.rs
src/handlers/fungible_price.rs
src/handlers/mod.rs
src/lib.rs
src/providers/mod.rs
src/providers/zerion.rs

This PR implements a fungible price endpoint according to the [SPEC proposal](https://walletconnect-specs-git-feat-tokenprices-walletconnect1.vercel.app/2.0/specs/servers/blockchain/blockchain-server-api#price) to get actual prices.
Since the API is compatible with different providers like Zerion and 1Inch, the Zerion provider adapter implementation was added.
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/608/files#diff-4493ff1a59d5bf63fc4e0b226e9908932f9c2ef71dafddf6ecf99f00c5739487).

feat(providers): fungible price endpoint implementation

---

src/metrics.rs
src/state.rs

This PR adds additional tracing logging to investigate 502 errors (possibly malformed headers) during the project ID validation.
Not tested.

feat(logging): adding additional tracing on project id validation

---

terraform/monitoring/panels/lb/error_5xx.libsonnet

This PR increases the period from `0` to `3` minutes for `5xx` alerts monitoring and decreases the alert threshold to `1000`.
Not tested.

feat(monitoring): using `3` minutes period for 5xx alerts

---

src/lib.rs

This PR decreases the keep-alive intervals.
The keep-alive ping interval should logically be shorter than the keep-alive timeout. 
We have the same now and this might risk the connection being closed just as a keep-alive message is sent to the ALB, which defeats the purpose of detecting whether the connection is still active.
The keep-alive ping interval is set to `10` seconds.
The idle timeout also decreased to `60` seconds to align with the ALB settings.
*Not tested (can't be tested without deploying to the at least staging).

fix(server): decreasing keep-alive intervals

---

src/lib.rs

This PR making the following changes:
* Enables `tcp_nodelay` for a lower latency (this means data is sent immediately over the network without waiting for the buffer to fill or for an acknowledgment of previously sent data).
* Enables `tcp_sleep_on_accept_errors` to log errors if there are no unix sockets available and wait other than just silently shutdowns. So we can catch the exact error if this happens.
* Increasing retrying for keep-alive from 1 to 5.
* Not tested.

fix(server): enabling `tcp_nodelay` and `tcp_sleep_on_accept_errors`

---

Dockerfile

This PR adds `curl` to the service runtime Docker image. The `curl` will be used for the ECS Container health check command by using `curl -sS http://localhost:8080/health || exit 1` in the ECS configuration.
Built the Docker image locally.

fix(Docker): adding `curl` to the Docker runtime image

---

src/analytics/identity_lookup_info.rs
src/handlers/identity.rs

Since the ethers library uses a hardcoded registry contract address, it doesn't support non-mainnet resolution anyway. So hardcoding mainnet. Additionally, changing the query params that this endpoint accepts to just be projectId since the other parameters were for the RPC endpoint.
[Slack conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1712418300123819?thread_ts=1712373328.103609&cid=C03RVH94K5K)
Not tested

fix: hardcode mainnet

---

src/analytics/identity_lookup_info.rs
src/handlers/identity.rs

This reverts commit d8ed82d050cb2f08ac2320f53164fa2f796fd515 because it causes a permanent error:
`NameLookup("RpcError: UnsupportedChain(\"1\")`.
Not tested.

fix(revert): hardcode mainnet (#610)

---

src/error.rs
src/handlers/identity.rs

This PR adds a proper handling of the following errors from the RPC call during the identity lookup:
* `Project Quota`: We have a lot of `HTTP 500` errors with the `NameLookup("RpcError: QuotaLimitReached")` message that should be returned as `HTTP 429`.
* `503 Service Unavailable`: When the RPC provider is unavailable.
All of the above errors are HTTP 500 now and should be distinguished.
* Current integration tests cover the good and bad names resolution. Quota limiting can't be tested as we have high quotas in prod.

fix(identity): handling properly errors in RPC call response

---

src/error.rs
src/handlers/identity.rs

This PR adds proper RPC call error handling during the avatar lookup in the identity endpoint. The error handling for the avatar RPC lookup is the same as for the name lookup, so the handling flow was consolidated into the function. Two different errors `NameLookup` and `AvatarLookup` were consolidated into one `IdentityLookup`. The source of the call of `IdentityLookup` error can be traced using the tracing `instrument` so we don't need two different errors.
* Start the server locally and run identity lookup. The error handling was as expected.

fix(identity): proper RPC errors handling in avatar lookup

---

integration/identity.test.ts
src/analytics/identity_lookup_info.rs
src/handlers/identity.rs
src/handlers/mod.rs

This PR is the reopened #610 with the tiny fix of the mainnet in CAIP-2 format and updated integration test.
* Started the server locally. Run the identity lookup with the wrong `chainId` and without `chainId` query argument. The result was a successful lookup response.

fix(identity): hardcode ethereum mainnet

---

SUPPORTED_CHAINS.md
src/env/infura.rs
src/env/publicnode.rs
tests/functional/http/infura.rs
tests/functional/http/publicnode.rs
tests/functional/websocket/infura.rs

This PR removing Ethereum Goerli and Polygon Mumbai testnets, [as they are sunsetted on April 13](https://blog.ethereum.org/2023/11/30/goerli-lts-update). 
* Updated providers tests.

fix(providers): removing Goerli and Polygon Mumbai chains

---

SUPPORTED_CHAINS.md
src/env/infura.rs
tests/functional/http/infura.rs

This PR adds the Linea Mainnet chain to our supported chains.
The full context of the [request for the Linea chain](https://walletconnect.slack.com/archives/C03SCF66K2T/p1712580939102439).
* Updated Infura provider test.

feat(providers): adding Linea mainnet to supported chains

---

src/error.rs
src/handlers/proxy.rs
src/metrics.rs
src/providers/mod.rs

This PR implements a retrying mechanism for RPC calls. This should be useful for the user experience when one of the providers returns a `rate-limited` error and we can retry up to max retries (currently is `3`) or fall with the appropriate error if all providers are rate-limited.
Metrics for attempts per chain ID are also added.
Resolve #265 and #452 
* Integration and provider tests.

feat(rpc): adding rpc call retrying

---

src/providers/mod.rs

This PR updates #624 with the minor fix to exclude zero-weighted providers from the iteration count, as it doesn't make sense to make additional iterations for zero-weighted providers during the sampling.
1. Manually tuned to zero-weight a few providers for a certain chain ID,
2. Run rpc call for the certain chain ID,
3. The number of iterations during the sampling is equal to the non-zero weighted providers count.

fix(weights): excluding zero weight providers from iteration

---

SUPPORTED_CHAINS.md
src/env/zksync.rs
tests/functional/http/zksync.rs

This PR removes zkSync Goerli testnet chain `eip155:280` and adds zkSync Sepolia Testnet `eip155:300` because of the Goerli deprecation. [zkSync endpoints docs](https://docs.zksync.io/build/api.html#rpc-endpoint-urls).
* Updated provider test.

fix(providers): removing zkSync Goerli testnet, adding Sepolia instead

---

src/lib.rs

This PR adds `x-sdk-type` and `x-sdk-version` headers to CORS allowed headers list.
This is useful for different behaviors based on the client SDK version. Currently, we need to make an exception for the certain SDK-version for the balances endpoint.
* Not tested.

feat: adding sdk type and version to CORS allowed headers

---

integration/balance.test.ts
src/handlers/balance.rs

This PR adds skipping the balance Zerion call and responds with an empty array if the `x-sdk-version` was not passed in the headers. This should fix the issue of redundant calls in sdk versions <= 4.1.8 https://github.com/WalletConnect/web3modal/pull/2157. By checking the `x-sdk-version` presence we are distinguishing the SDK version requests <= version 4.1.8.
The context in the [Slack thread](https://walletconnect.slack.com/archives/C03SCF66K2T/p1713177390071089).
* Requesting the balance endpoint with the `x-sdk-version` header and without.

fix(balance): respond with an empty balance for sdk version <= 4.1.8

---

integration/convert.test.ts
src/handlers/convert/approve.rs
src/handlers/convert/quotes.rs
src/handlers/convert/transaction.rs
src/providers/one_inch.rs

This PR changes `amount` to `String` instead of `usize`. Since the `usize` is pretty much huge in size we should protect ourselves from overflow of `usize`. Also, this adds better compatibility with the client's JS integration.
We don't need any migration because this feature is under development now.
* Updated integration test.

fix(conversion): changing amounts to `String`

---

integration/convert.test.ts
src/error.rs
src/providers/one_inch.rs

This PR adds passing through error message description from the 1Inch provider in case wrong parameters were passed and `HTTP 400 Bad Request` was returned from the provider request. This adds context to the client about what parameters were wrong.
* New [integration test were implemented](https://github.com/WalletConnect/blockchain-api/pull/635/files#diff-d2a40c4ae4e4965cd2ea19db3965e98a04e70177954587a2a3edecfcf1263ce0R98).

feat(conversion): passing through error description in case of wrong parameters

---

integration/convert.test.ts
src/handlers/convert/approve.rs
src/providers/one_inch.rs

This PR modified the `amount` parameter to become optional to allow the infinite amount for the approval since `0` in the amount means that no approval at all. So we should handle both cases: infinite amount and `0`.
* Updated integration test for the endpoint.

fix(conversion): making `amount` optional in approval

---

integration/fungible_price.test.ts
src/providers/zerion.rs

This PR adds an address representation for the `eth` native token as `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`. By default, Zerion uses `null` for the address of the native token, but for consistency across all endpoints and support for swaps, it's better to stick to the `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` representation of the native token address.
* [New integration test](https://github.com/WalletConnect/blockchain-api/pull/639/files#diff-4493ff1a59d5bf63fc4e0b226e9908932f9c2ef71dafddf6ecf99f00c5739487).

fix(fungibles): adding `eth` token address representation

---

src/providers/zerion.rs

This PR is a hotfix to handle properly null responses for the price that happened for some of tokens responses.

fix(Zerion): handling of null price response

---

src/providers/zerion.rs

This PR adds an additional filter to Zerion requests to filter out only non-spam items in transactions history and address balance since we don't need to return spam items. According to the Zerion API docs filter `filter[trash]` is applied.

fix(Zerion): return only non-spam items

---

src/utils/crypto.rs

This PR fixes a bug where malformed CAIP-2 and CAIP-10 addresses can cause panic in crypto utils, because of out-of-the-range vector access. Properly handling and additional errors were added.
* Updated unit tests.

fix(utils): properly handling of malformed CAIP-2 and 10

---

src/analytics/balance_lookup_info.rs
src/analytics/mod.rs
src/handlers/balance.rs

This PR adds analytics export for balance lookups with the following analytics item structure:
* timestamp,
* latency,
* symbol (token symbol),
* implementation chain ID
* quantity (token quantity according to decimals),
* value
* price
* currency
* address (lookup address)
* project_id,
* origin,
* region,
* country,
* continent.
Analytics export_prefix: `blockchain-api/balance-lookups`, export_name: `balance_lookups`.
* Not tested.

feat(analytics): adding analytics for balance lookups

---

integration/fungible_price.test.ts
src/handlers/fungible_price.rs
src/providers/mod.rs
src/providers/one_inch.rs
src/providers/zerion.rs
src/utils/crypto.rs

This PR changes the provider for fungibles prices from Zerion to 1Inch to support native token prices from 1Inch conversion parameters. 1Inch uses `0xeee` for the native tokens and Zerion uses just unique internal IDs. 
This change will fix errors while getting the conversion token prices. Before this change, we used the hardcoded list of the native tokens and Zerion ids.
Updated integration tests.

feat(providers): using 1Inch instead of Zerion for fungible prices

---

Dockerfile

This PR updates the Docker rust image to the latest stable Debian version: (12) `Bookworm`. This bump will also fix the [foundry GLIBC building error](https://github.com/WalletConnect/blockchain-api/actions/runs/8988920075/job/24691402178#step:8:1326).
The docker image was built successfully and without GLIBC error locally.

feat(Docker): bumping the Rust image to `bookworm`

---

integration/names.test.ts
src/error.rs
src/handlers/identity.rs

This PR adds the local name lookup if the name is not present in the ENS contract lookup. Since our `identity` endpoint API supports only one name return, we will use the ENS as a first priority and use our local gateway name resolver as a second-level priority. 
This extends our `identity` endpoint to lookup and cache our names registry and local registered names resolution will be available for all web3m users without any API modification.
A new [integration test was added](https://github.com/WalletConnect/blockchain-api/pull/651/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1R247).

feat(identity): adding local names resolution support

---

src/env/pokt.rs
tests/functional/http/pokt.rs

This PR adds zkSync support to the Pokt/Grove provider. zkSync support was recently announced by the Pokt/Grove.
Provider test was updated, zkSync test was added.

feat(providers): adding zkSync support to Pokt

---

integration/names.test.ts
src/handlers/profile/mod.rs

This PR making changes for the off-chain names gateway service to move from the `wc.ink` to `wcn.id` root zone.
This change is necessary as we have decided to move forward with the `wcn.id` zone instead of `wc.ink`.
Integration tests were changed to use the updated root zone.

feat(names): moving to `wcn.id` root zone

---

src/env/mod.rs
src/providers/mod.rs
src/providers/one_inch.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds `referrer` to the 1Inch `quote` and `swap` calls to pass fees depositor address. This will add fees redirection. For security reason, the referrer is stored as a TFC variable.
Configuration variables test were updated.

feat(convert): adding `referrer` to 1Inch provider

---

src/providers/one_inch.rs

This PR adds a `fee` argument that passed to `quote` and `swap` 1Inch endpoints with the value of `0.85` that was agreed upon for the `referrer` integration and using the fee depositor.
Current integration tests for converts.

fix(one_inch): adding `fee` argument to quotes and swap

---

integration/convert.test.ts
src/handlers/convert/quotes.rs
src/providers/one_inch.rs

This PR adds an optional `gasPrice` parameter to the convert quote endpoint to allow users to choose the gas price instead of using the default fastest. [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/232) is also updated.
The integration test was updated.

feat(convertion): adding optional `gasPrice` to the quote endpoint

---

src/providers/coinbase.rs

This PR removes the excessive content JSON header from the `json` reqwest method as [this header is added inside the method itself](https://github.com/seanmonstar/reqwest/blob/e639bdc1264c266a84dae3bae3193e07cae6861b/src/async_impl/request.rs#L445).
* Current integration tests are passed.

fix: removing excessive json header

---

Cargo.lock
Cargo.toml

Fix failing CI: https://github.com/WalletConnect/blockchain-api/actions/runs/9283394702/job/25544371126
Remaining work:
Not tested

fix: quotas query param name

---

.github/workflows/event_release.yml

Relax paths-ignore so releases get executed if Cargo.toml|lock or workflow files change.
Not tested

fix: relax paths-ignore

---

integration/balance.test.ts
src/handlers/balance.rs
src/handlers/convert/tokens.rs
src/handlers/fungible_price.rs
src/handlers/mod.rs
src/providers/mod.rs
src/providers/one_inch.rs

This PR fixes the bug where a forced balance update is invoked, but no updated balance in response due to the absence of the token in the balance object due to zero balance. 
As a fix, we are injecting the token balance item if there are no token item found in the current Zerion response that overrides the recent balance update from JSON-RPC or contract response.
[Slack conversation.](https://walletconnect.slack.com/archives/C03RVH94K5K/p1716557794631039?thread_ts=1713176741.098649&cid=C03RVH94K5K)
* [A new integration test was implemented](https://github.com/WalletConnect/blockchain-api/pull/661/files#diff-13d7369ef8e242470eace4b6a7039baf1685c66f865763226588f2c6bc652dccR93).

fix(balance): injecting forced balance update to the zero balance token response

---

justfile
src/analytics/message_info.rs
src/analytics/mod.rs
src/handlers/balance.rs
src/handlers/identity.rs
src/handlers/mod.rs
src/handlers/profile/address.rs
src/handlers/profile/attributes.rs
src/handlers/profile/register.rs
src/utils/crypto.rs

Adds the source of the RPC call to the analytics export. [Slack conversation](https://walletconnect.slack.com/archives/C04HK47TNBB/p1717082696327969?thread_ts=1717064623.738729&cid=C04HK47TNBB)
Also fixes `devloop` so that it works w/o tflint and tfsec. Also runs checks under stable Rust as this is what CI uses.
Not tested

feat: rpc source analytics

---

src/lib.rs
terraform/monitoring/panels/lb/error_5xx.libsonnet

As per [this discussion](https://walletconnect.slack.com/archives/C058RS0MH38/p1718212843263849?thread_ts=1718209220.781689&cid=C058RS0MH38) I don't think we need the service executor anymore. This closes ELB connections and likely results in 502 errors to clients. This existed to reduce memory load but now we use an ALB which decouples client connections from server connections.
Not tested

fix: remove service executor

---

integration/names.test.ts
src/handlers/profile/register.rs

This PR adds an address for the mainnet ENSIP-11 cointype `60` if the user is not provided it during the registration.
This should be set by default since we are missing this in the UI when the user is not on the Mainnet chain the name address is only added for the non-mainnet cointype. In this case, ENS.app resolution will not work, since the ENS contracts are on the Mainnet and Sepolia.
The full context: [Slack](https://walletconnect.slack.com/archives/C03RVH94K5K/p1718194512697689?thread_ts=1718179147.968809&cid=C03RVH94K5K)
* New integration test.

feat(names): adding mainnet cointype `60` address by default

---

src/database/helpers.rs
src/lib.rs
src/metrics.rs
tests/functional/database.rs

This PR implements an account names counter metrics watcher that periodically checks the names rows count in the `names` database table and stores the value to the `account_names_count` metrics gauge.
The new Grafana dashboard PR #674 
* New unit test for database helper function,

feat(metrics): implementing account names count metrics watcher

---

tests/context/mod.rs
tests/context/server.rs

This PR fixes RPC providers [integration test compilation errors](https://github.com/WalletConnect/blockchain-api/actions/runs/9548607111/job/26317101711#step:4:1099) after removing the rudimental code in #673.
* Passed `cargo test coinbase_provider -- --ignored` locally,
* Passed `cargo clippy --workspace --all-features --all-targets -- -D warnings` locally.

fix(tests): fixing providers integration tests compilation

---

src/utils/network.rs

This PR changes the user IP to get the last IP from the list in `X-Forwarded-For` instead of the first since the AWS Load Balancer appends the IP to the end.
Not tested.

fix(network): using the last forwarded IP from the list

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/names/registered.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds a new Grafana dashboard to monitor how many account names were registered.
This is a follow-up of #672.
Not tested.

feat(grafana): adding account names counter dashboard

---

src/analytics/account_names_info.rs
src/analytics/mod.rs
src/handlers/profile/register.rs

This PR adds name registration analytics with the following data:
* Name,
* Owner's address,
* Registration chain ID (in case the user is not at the mainnet),
* Geo data: origin, region, country, continent.
The analytics data is stored in the `blockchain-api/name-requests/name_registrations` S3 bucket.
Not tested.

feat(analytics): adding names registrations analytics

---

terraform/variables.tf

This PR tunes the rate-limiting token bucket settings:
* Decreasing the maximum token bucket size to 30.
* Increasing refill rate to 3 per second.
The full context of the reason for this change: [Slack](https://walletconnect.slack.com/archives/C03SCF66K2T/p1718608552397669)
Not tested.

fix(ratelimiting): tuning token bucket settings

---

integration/ratelimiting.test.ts

This PR tuning max token bucket size variables to `30` for the integration tests as a follow-up from #675. 
This should fix the rate-limiting [integration test error](https://github.com/WalletConnect/blockchain-api/actions/runs/9580015523/job/26420144164#step:5:49).
* Tested by running tests locally.

fix(tests): tuning rate-limiting integration test

---

Cargo.lock
yarn.lock

This PR updates dependencies versions in `Cargo.lock` and `yarn.lock` to fix security breaches found by the dependabot.
* [The list of dependabot issues](https://github.com/WalletConnect/blockchain-api/security/dependabot) that will be fixed.
* Running `cargo run` and `cargo test` were successful.

fix: updating `Cargo.lock` and `yarn.lock`

---

terraform/res_network.tf
terraform/variables.tf

Adds VPC peering to the IRN VPC
Manually

feat(terraform): IRN VPC Peering

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR bumps the shared GitHub Action workflow `ci_workflows` version to the latest [0.2.11](https://github.com/WalletConnect/ci_workflows/releases/tag/0.2.11) to support fetching private repositories (submodules).
This is required for the #681 
* Tested by using the branched version of the workflow in the #681 draft. CI was [successfully passed](https://github.com/WalletConnect/blockchain-api/actions/runs/9620128967/job/26537701653?pr=681#step:6:12).

feat(ci): bumping shared `ci_workflows` version to 0.2.11

---

.dockerignore
.env.example
.gitmodules
Cargo.lock
Cargo.toml
deny.toml
src/env/mod.rs
src/lib.rs
src/state.rs
src/storage/error.rs
src/storage/irn/mod.rs
src/storage/mod.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR implements the IRN client abstraction into the blockchain-api. The following changes are made:
**CI/CD and build**
* `WalletConnect/irn-node` repository was added as a git submodule.
* `irn_api` and `network` packages were added as dependencies from the `irn-node`.
* `BSL-1.0` license was added to the allowed list.
**The following IRN client configuration parameters were added:**
* `RPC_PROXY_IRN_NODE` environment variable and `irn_node` terraform variable for the IRN node address to connect to in IP:Socket format.
* `RPC_PROXY_IRN_KEY` environment variable and `irn_key` terraform variable for the IRN client private key.
* `RPC_PROXY_IRN_NAMESPACE` environment variable and `irn_namespace` terraform variable for the IRN storage namespace.
* `RPC_PROXY_IRN_NAMESPACE_SECRET` …

feat(sessions): irn client scaffolding

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR bumps the shared `ci_workflows` version to the recent [0.2.12](https://github.com/WalletConnect/ci_workflows/releases/tag/0.2.12) to fix the [release build error](https://github.com/WalletConnect/blockchain-api/actions/runs/9669212504/job/26675209849#step:2:270).
Not tested.

fix(ci): bumping the shared `ci_workflows` version to 0.2.12

---

Cargo.lock
Cargo.toml
integration/sessions.test.ts
src/error.rs
src/handlers/mod.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/list.rs
src/handlers/sessions/mod.rs
src/lib.rs

This PR implements the following handlers according to the [sessions API spec](https://github.com/WalletConnect/walletconnect-specs/pull/242/files):
* Session/permission creating at `POST /v1/sessions/:address`,
* Generating the ECDSA keypair, storing the verification key (for further owner verification), and returning the signing key.
* Generating the unique PCI (permission identifier) by using the UUIDv4 format.
* Storing the permission object in the IRN.
* List of session/permissions PCI (permission identifiers) for the certain address at `GET /v1/sessions/:address`,
* Get session/permission by the address and PCI (permission identifier) at `GET /v1/sessions/:address/:pci`.
* [Integration tests](https://github.com/WalletConnect/blockchain-api/pull/686/files#diff-d2b6bfa16ff410867b43a05e …

feat(sessions): implementing session create, list and get handlers

---

Dockerfile

This PR moves files copying *before* the `chef cook` to copy the `irn` submodule files and fix [the build error](https://github.com/WalletConnect/blockchain-api/actions/runs/9669791859/job/26677120309#step:8:372).
Tested by running `docker build --no-cache -t test_app .` locally and successfully built the image with the change from this PR.

fix(Dockerfile): moving copy before the `chef cook`

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR bumped the shared CI workflow `ci_workflows` to the [0.2.13](https://github.com/WalletConnect/ci_workflows/releases/tag/0.2.13) version to fix [the deploying error](https://github.com/WalletConnect/blockchain-api/actions/runs/9671311388/job/26682129478#step:2:73) due to the missed secrets inheritance.
Tested by manual deploying using the branch instead of the version.

fix(ci): bumping `ci_workflows` to `0.2.13` version

---

src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/list.rs
src/metrics.rs

This PR adds an IRN client operations latency metrics tracker as an `irn_latency_tracker`.
As a context to the metric, the operation type is also added as a tag.
Not tested.

feat(metrics): adding IRN client latency metrics

---

src/providers/one_inch.rs

This PR changing to use non-checksummed addresses only in requests to 1Inch endpoints. 
Some of the endpoints like the token price don't support checksummed addresses and return `token not found` error response when passing the checksummed token contract address. 
To avoid such collisions we should convert all checksummed addresses to non-checksummed by converting them to lowercase when requesting 1Inch.
* Successfully passed the current integration tests.

fix(one_inch): using non-checksumed address only

---

.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-providers.yml
.github/workflows/sub-validate.yml

This PR adds `PRIVATE_SUBMODULE_ACCESS_TOKEN` to the checkout step to fix the running of the [provider-specific tests and Rust integration tests](https://github.com/WalletConnect/blockchain-api/actions/runs/9751517891/job/26913564466).
Also, bumping the  GitHub action `actions/checkout` version to `4`.
Not tested, just action-lint passed.

fix(ci): adding submodule secret for providers and integration tests

---

.github/workflows/sub-validate.yml

This PR making the change to the `TS Integration tests` CI step to ignore Sessions-related integration tests in `sessions.test.ts` for the `staging` environment. 
At the moment we have collisions that need to be resolved to peer to the IRN from the `staging` environment (we have tests enabled in `prod`). 
This change will unblock our CI/CD until resolution. The Sessions API is alpha/mvp testing only at the moment.
* Running `PROJECT_ID=xxx RPC_URL=https://rpc.walletconnect.com yarn integration --testPathIgnorePatterns='sessions.test.ts'` successfully skipped the sessions test suite.

fix(ci): temporary ignoring integration sessions tests for staging

---

Cargo.lock
Cargo.toml
integration/sessions.test.ts
package.json
src/error.rs
src/handlers/sessions/context.rs
src/handlers/sessions/create.rs
src/handlers/sessions/mod.rs
src/lib.rs
src/utils/crypto.rs
yarn.lock

This PR implements the permission context update endpoint `/v1/sessions/{address}/context` according to the [API SPEC draft](https://github.com/WalletConnect/walletconnect-specs/pull/242/files#diff-585df27a5f0c0b1216c7296d8bbe3c30877bc469bcbdad4c905c6803c1e441dcR93).
For the request authentication, the signature (signed message) is used. 
As a signing message, the `context` canonized JSON object from the request is used and signed by the signing key (created during the session creation request). Then the signature is verified at the server by the verification key which is stored during the [session creation](https://github.com/WalletConnect/walletconnect-specs/pull/242/files#diff-585df27a5f0c0b1216c7296d8bbe3c30877bc469bcbdad4c905c6803c1e441dcR53) in the permission session object.
The …

feat(sessions): implement permissions context update endpoint

---

Cargo.lock
Cargo.toml
src/handlers/identity.rs

This PR updates the Redis identity resolver results cache key format into `${key}-v1` to add the keys version and update the current storage schema (the current records can't be migrated due to the format of the messagePack).
* Tested locally by passing the integration tests.

fix(identity): adding version to the cache key format

---

integration/sessions.test.ts
src/handlers/sessions/context.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/list.rs
src/handlers/sessions/mod.rs
src/handlers/sessions/revoke.rs
src/lib.rs
src/metrics.rs
src/storage/irn/mod.rs

This PR implements the permission context revoking endpoint `/v1/sessions/{address}/revoke` according to the [API SPEC draft](https://github.com/WalletConnect/walletconnect-specs/pull/242).
For the request authentication, the signature (signed message) is used. 
As a signing message, the permission controller unique identifier is used (PCI) and signed by the signing key (created during the session creation request). 
Then the signature is verified at the server by the verification key which is stored during the [session creation](https://github.com/WalletConnect/walletconnect-specs/pull/242/files#diff-585df27a5f0c0b1216c7296d8bbe3c30877bc469bcbdad4c905c6803c1e441dcR53) in the permission session object.
* [A new integration test was …

feat(sessions): implementing permission revoking

---

src/handlers/sessions/create.rs
src/handlers/sessions/mod.rs

This PR adds a signing key to the storage along with the verifying key during the permission creation request. The generated signing key will be used for making the signature during the co-signing request.
* Not tested.

feat(sessions): storing a signing key during permission creation

---

README.md

This PR adds a description to the `README.md` file on how to run manual integration tests.
* Command in the description was tested locally.

feat(readme): adding manual integration tests run description

---

Cargo.lock
Cargo.toml
integration/sessions.test.ts
src/handlers/sessions/context.rs
src/handlers/sessions/create.rs
src/handlers/sessions/mod.rs
src/handlers/sessions/revoke.rs
src/utils/crypto.rs

This PR makes the following changes based on [this Slack thread](https://walletconnect.slack.com/archives/C0760BM9AHH/p1721110736693969):
* Removing the signature authorization from the context update and revoking endpoints.
* Using the secp256k1 instead of P256 (secp256r1) during the PCI creation and returns the public, not a private key.
* Using keccak256 for message hashing.
* Removing unused dependencies.
* Updated integration and unit tests.

fix(sessions): changing to use secp256k1, removing signatures from context update and revoking

---

src/lib.rs
src/utils/crypto.rs

This PR changes numbers to strings in the `userOperation` to support bigint at the JS side which should be the string.
* Manually tested by calling the pre-created cosign request.

fix(sessions): change numbers to strings in the `userOperation`

---

terraform/monitoring/panels/irn/latency.libsonnet
terraform/monitoring/panels/names/registered.libsonnet

This PR consists the following fixes: 
* Fixes IRN latency alert by changing no alerting when there is no data instead of alert.
* Fixes Names counter query.
Tested by putting the query and config to the Grafana UI.

fix(grafana): fixing no data irn latency alert and registered names counter

---

src/error.rs
src/handlers/sessions/cosign.rs
src/utils/crypto.rs

This PR modifying co-signing steps according to the recent changes ([Slack thread](https://walletconnect.slack.com/archives/C0760BM9AHH/p1721314692128899)).
The updated flow:
* Get the `userOperation` hash by calling `getUserOpHash(userOps)` on the v07 entrypoint.
* Sign the resulting hash value with the PCI private key.
* ABI-encode two signatures (co-signer and `userOperation` signature) into one.
* Set the above-encoded signature to the updated `userOperation` and call `getSignature` method on the userOpBuilder contract.
* Set the returned signature from userOpBuilder call to `userOperation`.
* Send the resulting `userOperation` to the bundler.
Tested manually step by step.
Contracts call unit tests that can be [run manually](https://github.com/WalletConnect/blockchain-api/pull/713#disc …

feat(sessions): implementing additional cosigner steps

---

src/database/helpers.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/handlers/sessions/cosign.rs
src/utils/crypto.rs

This PR removes the getting receipt step from the co-signer request handler. Getting the receipt should be moved to a separate endpoint. 
The reason is the receipt can be obtained later than the request for user operation was made, so we need to poll for the receipt after the co-sign request from a dedicated endpoint for that operation.
The co-sign endpoint will now return the user operation tx hash instead of the receipt.
* Manually tested.

fix(sessions): removing getting of the receipt from the co-sign request

---

src/analytics/identity_lookup_info.rs
src/handlers/identity.rs

This PR adds the optional `clientId` request parameter to the analytics.
Some of `/identity` requests now have a `clientId` parameter which is the client ID of the end-user’s dapp instance of the Sign Client. 
We need to use this for analytics. The new optional `client_id` field was added at the end of the analytics structure.
* Not tested.

feat(analytics): adding `clientId` optional identity request field to the analytics

---

integration/names.test.ts
src/error.rs
src/handlers/profile/lookup.rs
src/handlers/profile/mod.rs
src/handlers/profile/register.rs
src/handlers/profile/reverse.rs

This PR adds `apiVersion=2` query parameter to the forward `/v1/profile/account/{name}` and reverse `/v1/profile/reverse/{address}` name lookup endpoints to fix the condition where `HTTP 404` was returned when no name registered was found. 
Adding the query parameter should fix the response to the new versions, but preserve the backward compatibility support for the current ones.
Resolves #700
[API Spec update.](https://github.com/WalletConnect/walletconnect-specs/pull/247)
* [New integration tests were added and current ones were updated.](https://github.com/WalletConnect/blockchain-api/pull/719/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1)

feat(names): adding `apiVersion=2` query parameter to fix not-found responses

---

terraform/monitoring/panels/names/registered.libsonnet

The ENS metric shows one metric per dimension instead of an aggregate.

fix(o11y): ENS Metric tracked without aggregate

---

src/utils/crypto.rs

This PR makes the following changes to the co-sign workflow:
* Get the signature function name changed to the `formatSignature`.
* Signature concatenation ABI encoding format was changed to [[byte, byte]].
* This change was tested manually using sync and async workflow.

feat(cosigner): changing get signature function name and signatures concat

---

src/handlers/identity.rs

This PR adds properly handling exceptional cases where the ENS name avatar pointing to the ERC721 NFT which is absent or the contract address is wrong.
Currently, when ENS name have an `avatar record` that points to the wrong contract address we are returning `HTTP 500` error (because the contract call result is `0x`), which is wrong since the name was resolved and we should just return `avatar: null` in such cases instead of the server error.
* The following identity request triggers `HTTP 500`: `/v1/identity/0x08D3a14b98D1E15B197bb86545d119E1C769Df45`.
* This Pr changes fixing the response to became `{"name":"bubnov.eth", "avatar":null }`.

fix(identity): properly handling of the avatar NFT absence

---

integration/jestconfig.integration.json

This PR increases the integration tests timeout to 10 seconds. Since we have a bunch of tests and the number of new tests increased sometimes the default 5 seconds is not enough and we get the `thrown: "Exceeded timeout of 5000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test"` error.
This PR increases the `testTimeout` parameter in the jest config file.
* Tested by running `yarn test` on the long-running test.

fix(tests): increasing integration tests timeout

---

src/handlers/identity.rs

This PR adds proper handling of the JSON-RPC code `-32000` when trying to get the identity avatar.
Currently, if the avatar contains an NFT contract address and the execution was reverted there is a JSON-RPC error `-32000` that results in the `HTTP 500` error response. In such cases, we should return just an empty avatar instead of the server error.
* Identity request `/v1/identity/0x2531Dac8784CC16b0F1047C5FB97A4a629c44566` results in the `HTTP 500` error, because the name `shibun.eth` contains the `eip155:1/erc721:0x373075bab7d668ed2473d8233ebdebcf49eb758e/1` avatar contract record that returns execution reverted.
* Calling the same request in the current PR results to the `{"name":"shibun.eth","avatar":null,"resolvedAt":"2024-08-08T13:15:45.889236Z"}` response, which is the same as at …

fix(identity): properly handling of the JSON-RPC code `-32000`

---

src/utils/crypto.rs

This PR adds an additional mapping (human-readable name -> chain ID) name to the zkSync Era chain. 
Zerion uses `zksync-era` chain name for the chain ID 324. 
Also, this PR fixes a bug where zkSync Era is mapped to the Chain ID `328` instead of `324`.

fix(zerion): adding zksync era mapping name

---

SUPPORTED_CHAINS.md
src/env/mantle.rs
tests/functional/http/mantle.rs

This PR changes Mantle (MNT) testnet chain ID and RPC endpoint to the actual.
Currently, Mantle deprecated the `https://rpc.testnet.mantle.xyz` endpoint and `5001` Chain ID for the testnet in favor of `5003` and `https://rpc.sepolia.mantle.xyz` RPC endpoint.
* Updated provider integration test.

fix(providers): changing Mantle Testnet endpoint and chain ID to the actual

---

src/env/publicnode.rs
tests/functional/http/publicnode.rs

This PR adds Polygon Amoy (eip155:80002) support to the Publicnode provider to distribute the load since we have just one provider for that chain ID at the moment.
* Updated provider integration test.

feat(providers): adding Polygon Amoy testnet support to the Publicnode provider

---

src/analytics/identity_lookup_info.rs
src/handlers/identity.rs
src/handlers/profile/mod.rs

This PR adds `same_sender` boolean field to the identity analytics to reflect was the name lookup request was made for the same address (`true`) as the owner or not (`false`). The field is optional to support backward compatibility.
Web3Modal related PR: [#2649](https://github.com/WalletConnect/web3modal/pull/2649)
* Not tested.

feat(analytics): adding `same_sender` field to the identity lookup analytics

---

src/error.rs
src/handlers/proxy.rs

This adds a 10s timeout to call providers. Metrics show that sometimes endpoints can sometimes take a long time to respond and this could lead to 504 errors.
Not tested

fix: add proxy timeout

---

src/providers/mod.rs

Sets the minimum weight to 1 when selecting a provider so that there's always a little bit of traffic to a provider.
Resolves #737 
Not tested

fix: min 1 weight

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/proxy/rpc_retries.libsonnet

This PR adds a Grafana `Provider call retries` panel to track analytics `rpc_call_retries` histogram. 
The panel will track how many provider retries we have for each of the chain id on RPC calls.
* The query was manually added to the Grafana dashboard and it shows the right chart.

feat(grafana): adding provider RPC call retries panel

---

terraform/ecs/variables.tf
terraform/redis/variables.tf

This PR increases the Redis node type to `cache.t4g.small` and Redis pool maximum connections to `512`.
This change fixes the Redis bottleneck issue on connection spikes when using the rate-limiting middleware which depends on the Redis connections.
* Tested by applying manually.

fix(redis): increasing the node type and max connections

---

integration/proxy.test.ts
src/handlers/proxy.rs

This PR adds proper handling of the `HTTP 400 Bad Request` RPC provider response.
Currently, if the user sends a bad JSON-RPC request, the provider responds with `HTTP 400` which is considered a provider error, and we try the next provider in the retry list. Every provider fails and that results in `HTTP 503 Provider x unavailable` error instead of stopping retrying and passing the `HTTP 400 Bad request` error to the user with the error details.
Resolves #740
* A new integration test was created.

fix(rpc): passing through a `bad request` error from the RPC provider

---

src/handlers/sessions/cosign.rs
src/utils/crypto.rs

This PR makes the following changes to the CoSigner flow:
* Removing Bundler interaction;
* Removing getSignature Call;
* Add a call to the `sendUserOp` endpoint and return the result.
The full context for these changes: [Slack thread](https://walletconnect.slack.com/archives/C06G97QSSUX/p1724334904209319).
* Manually tested with the research team by running the local version.

feat(cosigner): removing sending user operation to the bundler, adding call to the sendUserOp endpoint

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/app/handlers_latency.libsonnet
terraform/monitoring/panels/app/handlers_rate.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds a Grafana chart for the handler's execution time. The alert was added for more than 3 seconds of execution time for 5 minutes on average. This alert will help to catch possible blocking and long execution times that can affect the user's experience.
The panel for `Handlers requests per second` was also added.
Resolves #750
* Tested by placing the query into Grafana.

feat(grafana): adding handlers execution time, rps chart and alert

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/lb/latency.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds a new Grafana panel to monitor ELB Target (app) response time and alert in case the average response time for 5 minutes is more than 3 seconds.
Resolves #748 
* Manually applied to the Grafana dashboard.

feat(grafana): adding ELB target response time panel and alert

---

src/error.rs
src/handlers/sessions/context.rs
src/handlers/sessions/cosign.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs

This PR adds an additional temporary debugging for the IRN client record creation and tracking the error when the created record was not found during the `hget` lookup. 
We are having rare errors when the client successfully creates a record in IRN and then has a record not found issue. To track this error and make sure it's not a client error these temporary debug lines were added and will be removed when the issue is fixed.
* No tested.

feat(debug): temporary adding debug messages for PCI creation and error when not found in IRN

---

src/env/publicnode.rs

This PR temporarily disabled the Publicnode provider for the Base chain because of the `missing trie node ...` errors on requests.
Not tested.

fix(providers): temporary disabling Publicnode for the Base

---

src/providers/mod.rs
src/providers/pimlico.rs

This PR extending supported bundler operations list with the following new operations:
* `eth_estimateUserOperationGas`
* `pm_sponsorUserOperation`
New operations are required for the shared library to use the bundler ops API endpoint.
The API SPEC updating PR: https://github.com/WalletConnect/walletconnect-specs/pull/254
* Not tested.

feat(bundlerops): extending supported bundler operations list

---

src/env/publicnode.rs

This PR enabling back the Base chain for the Publicnode provider since the issue was resolved.
* Current integration tet.

fix(providers): enabling Base for Publicnode provider

---

integration/fungible_price.test.ts
src/error.rs
src/handlers/balance.rs
src/handlers/fungible_price.rs
src/handlers/mod.rs
src/providers/mod.rs
src/providers/solscan.rs
src/storage/redis/mod.rs
src/utils/crypto.rs

This PR adds Solana support for the [fungibles pricing endpoint](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-api#price) by using the [SolScan Token price](https://pro-api.solscan.io/pro-api-docs/v2.0/reference/v2-token-price) API endpoint for the SOL native token and [SolScan Token Metadata](https://pro-api.solscan.io/pro-api-docs/v2.0/reference/v2-token-meta) endpoint for the SPL tokens.
* A new [integration test was implemented](https://github.com/WalletConnect/blockchain-api/pull/765/files#diff-4493ff1a59d5bf63fc4e0b226e9908932f9c2ef71dafddf6ecf99f00c5739487).

feat(providers): adding Solana fungible price support

---

src/providers/solscan.rs

This PR fixes the token amount in the transaction history for Solana.
Currently, the token amount is returned without applying decimals, this PR fixes the issue by applying `amount / 10f64.powf(token_decimals)`.
* Current integration tests and manual testing.

fix(solscan): fixing tokens amount in the transactions history

---

src/error.rs

This PR makes the following change for the Zerion and SolScan provider's error handling: in case the request to the provider was not a successful `!response.status().is_success()` we will respond `HTTP 503` Provider temporary unavailable, instead of responding with HTTP 500 Server error. This makes better sense in case if the provider responds with the 500 or 503s.
* Not tested.

feat(providers): respond HTTP 503 instead of 500 on provider non-success request

---

Cargo.lock

This PR updates `Cargo.lock` file to the up-to-date state.
The update was produced by invoking the following steps:
* Rust update: `rustup update` command.
* Invoke build and run: `cargo run` command.
* Not tested.

fix: update `Cargo.lock` to the up-to-date state

---

src/handlers/balance.rs
src/handlers/convert/allowance.rs
src/handlers/convert/approve.rs
src/handlers/convert/gas_price.rs
src/handlers/convert/quotes.rs
src/handlers/convert/tokens.rs
src/handlers/convert/transaction.rs
src/handlers/fungible_price.rs
src/handlers/history.rs
src/handlers/onramp/options.rs
src/handlers/onramp/quotes.rs
src/handlers/portfolio.rs
src/handlers/proxy.rs
src/metrics.rs
src/providers/coinbase.rs
src/providers/mod.rs
src/providers/one_inch.rs
src/providers/solscan.rs
src/providers/zerion.rs

This PR adds proper monitoring metrics for all external requests to non-proxy providers.
At the moment we are just monitoring latency and status codes for the Proxy providers and only monitoring handlers execution latency for non-proxy providers and don't monitor response codes from non-proxy providers at all. Some handlers use different non-proxy providers and execute not only one request to the provider. We need to implement proper monitoring for the non-proxy provider's endpoints.
This PR adds the following changes:
* Refactoring: aggregating repeated code parts into private methods,
* Adding request latency and response status codes by invoking the [add_latency_and_status_code](https://github.com/WalletConnect/blockchain-api/pull/773/files#diff-9f90e93b5696724fd8e4407c9db0bfd381d5468bc …

feat(monitoring): adding proper metrics for all external requests to non-proxy providers

---

integration/fungible_price.test.ts
src/handlers/proxy.rs
src/metrics.rs
src/providers/zerion.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/non_rpc/endpoints_latency.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds the following new Grafana panel rows:
* Non-RPC Providers Status codes,
* Non-RPC Providers endpoints latency.
Monitoring charts on these panels were added for the following providers:
* Zerion,
* OneInch,
* Coinbase,
* SolScan.
Also, the `endpoint` attribute was added to the `http_external_latency_tracker` metrics.
* Manually tested.

feat(grafana): adding non-rpc providers Grafana panels for status codes and endpoints latency

---

src/env/mod.rs
src/lib.rs
src/utils/rate_limit.rs

This PR implements the IP's whitelisting for the rate-limiting middleware.
* New optional config environment variable `RPC_PROXY_RATE_LIMITING_IP_WHITE_LIST` was added for the comma-separated list of whitelisted IPs;
* Check for the IP in the whitelist added to the rate-limiting middleware.
* No tests for the whitelisting yet.

feat(rate_limiting): implementing IP whitelisting

---

src/handlers/sessions/cosign.rs
src/utils/crypto.rs

This PR adds the response to the CoSign request depending on the `version` query parameter.
The default response is used when no `version` or `version = 0` is provided for backward compatibility. The updated response `version != 0` should be a signature without calling the wallet service.
We are still in the testing/mvp stage so the `version` will reflect the further stages if needed until the stable.
* Only manual testing.

feat(CoSign): response depends on the `version` query parameter

---

terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR is a follow-up for #776, it fixes (adding) the Terraform variable for the IP whitelisting which is missed in the original #776.
* Not tested.

fix(rate_limiting): adding terraform IP whitelisting variable

---

src/env/mod.rs
src/metrics.rs
src/providers/mod.rs
src/providers/solscan.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf

This PR implements the local caching for tokens metadata and price.
We are requesting tokens metadata and price on each balance and transaction history request. Since the token's metadata doesn't change often we can cache it in Redis and reuse the cached data instead of querying the provider every time. 
Also, the token's price can be cached to reuse in balance, history, and fungible price endpoints without querying the provider on every request.
This will significantly decrease the latency of our balance, history, and fungible price endpoints and decrease provider request count.
The different TTL for the metadata and pricing cache was applied, since metadata changes are rare and token price changes more often:
* Metadata cache TTL: 1 hour,
* Token price cache TTL: 5 minutes.
The cache …

feat(SolScan): implementing tokens metadata and price caching

---

integration/jestconfig.integration.json

This PR increases the Jest tests timeout from 10 seconds to 30 seconds. 
For the Solana fulfilled address we are using the address with multiple subaccounts which sometimes leads to the uncached response from the provider can take ~12-15 seconds causes tests to fail due to timeout.
* Not tested.

fix(tests): increasing jest tests timeout

---

Cargo.lock
Cargo.toml
tests/functional/http/mod.rs
tests/functional/websocket/mod.rs

This PR reverts back the [WalletConnectRust](https://github.com/WalletConnect/WalletConnectRust) version to `0.31` and alloy primitives version to `0.7`. The reason is that the [verify_eip6492](https://github.com/WalletConnect/blockchain-api/blob/d96449513fb0dd37a3624062119eee6d78791551/src/utils/crypto.rs#L298) function became flaky: verification fails on the good signature.
Also, a few dependencies package versions were updated to up-to-date.
1. Start the server locally.
2. Run the integration tests for name registration few times (3-5) by calling `PROJECT_ID=xxx RPC_URL=http://localhost:3000 yarn integration -t 'Account profile names'`.
3. Currently, tests will be flaky, but when downgrading the version (using this PR) tests became stable back.

fix: revert back `WalletConnectRust` and `alloy_primitives` versions

---

.github/workflows/sub-validate.yml
integration/balance.test.ts
integration/names.test.ts

This PR changed the Solana fulfilled address for tests from `ThDD...8VV7` to `5PUr...Uhsr`. The reason for this change is that `ThDD...8VV7` is an account that is actively used for thousands of transactions, which causes a delay in response. 
We don't need such a huge account for tests, that's why we are changing to the `5PUr...Uhsr` that has a dozen transactions of activity.
Also, this PR removes the `MAIN_ZONE` variable and hardcoding the main zone in the test.
* Tested by running the integration tests locally.

fix(tests): changing Solana fulfilled address and removing name zone variable

---

src/env/mod.rs
src/metrics.rs
src/providers/mod.rs
src/providers/solscan.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/non_rpc/cache_latency.libsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/res_ecs.tf

This PR is the follow-up for #782 and adds the Grafana panel for the non-RPC providers' cache latency for monitoring purposes.
* The new panel was manually applied to the Grafana.

feat(monitoring): add non-rpc providers cache latency Grafana panel

---

src/error.rs
src/providers/coinbase.rs

This PR added a proper HTTP 503 (Temporarily unavailable) response instead of HTTP 500 (Server error) when the OneInch and Coinbase endpoints response was not successful.
* Not tested.

fix(providers): responding with HTTP 503 on provider non-success response

---

Cargo.lock
Cargo.toml
src/env/pokt.rs

This PR updates the `WalletConnectRust` package version to `0.32` and `alloy_primitives` to `0.8`.
Also, we are temporarily disabling the Pokt provider for the Ethereum mainnet until the flaky RPC response issue resolution.
* Tested by running names registration tests localy.

fix: updating `WalletConnectRust` and `Alloy` dependencies, disabling Pokt for the Eth mainnet

---

src/providers/mod.rs
src/providers/pimlico.rs

This PR adds the `pimlico_getUserOperationGasPrice` as a supported operation to the bundler proxy.
* Tested manually.

feat(providers): adding `pimlico_getUserOperationGasPrice` to the bundler supported operations.

---

src/handlers/sessions/context.rs
src/handlers/sessions/cosign.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/mod.rs
src/lib.rs

This PR makes changes to the CoSigner endpoints according to our [updated SPEC draft](https://www.notion.so/walletconnect/Ready-for-review-Co-signer-API-spec-v2-9a1cdcf24cee4a6b8b126213c0b2eef2).
* Permissions schema was changed to the ERC7715,
* Keys encoding using the Hex instead of the Base64,
* Renaming the context endpoint to the activation,
* Returning the signature instead of the walletService call in the sign endpoint.
* Manually tested at the moment.

feat(cosigner): updating the request schema to the ERC7715

---

src/providers/getblock.rs

This PR adds handling of the `HTTP 402 Payment required` response from the GetBlock provider as rate-limited since this error code returns when we reach the plan limits.
* No tested.

fix(providers): considering `HTTP 402` as rate limited for GetBlock

---

SUPPORTED_CHAINS.md
src/env/berachain.rs
src/env/mod.rs
src/lib.rs
src/providers/berachain.rs
src/providers/mod.rs
tests/functional/http/berachain.rs
tests/functional/http/mod.rs

This PR adds the Berachain [native RPC provider](https://docs.berachain.com/developers/network-configurations#rpc-providers) to the provider's list and adds support for the Berachain bArtio `eip155:80084` chain for RPC calls.
* A new test for the provider was created.

feat(providers): adding Berachain provider and Berachain bArtio support

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR bumps the `ci_workflows` version `0.2.13`->`0.2.14`.
* Not tested.

fix(ci): bumping `ci_workflows` version

---

SUPPORTED_CHAINS.md
src/env/publicnode.rs
tests/functional/http/publicnode.rs

This PR adds [Sei network](https://www.sei.io) support `eip155:1329` for RPC calls by extending the Publicnode provider.
The full [context thread](https://walletconnect.slack.com/archives/C03SCF66K2T/p1727382378579079?thread_ts=1727376353.788319&cid=C03SCF66K2T).
* A new integration test was added.

feat(providers): adding Sei network support

---

SUPPORTED_CHAINS.md
src/env/pokt.rs
src/env/publicnode.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs

This PR adds support for the Scroll Mainnet `eip155: 534352 ` and Scroll Sepolia testnet `eip155: 534351` chains to the RPC.
* New integration tests.

feat(providers): adding `Scroll` chain support

---

integration/sessions.test.ts
src/handlers/sessions/context.rs
src/handlers/sessions/cosign.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/list.rs
src/handlers/sessions/mod.rs
src/handlers/sessions/revoke.rs
src/handlers/wallet/send_prepared_calls.rs

This PR implements changes for the CoSigner PCI list endpoint according to [the recent API proposal](https://github.com/WalletConnect/walletconnect-specs/pull/242/commits/e471921e3fd2aed2a39c19b2b08f4bc685e19884).
* PCI item IRN storage schema was changed to store the projectID, expiration and creation timestamp.
* Returning all PCI data for the address instead of just the PCI uuid,
* Adding `created_at` PCI field,
* Adding project object with the project ID and project name. The project URL and icon URL should be added as a follow-up since the changes to the explorer client are needed to fetch the data.
* Adding `ProjectId` validation for all endpoints.
* [Integration tests were updated](https://github.com/reown-com/blockchain-api/pull/805/files#diff-d2b6b …

feat(CoSigner): returning all PCIs at the list endpoint

---

integration/sessions.test.ts
src/handlers/sessions/get.rs
src/handlers/sessions/mod.rs
src/lib.rs

This PR changed the session permission get context endpoint to be `GET /v1/sessions/:address/getcontext?projectId={projectId}&pci={pci}` instead of `GET /v1/sessions/:address/:pci` to reflect that we are getting only the PCI context and shorting the URL.
* The current integration test was updated.

feat(CoSigner): changing the get session context endpoint

---

integration/proxy.test.ts

This PR removes the bad JSON-RPC request integration test since we are just proxying requests to the provider and shouldn't check this. Also, some providers are allowing the `id` to be optional making this test flaky.
* Not tested.

fix(tests): removing JSON-RPC bad request test

---

integration/sessions.test.ts
src/error.rs
src/handlers/sessions/cosign.rs
src/handlers/sessions/create.rs
src/handlers/sessions/list.rs
src/handlers/sessions/mod.rs
src/handlers/sessions/revoke.rs
src/utils/mod.rs
src/utils/permissions.rs
src/utils/sessions.rs

This PR introduces the draft testing implementation for the following permissions check during the CoSign process:
* `contract-call` permission:
Extracting the contract call address from the bundler's execution operation and comparing it to the permissions allowed for the address call.
* `native-token-transfer` permission:
Extracted values from the bundler's execution batch are summarized and checked with the allowance.
Currently missing:
* Check for the period, start, and expiration,
* Tracking the already spent amount.
* Manual testing only, integration tests will be added before merging.

feat(CoSigner): implementing `contract-call` and `native-token-transfer` permissions check

---

src/env/quicknode.rs
tests/functional/http/quicknode.rs

This PR adds Unichain Sepolia and Berachain chains to the Quicknode provider.
Integration test for Quicknode updated.

feat(providers): adding Unichain and Berachain to the Quicknode provider

---

.github/workflows/event_pr.yml
Cargo.lock
Cargo.toml
docker-compose.mock-bundler.yaml
src/analytics/message_info.rs
src/env/mod.rs
src/env/server.rs
src/handlers/bundler.rs
src/handlers/identity.rs
src/handlers/wallet/call_id.rs
src/handlers/wallet/get_calls_status.rs
src/handlers/wallet/handler.rs
src/handlers/wallet/mod.rs
src/handlers/wallet/prepare_calls.rs
src/handlers/wallet/send_prepared_calls.rs
src/lib.rs
src/providers/mock_alto.rs
src/providers/mod.rs
src/test_helpers.rs
src/utils/crypto.rs
tests/context/mod.rs
tests/context/server.rs

Adds support for `wallet_getCallsStatus` to Wallet Service according to [the spec](https://www.notion.so/walletconnect/API-specs-for-Wallet-Services-0c4b70a397e2435691f9bb1f20bc652d?pvs=4#5c4f865af7b24308920b13bae94da5ef).
This adds a basic happy-path test case to test this method. It mocks the call ID input with a "normal" Safe execution which we already have code for. However, going forward we will have code that will be able to test the other 2 `wallet_*` endpoints and we will be able to update this test case to be more E2E.
Depends on https://github.com/reown-com/yttrium/pull/37
New test case

feat: wallet_getCallsStatus

---

src/error.rs
src/handlers/sessions/cosign.rs
src/utils/permissions.rs
src/utils/sessions.rs

This PR adds the following changes:
* Decoding the calldata ABI with packed (one transaction) and unpacked formats to support the `Safe` format,
* Using the yttrium smart_accounts->safe implementation for decoding,
* Removing `ethers-rs` in favor of `alloy`,
* Adding CoSigner check if the permission was revoked,
* Adding CoSigner check if the permission was expired.
New unit tests.

fix(CoSigner): decoding the ABI calldata from Safe format, PCI expiration and revocation check.

---

src/handlers/wallet/handler.rs

This PR updates the `is_internal` cases to return HTTP 500.
Not tested.

fix(WalletService): fixing HTTP 400 error when internal expected

---

integration/bundler.test.ts
tests/functional/http/mod.rs
tests/functional/websocket/mod.rs

This PR fixing the bug in CI tests introduced since [#804 where changing the server address type to URL](https://github.com/reown-com/blockchain-api/pull/804/files#diff-f010c176f1bdfbc3c2b1c7c0341c664e6e435e73ca13e93066730c1ab957c057R7).
When `format!` the URL path with the Url type the host address results in the ending slash `/` that adds a double slash `//` as a result and [404 error in CI tests](https://github.com/reown-com/blockchain-api/actions/runs/11410902782/job/31767622146#step:5:1391).
This PR removes the starting slash in `format!`.
Tested by running CI tests locally.

fix(ci): fixing integration tests context url path

---

Cargo.lock
Cargo.toml
src/handlers/wallet/prepare_calls.rs
src/handlers/wallet/send_prepared_calls.rs
src/main.rs
terraform/ecs/cluster.tf

Debug errors e.g.:
- `rpc_proxy::handlers::wallet::handler: Internal server error handling wallet RPC request (prepareCalls): PrepareCalls(InternalError(Sponsorship(missing field `jsonrpc` at line 1 column 218`
- `rpc_proxy::handlers::wallet::handler: Internal server error handling wallet RPC request (sendPreparedCalls): SendPreparedCalls(InternalError(SendUserOperation(error decoding response body`
This modifies the logging configuration so that you can enable debug logs per-module e.g. how Terraform Cloud is now configured: `log_level = "info,yttrium=trace"`
Depends on https://github.com/reown-com/yttrium/pull/46
Not tested

fix: debug wallet service with new logs

---

integration/sessions.test.ts
src/handlers/sessions/cosign.rs
src/utils/permissions.rs

This PR changes the native token transfer permission name to the `native-token-recurring-allowance` to fit the current SDK name.
The context: [Slack thread](https://reown-inc.slack.com/archives/C06G97QSSUX/p1729604631318369?thread_ts=1728909115.959829&cid=C06G97QSSUX).
* The change passes the updated integration test.

feat(CoSigner): changing the native token transfer permission to the `native-token-recurring-allowance`

---

integration/chain_orchestrator.test.ts
src/error.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/handlers/chain_agnostic/status.rs
src/lib.rs
src/providers/bungee.rs
src/providers/mod.rs
src/storage/irn/mod.rs

This PR adds the approval transaction to the transactions list if required.
We are checking the allowance for the bridging transaction first and requesting the approval transaction data if the allowance is less than the minimum required. 
The approval transaction is added as the first transaction to the list.
Also, the `status` for the orchestration ID is added by checking if the amount in the wallet is greater than expected.
* Integration tests were updated, and local tests were successfully passed.

feat(ca_orchestration): adding the approval transaction if needed and checking the status

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/check.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/handlers/chain_agnostic/status.rs
src/utils/crypto.rs

This PR fixes the following issues in the Chain Orchestrator:
* Calculating the exact topup amount (current destination chain balance - expected transfer amount) instead of just using the transfer amount, in this case, the remaining balance will be used for the transfer;
* Fixing the status check endpoint by adding the right (destination) contract and chain ID instead of the bridging data;
* Checking the ERC20 token destination balance amount to skip bridging if it's sufficient.
* Integration tests for the chain orchestration were updated to catch this case.

fix(CA): fixing the topup amount and status check

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/check.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR adds an amount top-up multiplier for the bridging to cover the bridging fees. This change will fix the bug when the check status is pending even after the bridging was done.
The default multiplier is 5%, which is the same as [in the sample](https://github.com/reown-com/web-examples/blob/9e94417090cfdd7e4bdc44ee181865530379fc23/advanced/wallets/react-wallet-v2/src/utils/MultibridgeUtil.ts#L11).
The integration test was updated to check the bridging amount * multiplier.

feat(CA): adding topup amount multiplier

---

Cargo.lock
src/handlers/wallet/get_calls_status.rs

This PR fixes the `wallet_getCallsStatus` call by removing the CAIP-2 chain ID when passing it to the bundler provider.
Also, the [yttrium version is bumping to the](https://github.com/reown-com/yttrium/pull/54) fix of the `entryPoint` deserialization error.
* Tested manually by passing the `wallet_getCallsStatus` request to the local instance.

fix(walletService): fixing get_call_status bundler call

---

src/env/pokt.rs
tests/functional/http/pokt.rs

This PR temporarily removes Pokt provide from the Base Sepolia `eip155:84532` chain support, because of the flaky responses from the JSON-RPC contract calls responding with the `0x` response with no any error.
* Flaky responses were received using the `eth_call` method.
* Updated integration tests.

fix(providers): Removing Pokt provider from Base Sepolia chain support

---

Cargo.lock
deny.toml
src/handlers/wallet/get_calls_status.rs

This PR updates Cargo dependencies. The reason for this update is to fetch the latest yttrium library. 
Fixes to the `get_calls_status` handler were added since the response for the bundler's receipt was changed in the yttrium.
The [Unicode-3](https://github.com/unicode-org/icu/blob/main/LICENSE) license was added to thee allowed list.
* Tested by current integration tests.

feat: updating Cargo dependencies and yttrium library

---

SUPPORTED_CHAINS.md
src/env/publicnode.rs
tests/functional/http/mod.rs
tests/functional/http/publicnode.rs

This PR adds the Bitcoin RPC support for mainnet `bip122:000000000019d6689c085ae165831e93` and testnet `bip122:000000000933ea01ad0ee984209779ba` to the Publicnode provider.
* Integration tests for the Publicnode provider were updated.

feat(providers): adding Publicnode Bitcoin RPC support

---

terraform/variables.tf

This PR increases `autoscaling_max_capacity` to `10` for the ECS cluster to handle the load under the flood.
Not tested.

fix(ecs): increasing the cluster max capacity

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/route.rs

This PR fixes the following issues:
* Proper chain ID passing when calculating the nonce to fix the `nonce is too high` error,
* Decreasing the default gas estimate from x4 to x2,
* Fixing chain ID passing to the transactions list.
* Updated integration test

fix(CA): fixing the nonce calculation, decreasing gas estimate, transactions chain ID fix

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/route.rs

This PR increases the gas estimation multiplier from the default to `6`.
* The integration test was updated.

fix(CA): increasing the default gas estimation multiplier

---

src/env/quicknode.rs
tests/functional/http/quicknode.rs

This PR adds the following chains to the Quicknode provider:
* Polygon zkEvm `eip155:1101`,
* Bitcoin Mainnet,
* Bitcoin Testnet.

feat(providers): adding Polygon zkEvm and Bitcoin to the Quicknode provider

---

Cargo.lock
Cargo.toml

This PR updates Cargo dependencies, pins the `yttrium` repo to the commit, and bumps `alloy` to the `0.6.1` version.
* Tested by running `cargo clippy`: app successfully built.

fix(dependencies): pin to ytrrium repo to commit and bumping alloy

---

terraform/monitoring/panels/status/provider.libsonnet

This PR adds an alert in case the provider responds with HTTP 40[1-3] errors. 
We should track these responses since they reflect paid providers' payment or plan issues and we should take action on this. 
Only 40[1-3] were included, because of:
* HTTP 400 Bad Request - reflecting the client request error,
* HTTP 404 Not Found - some providers (like 1Inch) use this response as a client error request (requested token not found, etc).
Not tested.

feat(o11y): adding HTTP 40[1-3] alerts for providers

---

src/utils/crypto.rs

This PR adds [Zero](https://docs.zero.network/) mainnet and testnet to CAIP2 utils.
Unit test.

feat(utils): adding Zero chain to CAIP2 utils

---

src/env/pokt.rs
tests/functional/http/pokt.rs

This PR temporarily disables Pokt for the Polygon chain because of the flaky responses with the `execution reverted` even for the `eth_chainId`.
* Sending the `eth_chainId` request sometimes results in an `execution reverted` response.

fix(providers): temporarily disabling Pokt for the Polygon

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/handlers/chain_agnostic/status.rs
src/providers/bungee.rs

This PR adds the following changes: 
* Adds the briding timeout for `30` minutes because bridging can take ~20 minutes until funds are refunded; 
* Adds check if the initial address token amount was changed since the routes request and if it was changed, but less than expected after bridging;
* Pinning to the `Across` bridge when requesting quotes from the Bungee.
* Current test coverage.

feat(CA): adding timeout, insufficient bridged amount check, pinning to the exact bridge

---

src/env/pokt.rs
src/env/publicnode.rs
src/env/quicknode.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs
tests/functional/http/quicknode.rs

This PR removes Grove/Pokt provider (because of flaky RPC responses) and adds Publicnode and Quicknode providers instead for the Optimism chain `eip155:10`.

fix(providers): swapping providers for the Optimism chain

---

integration/chain_orchestrator.test.ts
src/error.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR adds a fine-tuning to the bridging amount estimation by using the following approach:
* Get the bridging quote from the original transfer amount top-up;
* Calculate the bridging fee from the quote final amount response;
* Update the transfer amount top-up on the previous quote fee;
* Multiply the result by 2% slippage;
* Get the new quote with the final top-up amount.
The integration test was updated.

feat(CA): fine tuning the bridging amount estimation

---

integration/fungible_price.test.ts
src/handlers/fungible_price.rs
src/providers/one_inch.rs
src/providers/solscan.rs

According to [the SPEC](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-api#success-response-body-6), this PR adds the missing `address` field to the fungibles price response.

fix(fungibles): adding `address` field to the fungibles price response schema

---

src/handlers/proxy.rs
src/metrics.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/proxy/chains_availability.libsonnet

This PR adds tracking of chain availability by ChainId. The following changes were implemented:
* A new metric `no_providers_for_chain_counter` to track `no providers available` responses for chain IDs;
* Proxy endpoint updated to track the new `no_providers_for_chain_counter` metric;
* A new Grafana `Chains availability` panel was added.
Not tested.

feat(o11y): adding tracking of chain availability by ChainId

---

terraform/monitoring/panels/status/provider.libsonnet

This PR removes the 40[1-3] errors alert since the alert must be tuned for the per-provider actions because some of the providers return 402, and 403 in case of the rate limiting.
Not tested.

fix(o11y): removing 40x providers alerts

---

src/env/publicnode.rs
tests/functional/http/publicnode.rs

This PR adds Publicnode provider for the Arbitrum `eip155:42161` chain.
Updated integration tests.

feat(providers): adding Publicnode provider for the Arbitrum chain

---

src/env/quicknode.rs
tests/functional/http/quicknode.rs

This PR swaps the Unichain endpoint to the Arbitrum for the Quicknode.
Test updated.

fix(providers): swaping Unichain to Arbitrum in the Quicknode

---

src/env/arbitrum.rs
src/env/mod.rs
src/lib.rs
src/providers/arbitrum.rs
src/providers/mod.rs
terraform/monitoring/dashboard.jsonnet
tests/functional/http/arbitrum.rs
tests/functional/http/mod.rs

This PR adds Arbitrum native endpoints for Arbitrum One `eip155:42161` and Arbitrum Sepolia `eip155:421614`.
A new integration test was created.

feat(providers): adding Arbitrum native RPC endpoints

---

src/env/publicnode.rs
tests/functional/http/publicnode.rs

This PR adds Ethereum Sepolia `eip155:11155111` to the Publicnode provider.

feat(providers): adding Ethereum Sepolia to the Publicnode

---

src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR fixes the bug with the flaky route responses (empty routes) even when funds and bridging are available by adding the initial asset exclusion from the assets searching for the bridging. This causes a `no bridging needed` response when the initial asset is found.
Tested multiple times by requesting and reproducing the flaky issue.

fix(CA): adding an exclusion into the bridging assets search

---

src/env/publicnode.rs
terraform/monitoring/panels/proxy/chains_unavailability.libsonnet
tests/functional/http/publicnode.rs

This PR adds the Solana Mainnet RPC endpoint to the Publicnode RPC provider and tunes the chain unavailability alarm to fire on 10 requests in 10 minutes instead of 100 requests burst.
* Publicnode tests were updated.

feat(providers): adding Solana mainnet to the Publicnode

---

src/env/infura.rs
tests/functional/http/infura.rs

This PR updates the Infura RPC endpoints by adding the following chains:
* BSC Mainnet and Testnet,
* zkSync Mainnet,
* Polygon Amoy,
* Unichain Sepolia.

feat(providers): updating Infura provider endpoints

---

src/env/publicnode.rs
tests/functional/http/publicnode.rs

This PR updates Publicnode provider RPC endpoints to be up-to-date based on the Publicnode announcement that old endpoints will be deprecated soon.
Tested by current integration test for the provider.

feat(providers): updating Publicnode RPC endpoints

---

src/providers/tenderly.rs

This PR makes `decimals` optional according to the Tenderly simulation result schema. This will fix the deserialization error on some requests.

fix(Tenderly): making `decimals` optional in the simulation schema

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/providers/mod.rs
src/providers/tenderly.rs

This PR implements the cached gas estimation for the initial transaction by using the following flow:
* If the transaction is an ERC20 transfer, check the cached gas used value for the ERC20 token contract and ChainID,
* If the cached value is found - update the initial transaction `gas` with the cached value,
* If the cached value was not found - simulate the initial transaction, save the resulting gas used value to the cache by using the token contract and ChainID, and update the initial transaction `gas` with the cached value.
The cache record TTL for the gas estimated value is 24 hours.
The slippage of 3% is added to the gas estimation to cover gas changes.
Manually the integration test was updated.

feat(CA): implementing cached gas estimation for the initial transaction

---

src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/providers/mod.rs
src/providers/tenderly.rs
terraform/monitoring/dashboard.jsonnet

This PR adds response monitoring metrics and Grafana panels for the Tenderly simulation provider.
Not tested.

feat(o11y): adding Tenderly provider monitoring

---

Cargo.lock
Cargo.toml
integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/utils/crypto.rs

This PR reverting transaction schema change from `data` -> `input`.
Integration tests.

fix(revert): reverting transaction schema change

---

Cargo.lock
Cargo.toml
integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/utils/crypto.rs

This PR reverts back to the updated initial transaction types and API changes.

fix: revert back new initial tx types

---

src/handlers/chain_agnostic/mod.rs

This PR increases the cached gas estimation slippage from 2% to 50% to cover possibly daily spikes.
Not tested.

fix(CA): increasing cached gas slippage to 50 percent

---

src/handlers/chain_agnostic/route.rs

This PR adds logging for the `Insufficient balance` chain abstraction route response.
Not tested.

feat(CA): adding logging for the insufficient balance response

---

src/analytics/identity_lookup_info.rs
src/handlers/identity.rs

This PR removes the identity analytics `same_sender` field and adds the `sender` address optional field.
The [full context](https://reown-inc.slack.com/archives/C03RVH94K5K/p1734965652290149?thread_ts=1723117961.333029&cid=C03RVH94K5K) of this change.
Not tested.

feat(analytics): adding identity `sender` field instead of the `same_sender`

---

src/providers/mock_alto.rs
src/providers/mod.rs
src/providers/pimlico.rs

This PR extends the bundler operations endpoint with the new methods:
* `pm_getPaymasterData`,
* `pm_getPaymasterStubData`.
As Pimlico is compliant with ERC7677 they support and recommend the above paymaster-related bundler methods.
Not tested.

feat(bundler): extending supported bundler operations

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml

This PR increases the version of the `WalletConnect/ci_workflows` to the latest to fix the `Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params` error when deploying to the ECS.
It was tested by running the deploy CD workflow from the branch in the [blockchain-api manual action run](https://github.com/reown-com/blockchain-api/actions/runs/12673381980).

fix(CD): bumping `WalletConnect/ci_workflows` shared actions workflow version

---

integration/balance.test.ts
src/env/dune.rs
src/providers/dune.rs

This PR extends the Dune provider to serve Solana balance requests along with the Eip155.
Current Solana balance integration tests were passed.

feat(providers): extending Dune provider to serve Solana balances

---

SUPPORTED_CHAINS.md
src/env/pokt.rs

This PR changed the `Klaytn` chain `eip155:8217` endpoint and name to `Kaia` since the chain name was renamed according to the [official website](https://www.kaia.io/).
* Current integration tests for providers.

fix(providers): changing Klaytn to Kaia endpoint

---

SUPPORTED_CHAINS.md
src/env/mod.rs
src/env/wemix.rs
src/lib.rs
src/providers/mod.rs
src/providers/wemix.rs
terraform/monitoring/dashboard.jsonnet
tests/functional/http/mod.rs
tests/functional/http/wemix.rs

This PR adds Wemix RPC support for the `eip155:1111` Mainnet and `eip155:1112` Testnet support.
* A new integration provider test was created and passed.

feat(providers): adding Wemix RPC support

---

src/providers/bungee.rs

This PR reverts multiple bridge usage in Bungee quotes requests using `includeBridges` parameter because it's not working as expected and leads to unexpected errors.

fix(providers): reverting Bungee multiple bridge usage

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/assets.rs
src/handlers/chain_agnostic/mod.rs

This PR adds USDT asset support for the chain abstraction. The asset is supported by the following chains: Optimism, Base, and Arbitrum. 
To support different assets the default assets list schema was changed to support different balance storage slots for different assets contracts.
A new integration test for the USDT CA was added along with the USDC CA asset.

feat(CA): adding USDT asset to the chain abstraction

---

src/handlers/chain_agnostic/assets.rs

This PR removes the USDT Base contract from the available chain abstraction assets since there is no liquidity in any of the used bridges for it.
The full context in [Slack](https://reown-inc.slack.com/archives/C04DB2EAHE3/p1736944678522549?thread_ts=1736809028.859309&cid=C04DB2EAHE3).
Not tested.

fix(CA): removing USDT asset Base chain support

---

src/providers/bungee.rs

This PR extends the Bungee quotes request bridges list by adding the following:
* Across: most used bridge with the maximum liquidity,
* CCTP: USDC bridge,
* Hop and Stargate: they are second after Across for the liquidity.
* Current CA integration tests.

feat(CA): extending Bungee quotes bridges list

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR updates the CA assets discovery algorithm to prioritize the same asset (same token symbol) when found first and use the rest of the available assets with the highest amount as a lower priority. This will solve the unnecessary swapping if there is the same asset (but on different chains) available for bridging.
* Integration test was updated.

feat(CA): prioritizing the same asset for bridging routes

---

src/handlers/chain_agnostic/route.rs

This PR increases the default gas limit for the CA bridging transaction from x6 to x9.
Not tested.

fix(CA): increasing the default gas limit

---

src/handlers/balance.rs
src/lib.rs
src/providers/dune.rs
src/providers/mod.rs
src/providers/solscan.rs
src/providers/zerion.rs
src/state.rs

This PR implements tokens metadata shared cache between Zerion and Dune providers for the address balances endpoint. The reason to use a shared cache is that when using multiple providers there can be a difference in the token metadata (like different names or icons). 
By using a long-living (1 day) cache with the "first hit, first saved" rule we will use the same metadata for every provider and fix icons flipping on every request and keeping the metadata updated in case some of the providers will be added or removed.
Since the tokens metadata doesn't update often, keeping the 1 day caching seems reasonable.
* Current balance integration tests are passed.

feat(balance): implementing tokens metadata caching between Zerion and Dune providers

---

src/analytics/chain_abstraction_info.rs
src/analytics/mod.rs
src/handlers/chain_agnostic/route.rs

This PR adds analytics for the chain abstraction endpoint.
The following analytics data will be added:
* Timestamp,
* ProjectId,
* IP address geo data (Origin, Region, Country, Continent),
* ChainID: Funding asset chain ID,
* Token contract address: funding token contract address,
* Token symbol: funding token symbol,
* Amount: how much was funded.
* Timestamp,
* ProjectId,
* IP address geo data (Origin, Region, Country, Continent),
* Source chain ID token: Bridging source chain ID,
* Source token contract address: Bridging source token contract address,
* Source token symbol: Bridging source token symbol,
* Destination chain ID token: Bridging destination chain ID,
* Destination token contract address: Bridging destination token contract address,
* Destination token symbol: Bridging …

feat(analytics): adding chain abstraction analytics

---

src/providers/solscan.rs

This PR adds a new SolScan activity type `ACTIVITY_SPL_CLOSE_ACCOUNT`. This will fix the deserialization error when this type occurs in the history response.

fix(SolScan): adding new `close account` activity type

---

src/handlers/chain_agnostic/route.rs
src/providers/mod.rs
src/providers/tenderly.rs

This PR adds the gas estimation for the bridging transaction by using the transaction simulation provider instead of the hardcoded value.
* The gas estimation is cached using the chainId and destination address composite key.
* The slippage for the estimated gas (to cover gas spikes between cache invalidation) is raised from 3% to 10%.
* The caching TTL is decreased from 24 hours to 4 hours for all gas caching (including ERC20 transfers) to cover gas spikes.
* Manually tested and partly covered by the current CA integration tests.

feat(CA): adding cached bridging transaction gas estimation

---

.env.example
.github/workflows/event_pr.yml
Cargo.lock
Cargo.toml
src/env/mod.rs
src/handlers/chain_agnostic/status.rs
src/handlers/sessions/context.rs
src/handlers/sessions/cosign.rs
src/handlers/sessions/create.rs
src/handlers/sessions/get.rs
src/handlers/sessions/list.rs
src/handlers/sessions/mod.rs
src/handlers/sessions/revoke.rs
src/lib.rs
src/storage/error.rs
src/storage/irn/mod.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR updates the IRN client to the latest `wcn_replication`, switching to the mainnet. 
Internal methods were refactored to use `Strings` as keys and `Bytes (Vec<u8>)` as values to be in sync with the client. 
We are using the Serde serialization for the values data. Hence, it makes sense to serialize/deserialize directly to bytes instead of strings. `hfields` method was refactored to be `hscan` that returns a vector of tuples with `(field_name, value)` pairs.
The IRN node environment variable was updated to be `nodes` including a list of WCN nodes in a MultiAddr format.
* Tested on the local IRN cluster using `test_irn_client_set_get_del()` and `test_irn_client_hashmap()` cargo tests which are included in the implementation.

feat(IRN): updating irn client to `wcn_replication` and switching to the mainnet

---

terraform/res_network.tf
terraform/variables.tf

This PR removes IRN VPC peering, since the IRN/WCN nodes are currently in a public network.
Not tested.

feat(IRN): removing Irn VPC peering

---

src/handlers/chain_agnostic/route.rs

This PR increased the estimated gas slippage from 10% to 50% to cover volatility during the cached value TTL.
Not tested.

feat(CA): increasing the estimated gas slippage

---

src/handlers/chain_agnostic/route.rs
src/providers/tenderly.rs

This PR increasing the gas estimation slippage from 50% to 100% (x2) and decreasing the cache TTL from 4 hours to 2 hours to cover the high volatility.
Not tested.

feat(CA): increasing gas estimation slippage and decreasing the cache TTL

---

src/handlers/chain_agnostic/route.rs
src/providers/mod.rs
src/providers/tenderly.rs
src/utils/crypto.rs

This PR adds gas estimation for the approval transaction using the `eth_estimateGas` RPC call and caches the result to reuse it. The gas set/get cache method was extended to use the ERC20 function as an additional optional key parameter since the ERC20 `transfer` gas estimate and ERC20 `approval` functions will have different gas estimations but the same contract address.
* Current integration test: schema check only.

feat(CA): adding cached gas estimation for the approval transaction

---

src/providers/bungee.rs

This PR makes the `bridge_route_errors` response field optional, since it's absent in some responses that cause the deserialization errors.
Not tested.

fix(Bungee): making bridging route errors optional

---

src/providers/mod.rs

This PR disables the cache for the gas estimation until we have a data for the appropriate TTL and slippage tuning.
Not tested.

fix(CA): temporary disabling the cached gas estimation

---

src/error.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/providers/mod.rs
src/providers/tenderly.rs

This PR changes the approach of the gas estimation from using the `eth_estimateGas` for the approval transaction and simulation for the bridging transaction to the bundled simulation for the approval and bridging transaction together.
* The bundled simulation provider trait was added and the implementation for the Tenderly provider;
* Flow of the estimation changed to simulate both transactions in a bundle;
* The proper check for the transaction simulation failure was added;
* The proper error handling for the simulation provider error and the simulation failure added;
* The estimated gas slippage decreased to 20% to cover the volatility between the estimation and the transaction execution.
The current integration test for the gas estimation shouldn't be …

fix(CA): using the bundled simulation for allowance and bridging transactions

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR fixes the following bugs when calculating the bridging fee:
* The 50% slippage was applied to the top-up amount itself instead of the bridging fee only. We are applying the slippage to the bridging fee to cover the volatility between getting the route and the execution.
* The metadata bridging fee was calculated using the top-up amount from the first routes request instead of the final top-up amount (required top-up amount + bridging fee * slippage), which resulted in the higher fee in the UI than was exactly used.

fix(CA): proper bridging fee calculation

---

src/handlers/chain_agnostic/route.rs

This PR temporarily increases the estimated gas slippage to x5 to pass ethe xecution of transactions.
Not tested.

feat(CA): temporarily increasing the gas slippage

---

src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs
src/providers/tenderly.rs

This PR changes to use the `gas` field for the simulation gas estimation.
Not tested.

feat(CA): using the gas estimation from the `gas` field

---

src/env/drpc.rs
tests/functional/http/drpc.rs

This PR removes Solana support from the DRPC provider, because of the `solana is not supported on freetier` message response.

fix(providers): removing Solana from DRPC

---

src/handlers/chain_agnostic/route.rs
src/providers/tenderly.rs

This PR changes the simulated bridging transactions comparison by the data input instead of by the nonce, since this causes an error on the correct transaction because of the different nonce getting parameters are used in our implementation and in the Tenderly. It's much safer to check transactions using input data.
Manually tested.

fix(CA): comparing simulated transaction by the input

---

src/providers/tenderly.rs

This PR changes the Tenderly simulation response `from` field to become optional to fix the deserialization error when the field is not present.
Not tested.

fix(Tenderly): making simulation response `from` field optional

---

src/handlers/chain_agnostic/route.rs
src/metrics.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/chain_abstraction/gas_estimation.libsonnet
terraform/monitoring/panels/chain_abstraction/insufficient_funds.libsonnet
terraform/monitoring/panels/chain_abstraction/no_bridging.libsonnet
terraform/monitoring/panels/chain_abstraction/no_routes.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR implements metrics and Grafana o11y panels for the Chain Abstraction.
The following metrics and panels were created:
* Gas estimation histogram with by chain observability panel,
* `Insufficient funds` responses counter and observability panel,
* `No bridging needed` responses counter with by type observability panel,
* `No routes found` responses counter with by route observability panel.
When we get some data to make alert threshold adjustments, appropriate alerts will be added.
Not tested.

feat(o11y): implementing metrics and Grafana panels for chain abstraction

---

src/handlers/identity.rs

This PR extends identity resolver JSON-RPC error codes considered as a bad response to `-32003` code: `EVM error: InvalidFEOpcode`.
Not tested.

fix(identity): expanding JSON-RPC error codes to `-32003`

---

terraform/monitoring/panels/chain_abstraction/gas_estimation.libsonnet
terraform/monitoring/panels/chain_abstraction/insufficient_funds.libsonnet
terraform/monitoring/panels/chain_abstraction/no_bridging.libsonnet
terraform/monitoring/panels/chain_abstraction/no_routes.libsonnet

This PR fixes labels for Chain Abstraction Grafana panels where `sum by` is used. We should display the group name instead of the hardcoded label for better observability.
Also, `exemplar` is set to `false` because we don't need context-rich samples in the output.
Tested by manually putting these parameters into the Grafana.

fix(o11y): fixing lables for chain abstraction Grafana panels

---

src/env/solscan.rs
src/env/zerion.rs

This PR decreases SolScan and Zerion's priority for the balance requests to route more traffic to other providers.
Not tested.

feat(providers): decrease SolScan and Zerion priority for the balance request

---

src/handlers/balance.rs
src/lib.rs
src/state.rs
terraform/redis/variables.tf

This PR adds the balance response caching for 10 seconds TTL except if the `forceUpdate` parameter was provided where we need to query for the latest balance.
Not tested.

feat(balance): adding the balance response caching

---

src/env/dune.rs
src/providers/mod.rs

This PR fixed a bug in a weighted distribution algorithm where the weight was always `1` due to using of `min()` instead of `max()`.
Also, increasing the weights to `High` for the Dune provider.
Tested manually by echoing the weights and checking providers' distribution.

fix(providers): fixing a bug in weights distribution and tune weights for Dune

---

src/env/zerion.rs

This PR fune-tunning Zerion provider priority to route 10% of the traffic.

feat(providers): fune-tunning Zerion priority

---

src/env/allnodes.rs
src/env/drpc.rs
src/env/infura.rs
src/env/lava.rs
src/env/publicnode.rs
terraform/monitoring/dashboard.jsonnet

This PR changes all `eip155:1` providers priority to `Low` and Allnodes to `Max` to route most RPC traffic to the Allnodes provider.
Not tested.

feat(providers): routing more traffic to Allnodes

---

src/env/infura.rs

This PR temporarily decreased the Infura provider weight to a minimal `1` for the `eip155:1`
Not tested.

feat(providers): decrease Infura weight to minimal

---

src/env/allnodes.rs
src/env/infura.rs

This is a planned reverting `eip155:1` weights after Allnodes testing and disabling the Allnodes RPC endpoint.
Manual testing.

feat(providers): reverting back `eip155:1` weights

---

src/handlers/chain_agnostic/assets.rs

This PR disables the USDT support on the Arbitrum chain due to the failing simulation until the resolution.

fix(CA): temporarily disabling USDT on Arbitrum

---

src/providers/dune.rs
src/providers/one_inch.rs
src/utils/mod.rs

This PR makes a few small fixes:
* Making the token name based on the chain name (native token) capitalized;
* Applying the slippage (+10%) to the 1Inch gas estimation to cover differences for SA.
Current integration tests and manual testing.

fix: capitalizing the metadata token name, multiply gas estimation from 1Inch

---

src/handlers/chain_agnostic/mod.rs

This PR increases the bridging fee slippage `50%` -> `75%`, to cover the bridging fee fluctuation between the route requested and executed to guarantee get the minimal requested amount at the end. That should fix the reported issue when the final amount was half-cent less.
Not tested.

fix(CA): increasing the bridging fee slippage

---

src/env/quicknode.rs

This PR decreases Quicknode endpoints priorities to a minimum where there are other providers available.
Not tested.

feat(providers): tuning the Quicknode provider priority

---

src/env/allnodes.rs
src/env/drpc.rs
src/env/getblock.rs
src/env/infura.rs
src/env/lava.rs
src/env/pokt.rs
src/env/publicnode.rs
src/providers/mod.rs

This PR enables the Allnodes provider for the `eip155:1`, adding a new `Minimal` priority weight with a `1` value and changes all `eip155:1` priorities to `Minimal` except the Allnodes to route most of the traffic to it.
Tested by provider integration test.

feat(providers): enabling Allnodes provider and tuning Ethereum Mainnet RPC traffic

---

integration/balance.test.ts
src/analytics/account_names_info.rs
src/analytics/balance_lookup_info.rs
src/analytics/history_lookup_info.rs
src/analytics/identity_lookup_info.rs
src/analytics/message_info.rs
src/analytics/onramp_history_lookup_info.rs
src/handlers/balance.rs
src/handlers/history.rs
src/handlers/identity.rs
src/handlers/mod.rs
src/handlers/profile/register.rs
src/handlers/proxy.rs
src/handlers/wallet/get_calls_status.rs
src/handlers/wallet/handler.rs

This PR adds the following SDK info query parameters: 
* `sv` - version,
* `st` - type.
These parameters append to the analytics where the analytics are already applied.
Also, adding the `sv` query parameter to the balances endpoint as a workaround for the deprecated `x-sdk-version` header parameter, keeping it backward compatible.
The integration test for the balance endpoint was updated to check the `sv` query parameter and backward compatibility with the `x-sdk-version` header.

feat: adding SDK info `sv` and `st` query parameters for analytics

---

integration/balance.test.ts
integration/chain_orchestrator.test.ts

This PR fixes the CI integration tests by temporarily disabling CA USDT Arbitrum test and fixing the expected Solana filled balance.
Tested by running updated integration tests.

fix(CI): fixing CI tests

---

src/handlers/identity.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/handlers/wallet/get_calls_status.rs

Implements hardcoded providers when `sessionId` query param is provided.
If the provider fails, it will fallback to normal routing logic.
As per the [design doc](https://www.notion.so/walletconnect/1Pager-using-Blockchain-API-for-sending-chain-abstraction-txns-1503a661771e80f38612ea98a1079fc0?pvs=4#1933a661771e806abfa3fda685f6ba42).
Used by https://github.com/reown-com/yttrium/pull/128
Not tested

feat: sessionId and hardcoded provider

---

src/analytics/message_info.rs
src/handlers/balance.rs
src/handlers/chain_agnostic/route.rs
src/handlers/history.rs
src/handlers/identity.rs
src/handlers/mod.rs
src/handlers/profile/register.rs
src/handlers/proxy.rs
src/utils/network.rs

Records the RPC ID and `x-request-id` header contents into the RPC analytics export.
This is useful to later link the `x-request-id` value with the chain abstraction data. Edit: [this PR](https://github.com/reown-com/yttrium/pull/132)
Task list:
Not tested

feat: request & RPC ID analytics

---

terraform/monitoring/panels/usage/provider.libsonnet

This PR adds an alert for providers (RPC/Non-RPC) availability. The availability is calculated as an `HTTP 200` response percentage and other response codes. The alert will fire if the provider availability is less than 90%.
Manually tested.

feat(o11y): adding an alert for providers availability

---

src/handlers/wallet/prepare_calls.rs

#956 upgraded yttrium which changed the fields in `Call` from `data` to `input`. This was an un-intended breaking change, and [ERC-5729 specifies](https://eips.ethereum.org/EIPS/eip-5792#wallet_sendcalls) the use of `data`.
Not tested

fix: revert breaking change that changed data to input

---

src/analytics/balance_lookup_info.rs
src/analytics/history_lookup_info.rs
src/analytics/onramp_history_lookup_info.rs
src/handlers/balance.rs
src/handlers/history.rs

This PR adds tracking of the `request_id` in analytics for the balance and history endpoints.
Not tested.

feat: adding tracking of the `request_id` in analytics for balance and history

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/assets.rs
src/handlers/chain_agnostic/mod.rs

This PR adds different contract storage slots support, adding a correct `balanceOf` storage slot for the USDT Arbitrum contract to fix the simulation error and enable the USDT Arbitrum chain abstraction support.
* A new integration test was created to cover such cases.

fix(CA): adding different storage slots per contracts and enabling USDT on Arbitrum

---

src/handlers/chain_agnostic/route.rs
src/handlers/mod.rs
src/handlers/proxy.rs
src/handlers/self_provider.rs
src/utils/crypto.rs

Creates a "self provider" for alloy and upgrades various usages of this. This new approach avoids doing HTTP requests to the service itself, and instead makes a direct function call to the proxy handler.
Not tested

feat: self provider

---

terraform/variables.tf

This PR makes grafana key terraform variable sensitive.
Not tested.

fix: make Grafana key sensitive

---

Cargo.lock
src/storage/irn/mod.rs
terraform/variables.tf

This updates the WCN client to the following version: https://github.com/WalletConnectFoundation/wcn/pull/169.
The update requires changing the format of WCN node addresses from `Multiaddr` to [`PeerAddr`](https://github.com/WalletConnectFoundation/wcn/blob/main/crates/rpc/src/lib.rs#L246). Following is the list of EU WCN `mainnet` nodes in the `PeerAddr` format:
```
12D3KooWFJpHSpFCoHqFJsHyc9JA7C9XPTVhyXsiTRucU6TikGWe-/ip4/35.157.165.56/udp/3014/quic-v1,12D3KooWFvEEKjqhobbAfdLdj3BFnDkt1dXS2AZBJ1nYPJaSQ7Nj-/ip4/3.79.81.125/udp/3014/quic-v1,12D3KooWPFwn2kqsv8E773d1HFhUvmWEKBdubue6BE4pH2Hq6g63-/ip4/52.28.124.174/udp/3014/quic-v1
```
Not tested.

fix: update WCN client

---

.env.example
.github/workflows/event_pr.yml
integration/onramp.test.ts
src/env/mod.rs
src/handlers/onramp/mod.rs
src/handlers/onramp/multi_quotes.rs
src/handlers/onramp/properties.rs
src/handlers/onramp/providers.rs
src/handlers/onramp/widget.rs
src/lib.rs
src/providers/meld.rs
src/providers/mod.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds the following Meld API endpoints:
* Get a list of available providers;
* Providers properties:
* countries,
* crypto-currencies,
* fiat-currencies,
* payment-methods,
* fiat-purchases-limits.
* Get quotes;
* Generate widget url.
The [API proposal document](https://www.notion.so/walletconnect/OnRamp-Meld-API-integration-1a43a661771e8021a482ebcbbbdb7053).
New integration tests were implemented.

feat(OnRamp): adding Meld API

---

src/handlers/chain_agnostic/mod.rs
src/providers/tenderly.rs

This PR fixes the `NativeCurrency` token standard name in the Tenderly simulation result. The Tenderly response for this type is `NativeCurrency` and not in a screaming case like `ERC20`. Adding an exception for this type to avoid an internal server error. Also, the contract address is optional for this type.

feat(Tenderly): properly handling of the native currency token standard

---

src/handlers/chain_agnostic/route.rs
src/metrics.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/chain_abstraction/response_types_rate.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds tracking of the successful routes found responses compared to unsuccessful responses (no routes found, insufficient funds, no bridging needed).

feat(o11y): adding CA response types rate panel

---

.env.example
.github/workflows/event_pr.yml
src/env/mod.rs
src/providers/meld.rs
src/providers/mod.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds Meld API base URL as a variable to distinguish staging and prod environments for swaps testing. Meld is using different API keys and API endpoints for testing and production environments.

feat(Meld): adding Meld API base url as a variable

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/assets.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR adds USDS (DAI) asset support for the chain abstraction on Optimism and Arbitrum chains.
Since the bridging fee for DAI is very low, increasing the bridging fee slippage from 75% to 200% will avoid bridging transactions failing in case of fee fluctuation.
* A new integration test was created.

feat(CA): adding USDS asset support

---

src/providers/pimlico.rs

This PR fixes a bug when the state overrides injecting when the parameter provides it. 
This is a follow-up to #982, which adds the state overrides only if the parameter length is 2 and only when the state override was not provided. 

fix(Pimlico): injecting state overrides only if not provided

---

src/env/berachain.rs
tests/functional/http/berachain.rs

This PR adds Berachain Mainnet `eip155:80094` RPC support by adding the Berachain native mainnet RPC endpoint.
The integration test for the Berachain provider was updated and passed.

feat(Providers): adding Berachain Mainnet support

---

src/handlers/onramp/widget.rs

This PR fixes the Meld input parameter for the onramp for the source amount from `String` to be `f64` since we are using just a float number here.

fix(Meld): changing the source amount type to be f64

---

src/handlers/chain_agnostic/route.rs

This PR fixes the support for the simulated asset by passing the asset changed instead of the initial transaction asset for the bridging supported assets check.

fix(CA): fixing the support of the changed asset from the simulation

---

Cargo.lock
integration/chain_orchestrator.test.ts
integration/fungible_price.test.ts
src/handlers/chain_agnostic/assets.rs
src/handlers/chain_agnostic/route.rs

This PR removes DAI support in favor of the USDs (Base chain only) support. 
Fixing a bug in the final bridging fee calculations and amount checks between different asset decimals.
Fixing integration tests by removing repeated parts for route checks and using a reusable `checkRoutesResponse` function with a broader schema and values checks for each route test.
* New integration tests for sourcing to USDs and funding from USDs,
* Fixed USDC and USDT integration tests.

fix(CA): adding a proper USDs contract, fixing decimals amount conversion, fixing tests

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/assets.rs
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR adds native token (ETH) abstraction support on Base, Optimism and Arbitrum chains, and adds support of the native token transfer initial transaction.
Integration tests were updated:
* New tests were added: an initial transaction that sends ETH to the Base chain, but funding ETH from the Optimism chain.
* Removing a single status check in favor of checking the bridging status for each test (each route).
* Adding additional checks for the metadata depends on the ERC20 or native token transfer transactions.

feat(CA): adding ETH abstraction support for native token transfer transactions

---

integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/route.rs

This PR fixes the nonce calculation for the initial transaction for cases where there is only a swap on the same chain performing.
Also, handling the negative bridging fee on USDs swaps considering it as a zero fee.
The integration test was updated to check this case.

fix(CA): proper nonce calculation for the same chain swaps

---

Cargo.lock
src/lib.rs
src/providers/mod.rs

This PR adds a check that the Prometheus server is ready in a constructor for better error messaging.

fix(Prometheus): adding a check that the Prometheus server is ready in a constructor

---

SUPPORTED_CHAINS.md
src/env/mod.rs
src/env/monad.rs
src/lib.rs
src/providers/mod.rs
src/providers/monad.rs
terraform/monitoring/dashboard.jsonnet
tests/functional/http/mod.rs
tests/functional/http/monad.rs

This PR adds Monad Testnet `eip155:10143` and Monad native RPC endpoint as a provider.
New integration test for the Monad provider.

feat(providers): adding Monad Testnet RPC support

---

src/utils/crypto.rs

Adding `Caip2ChainId` and `Caip19Asset`
Note: Didn't change the current implementation of `ChainId` and its usage
Introduced a new regex that matches the CAIP2 spec exactly, which is not the case with `CAIP_CHAIN_ID_REGEX`
Automated test coverage

chore: add Caip19Asset and Caip2ChainId

---

integration/balance.test.ts
src/handlers/balance.rs

This PR adds an exclusion for affected SDK versions `1.6.4`, and `1.6.5` to return an empty balance response. The affected SDK version makes an excessive request to the balance endpoint so this will prevent pressure to the balance provider until the version is upgraded by the users.
A new integration test was created.

fix(balances): adding an exclusion for the affected SDK version

---

src/lib.rs
src/providers/mod.rs

This PR makes the Prometheus URL config parameter optional and disables querying Prometheus if it's not provided, instead of the one-time health check during the bootstrap.

fix(prometheus): making prometheus url optional instead of one time health check

---

integration/balance.test.ts
src/handlers/balance.rs

This PR makes the following modification to the SDK version check for an empty balance response:
* For the SDK version, checking the query `sv` parameter first and using `x-sdk-version` header if not present;
* Checking for the `version` and `type-version` formats for the version comparison for backward compatibility.
The integration test for this case was updated.

fix: proper SDK version check for an empty balance response

---

src/handlers/balance.rs
src/handlers/fungible_price.rs
src/handlers/history.rs
src/lib.rs
src/providers/coinbase.rs
src/providers/dune.rs
src/providers/mod.rs
src/providers/one_inch.rs
src/providers/solscan.rs
src/providers/zerion.rs
src/state.rs

This PR refactors the tokens metadata cache to be globally accessible by the `TokenMetadataCacheProvider` to fix the cache inconsistency between different providers and metadata caching implementations between providers.
Current balance and history integration tests should pass.

fix: refactoring the token metadata cache to become a globally accessible

---

src/handlers/wallet/prepare_calls.rs

This PR disables paymaster sponsorship for the userOp in the wallet service. 
The reason for temporarily disabling this until the resolution is the `Internal server error` caused by the `UserOperation reverted during simulation with reason: 0xacfdb444` bundler response.
Tested manually by sending the UserOp.

fix(walletService): disabling paymaster sponsorship

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/balance/requests_distribution_evm.libsonnet
terraform/monitoring/panels/balance/requests_distribution_solana.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds requests distribution by provider charts for account balances.
A new `Accounts balance` row and two charts were added:
* Requests distribution by provider for EVM,
* Requests distribution by provider for Solana.

feat(o11y): adding requests distribution by provider charts for balances

---

src/lib.rs
src/utils/network.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/swaps/availability.libsonnet

This PR adds a new Grafana "Swaps" section with the availability chart for the following swap endpoints:
* Tokens list: `/v1/convert/tokens`,
* Quotes: `/v1/convert/quotes"`,
* Build approve: `/v1/convert/build-approve"`,
* Build swap transaction: `/v1/convert/build-transaction"`,
* Gas price: `/v1/convert/gas-price"`,
* Allowance check: `/v1/convert/allowance"`.
An alert for an availability drop below 95% is also added.
This PR also fixes the `http_call_counter` metrics where all endpoints were hardcoded as "proxy". It's fixed to use the endpoint path instead.

feat(o11y): adding swaps availability chart and monitoring

---

src/handlers/mod.rs
src/lib.rs

This PR moves endpoints latency and status codes metrics to the middleware from the `on_request`, `on_response` layer to fix the deadlock during the `span` `uri` reading for the metrics and make the code more cleaner.
Instead of using `tracing::span`s `URI` for the metrics, we can use the URI in the custom middleware directly and move the metrics logic to its dedicated space.
* Tested locally.

fix: moving latency and status codes metrics to the middleware

---

src/handlers/mod.rs
src/lib.rs

This PR reorders middlewares to execute **all middlewares** except `latency and status codes` middleware **only on existing routes** by using [route_layer](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.route_layer) instead of [layer](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.layer) on all routes (including not existing).
Also, changes to write metrics in the `latency and status codes` middleware async instead of sync which can lead to blocking or latency increase for responses.

feat: middlewares reordering, writing metrics async

---

src/handlers/mod.rs

This PR fixes a metrics overflow bug when using the URI as a latency and status metrics key that results into a metrics overflow due to use of the `/route/:address` routes. The fix is to use the matched path extractor instead.
Tested locally: a middleware using the matched path instead of the URI.

fix(metrics): using the matched path instead of the URI in status and latency metrics

---

Cargo.lock
src/handlers/wallet/prepare_calls.rs
src/utils/erc4337.rs
src/utils/erc7677.rs
src/utils/mod.rs

Fixes the prepare flow to use `eth_estimateUserOperationGas` as well as fully support the new 7677 paymaster spec. The full flow was not tested, but this is better than previously.
[Slack conversation](https://reown-inc.slack.com/archives/C06G97QSSUX/p1744113153391959?thread_ts=1744017462.368659&cid=C06G97QSSUX)
Somewhat manually

fix: prepare use op

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/dispatch_validate.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml
Cargo.lock
Cargo.toml
deny.toml
integration/chain_orchestrator.test.ts
src/handlers/chain_agnostic/mod.rs
src/handlers/chain_agnostic/route.rs

This PR introduces a new `AssetNotSupported` error type from https://github.com/reown-com/yttrium/pull/152 where the possible bridging asset is not supported and we know that the initial transaction will fail due to insufficient funds for a transfer.
A new integration test was implemented.

feat(CA): adding `AssetNotSupported` error type instead of no bridging needed where applicable

---

src/providers/mod.rs
src/providers/tenderly.rs

This PR enables the gas estimation caching for the ERC20 transfer CA initial transaction. The cache TTL decreased to 30 minutes, and the gas estimation slippage is x5 to cover the volatility.
Not tested.

feat(CA): enabling ERC20 transfer gas estimation caching

---

integration/onramp.test.ts

This small change allows passing the CI gate tests since the Meld provider property `defaulAmount` can respond with a number or can be null.

fix(CI): making a provider default amount can be null

---

src/providers/mod.rs

This PR adds a debug info message on the weights update (every 15 seconds) to log the current balance providers' weights for debugging purposes.

fix(debug): adding debug message for the balance provider weights

---

src/handlers/balance.rs
src/providers/mod.rs

This PR temporarily disables the balance provider's failover retrying for debugging purposes and removes the debugging log for the current balance providers' weights.
Current balance integration tests passed.

fix: temporarily disabling the balance provider failover retrying

---

src/handlers/balance.rs
src/metrics.rs
src/providers/dune.rs
src/providers/zerion.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/balance/provider_retries.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR introduces the following changes:
* Fixes balance providers failover logic;
* Adds a new balance lookup retries metrics and a Grafana `Balance provider call retries` panel to track how many retries we have until the balance response is reached;
* Adding backward compatibility support for the optional `ChainId` balance query parameter for the CAIP-2 and non-CAIP-2 chain IDs.
Current integration tests.

fix(balances): fixing the failover retrying, adding support for an optional chainId in a non CAIP-2 format, adding balance retries metrics

---

src/providers/dune.rs

This PR updates the Dune SVM balance endpoint to an updated one. The change is from `beta` -> `beta2`.
The old endpoint will sunset by the end of the month.
Current integration tests should pass.

feat(Dune): updating the SVM balance endpoint

---

src/env/syndica.rs
tests/functional/http/mod.rs
tests/functional/http/syndica.rs

This PR adds Solana Devnet `solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1` RPC endpoint to the Syndica provider.
Integration tests for Syndica were updated.

feat(providers): adding Solana Devnet to the Syndica provider

---

integration/chain_orchestrator.test.ts
src/providers/tenderly.rs

This PR adds ETH balance state override for simulations to not fail on CA initial transaction simulation if the source address doesn't have enough balance, and for the gas sponsorship.
The current integration test for ETH shouldn't fail.

feat(CA): adding a proper simulation balance override for ETH

---

integration/onramp.test.ts

This PR adds a `countryCode` parameter to the Meld onramp quotes request.
OnRamp integration tests were passed.

fix(tests): adding a country code to the Meld quotes

---

.github/workflows/sub-validate.yml
integration/ratelimiting.test.ts

This PR increases max tokens for the rate-limiting integration test to 200 to fix the integration test running on a prod environment. This PR enables sessions and chain abstraction integration tests on a staging environment, which were temporarily disabled due to the WCN limitations, but can now be enabled.
Updated integration tests passed successfully.

fix(CI): fixing rate-limiting test and enabling sessions and chain abstraction tests on staging

---

terraform/monitoring/data_sources.tf
terraform/monitoring/variables.tf
terraform/res_monitoring.tf

This fixes dashboards more permanently by letting the role Grafana assumes to assume the role provisioned by Blockchain API in order to pull metrics.

chore: update monitoring-role TF module to accept more than one trusted role

---

.github/workflows/sub-yttrium-integration.yml

Fixes [failing CD](https://github.com/reown-com/blockchain-api/actions/runs/14855676498/job/41794272476#step:5:2248). This new secret was added to organization secrets but not passed-through here.
Not tested

fix: FAUCET_REQUEST_API_KEY env var

---

src/handlers/wallet/exchanges/mod.rs
src/handlers/wallet/get_exchange_url.rs

Handling floats/decimals in Hex is challenging and implementation in JS and Rust is different. Switched to standard float

chore: change the implementation to use string float instead of hex

---

integration/history.test.ts
src/providers/zerion.rs

This PR adds a filtering by `chainId` by using an optional `chainId` parameter in the transactions history endpoint.
The new integration test was created.

fix(transactions): adding a filtering by `chainId`

---

SUPPORTED_CHAINS.md
src/env/drpc.rs
src/env/pokt.rs
src/env/publicnode.rs
tests/functional/http/drpc.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs

This PR adds Sonic Mainnet `eip155:146 ` and Tesnet `eip155:57054` RPC support according to the new chain's priority.
Providers' integration tests were updated.

feat(chains): adding Sonic Mainnet and Testnet RPC support

---

terraform/postgres/main.tf

This PR updates the AWS RDS engine version `15.5` -> `15.10` because the engine version was updated during the maintenance window, and now it's causing a downgrading error during the terraform apply: `api error InvalidParameterCombination: Cannot upgrade aurora-postgresql from 15.10 to 15.5`
Not tested.

fix(terraform): updating the RDS engine version

---

src/env/pokt.rs
src/env/publicnode.rs
src/handlers/proxy.rs
tests/functional/http/publicnode.rs

This PR changes the default provider for RPC call when session_id was provided to the `Publicnode`.
Not tested.

fix(rpc): using the Publicnode provider when session was provided

---

SUPPORTED_CHAINS.md
src/env/allnodes.rs
src/lib.rs
src/providers/allnodes.rs
src/providers/mod.rs
tests/functional/http/allnodes.rs
tests/functional/http/mod.rs

This PR makes the following changes:
* Adding Allnodes as a WS RPC provider for the Ethereum mainnet instead of the removed Infura,
* Updating the list of supported WS chains,
* Fixing the supported chains CI test.
Tested by running the current integration tests.

fix: ws provider fix

---

src/handlers/wallet/exchanges/binance.rs
src/handlers/wallet/exchanges/coinbase.rs

Add more assets to the list of supported ones for both Binance and Coinbase
Resolves PAY-26,PAY-27,PAY-28

feat: enable more pairs for exchanges

---

src/providers/meld.rs

This PR adds handling of the "bad request" Meld provider response, to handle both `HTTP 400` and `HTTP 422`, since the production endpoint uses `HTTP 422` and the sandbox uses `HTTP 400`.

fix(Meld): proper handling of the bad request response

---

SUPPORTED_CHAINS.md
src/env/mod.rs
src/env/pokt.rs
src/env/publicnode.rs
src/env/sui.rs
src/lib.rs
src/providers/mod.rs
src/providers/sui.rs
tests/functional/http/mod.rs
tests/functional/http/pokt.rs
tests/functional/http/publicnode.rs
tests/functional/http/sui.rs

This PR adds Sui chain RPC support for the mainnet, testnet and devnet using the following RPC providers:
* Publicnode,
* Grove/Pokt,
* Native RPC endpoint.
New provider tests were implemented.

feat(providers): adding Sui chain RPC support

---

src/env/drpc.rs

This PR decreases the BSC `eip155:56` chain priority for the dRPC provider since it's constantly rate-limited for this endpoint, and we need to re-route traffic to avoid increasing latency and retrying.
Not tested.

feat(providers): decreasing BSC chain priority for the dRPC

---

Cargo.lock
Cargo.toml
justfile
src/error.rs
src/handlers/bundler.rs
src/test_helpers.rs
tests/functional/bundler.rs
tests/functional/mod.rs

[Design doc](https://www.notion.so/walletconnect/1Pager-WalletKit-Util-for-WalletService-1d83a661771e8093b014e2594f947c4e?pvs=4#1f53a661771e80cc935bd7156166ea19)
Resolves https://linear.app/reown/issue/CR-701/blockchain-api-bundler-endpoint-accept-bundler-url-as-bundler-name
Not tested

feat: handle custom bundler URL

---

tests/functional/bundler.rs

This PR temporarily disables the `functional::bundler::default_bundler` test due to non-provided env variables in the CI.
Not tested.

fix(test): temporarily disabling bundler functional test

---

src/env/drpc.rs
src/env/pokt.rs
src/env/publicnode.rs

This Pr adjusting chains according to the latest Pokt provider changes:
* Removing Linea endpoint from the Pokt provider because it has a consistent `HTTP 404` response;
* Adding Linea chain to the dRPC and Publicnode;
* Decreasing the Ethereum Sepolia endpoint to the minimum in Pokt due to an excessive amount of `HTTP 500` responses.
Tested manually and by the current integration tests.

fix(providers): adding Linea chain to the dRPC and Publicnode, removing from Pokt

---

Cargo.lock
Cargo.toml
src/handlers/chain_agnostic/route.rs

This PR adds proper handling of the initial transaction simulation error in a Chain Abstraction. This prevents an `HTTP 500` error in cases when the initial transaction is broken or can't be executed, and we know this when making the initial transaction simulation with overrides.
This PR is related to these yttrium changes:
* https://github.com/reown-com/yttrium/pull/175
Manually tested.

fix(CA): properly handling of the initial transaction simulation error

---

SUPPORTED_CHAINS.md
src/env/hiro.rs
src/env/mod.rs
src/lib.rs
src/providers/hiro.rs
src/providers/mod.rs

This PR is a minimal implementation for Stacks RPC support.
Currently, the only `/v2/transactions` support was added by using the `stacks:1` or `stacks:2147483648` chain ID with the `stacks_transactions` JSON-RPC method.
Example Stacks transaction request within the JSON-RPC schema:
```
{"id":"1", "method":"stacks_transactions", "params":["0x...tx_binary_data"], "jsonrpc":"2.0"}
```
Hiro provider was added as a Stacks RPC provider.
Manual testing.

feat(RPC): adding Stacks transactions RPC support

---

src/utils/crypto.rs

This PR updates the CAIP-2 to human-readable names utils with the following chains support:
* Abstract,
* Ape,
* Berachain,
* Degen,
* Gravity Alpha,
* Ink,
* Lens,
* Ploygon zkEvm,
* Soneium,
* Spnic,
* Unichain.
This will fix deserialization errors from the transaction history providers for these chains since a human-readable format is used.
Not tested.

feat(utils): updating CAIP-2 to names utility

---

src/env/callstatic.rs

This PR disables the CallStatic provider due to the [flaky responses](https://reown-inc.slack.com/archives/C03SCF66K2T/p1749050663176459).
Not tested.

fix(providers): disabling CallStatic provider

---

terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds `zan_api_key` terraform variables and passes the API key to the ECS container, which was lost in #1099
Not tested.

fix: adding Zan API key to terraform variables

---

src/providers/therpc.rs

This PR adds a proper handling of the TheRPC provider rate-limited response. The `HTTP 200` and the error code `-32029` are used to reflect the rate limit.

fix(TheRPC): proper handling of the rate limited response

---

src/handlers/wallet/exchanges/coinbase.rs

Fixing the Solana network name "SOL" -> "solana".
Not tested.

fix(exchanges): fixing the Solana network name

---

SUPPORTED_CHAINS.md
src/env/mod.rs
src/env/moonbeam.rs
src/lib.rs
src/providers/mod.rs
src/providers/moonbeam.rs
terraform/monitoring/dashboard.jsonnet
tests/functional/http/mod.rs
tests/functional/http/moonbeam.rs

This PR adds Moonbeam GLMR chain `eip155:1284` support and Moonbeam native RPC endpoint.
New integration test.

feat(providers): adding Moonbeam RPC chain support and Moonbeam RPC provider

---

src/env/drpc.rs
src/env/quicknode.rs

This PR adds a Polygon endpoint to the Quicknode provider with minimal weight and Sei to the dRPC.
Not tested.

feat(rpc): adding Polygon to Quicknode and Sei to the dRPC

---

src/providers/dune.rs
src/providers/meld.rs
src/providers/one_inch.rs
src/providers/zerion.rs

This PR adds proper handling of connection resets to non-RPC providers' endpoints for cases where the remote peer closes the connection. 
In this case, we should respond with the `HTTP 503 Temporarily unavailable` instead of the `HTTP 500`s.
Not tested, but the fix is based on the current HTTP 500 errors.

fix(providers): adding a proper handling of connection resets to non-rpc providers

---

integration/onramp.test.ts
src/handlers/onramp/properties.rs
src/providers/meld.rs

This PR exposes default values by country properties from the Meld API by extending the current properties endpoint and introducing a new `countries-defaults` type.
A new integration test was created.

feat(onRamp): adding country properties defaults

---

SUPPORTED_CHAINS.md
src/env/drpc.rs

This PR adds Rootstock mainnet `eip155:30` support for RPC calls.
Current tests.

feat(RPC): adding Rootstock mainnet support

---

Cargo.lock
Cargo.toml
integration/onramp.test.ts
src/error.rs
src/providers/meld.rs

This PR adds support for obtaining Meld quotes for all possible payment types.
By default, the Meld quotes response has quotes only for the bank card payment type if no payment type was provided.
We want to get all available quotes for all available payment types by getting all available payment types for the country, and then querying in parallel the Meld quotes endpoint for each payment method. 
The aggregated response quotes will be returned.
The quotes endpoint integration test was updated to check that the quotes response has multiple payment types.

feat(Meld): getting quotes for all possible payment types

---

src/providers/meld.rs

This PR adds proper handling of the `NO_VALID_QUOTES` error code when iterating on payment types. That will fix the iteration break in case one of the payment types doesn't have quotes.
Current staging integration test catching this issue.

fix(Meld): adding proper handling of the no valid quotes error code

---

src/providers/allnodes.rs
src/providers/arbitrum.rs
src/providers/aurora.rs
src/providers/base.rs
src/providers/binance.rs
src/providers/blast.rs
src/providers/callstatic.rs
src/providers/drpc.rs
src/providers/mantle.rs
src/providers/mod.rs
src/providers/monad.rs
src/providers/moonbeam.rs
src/providers/morph.rs
src/providers/pokt.rs
src/providers/publicnode.rs
src/providers/quicknode.rs
src/providers/therpc.rs
src/providers/unichain.rs
src/providers/wemix.rs
src/providers/zksync.rs

This PR reverts #1131 and adds only catching the unmarshalling Go error message in Pokt as a temporarily solution.
Not tested.

fix: reverting #1131 and add only unmarshalling error catching

---

src/providers/hiro.rs

Add `stacks_transfer_fees` rpc method that queries `/v2/fee/transfer` endpoint on Stack's API

feat(Hiro): adding transfer fee endpoint support

---

src/providers/allnodes.rs

```
This PR adds detailed logging for JSON-RPC error codes in the -32000 to -32099 range returned by the Allnodes provider.
**Motivation:** During recent incidents, Allnodes returned error codes in this range, leading to HTTP 500 responses and provider failover, triggering alerts. This logging will help identify the specific error messages and data associated with these codes, allowing for a better understanding of their nature and whether they should cause provider unavailability or require specific handling (similar to how other providers handle certain error codes). This addresses the need to debug the "routing algo got messed up" issue mentioned in the Slack thread.
This change introduces new logging. It should be tested by deploying to a staging environment and …
```

feat: Add logging for error codes

---

src/error.rs
src/handlers/ws_proxy.rs
src/lib.rs

This PR allows WSS RPC connections to the standard HTTP RPC `/v1` endpoint. This is required for some SDKs that don't have the ability to change the endpoint for the WSS connection upgrade, like [solana/web3.js](https://solana-foundation.github.io/solana-web3.js/classes/Connection.html#constructor), and are forced to use the same endpoint for the HTTP RPC and WSS RPC connections.
Since the WSS connections are the `GET` method only and HTTP RPC are the `POST` method only, we can route based on this to the different handlers (http, wss).
This PR also adds an appropriate error message if there is a non-WSS connection to the endpoint with the `GET` method.
* Due to the Rust version update, there are formatting and `format!` clippy errors fixes included in this PR as the last two commits. …

feat(RPC): allowing WSS RPC connection to the standard `/v1` RPC endpoint

---

src/lib.rs

This PR adds a trailing slash alias for the WS RPC proxy endpoint, the same that we have for the HTTP RPC proxy, because SDKs are adding a trailing slash.

fix: adding trailing slash for WS RPC proxy alias

---

integration/balance.test.ts
src/handlers/balance.rs

This PR adds a change to the `/v1/account/{address}` balance endpoint to respond with an empty array if no `origin` header was provided.
* Current integration tests were updated,
* A specific test was added to test an empty response without an origin provided.

feat(balance): respond with an empty array if no origin provided

---

terraform/monitoring/panels/swaps/availability.libsonnet

This PR fixes the Swap endpoints availability chart and alert by adding proper `refId`s. 
The same `refId` was reused, which caused calculation issues. Also, there was no summary availability query.
Not tested.

fix(o11y): fixing swap endpoints availability chart

---

src/utils/crypto.rs

This PR fixes the `u64` overflow error `Integer overflow when casting to u64` in the `convert_token_amount_to_value` function when the balance value is more than the `u64` size. Since the balance is U256, we should convert the value properly. Using the`f64` as a result of the function is still reasonable since we don't need a precision more than f64 for the balance endpoint.
The functional test was updated.

fix(balance): fixing u64 overflow in a balance when using the force update

---

src/env/quicknode.rs
src/lib.rs
src/providers/mod.rs
src/providers/quicknode.rs

This PR extends the Quicknode provider to support Solana WebSocket on Mainnet, Devnet, and Testnet.
Manually tested and integration tests should pass.

feat(RPC): extending the Quicknode provider to Solana WSS support

---

src/handlers/wallet/get_exchange_buy_status.rs
src/handlers/wallet/get_exchange_url.rs

This PR changes to pass an error into the internal error message for logging at the production and for better debugging, since it's not logging at the production at the current state.

fix(exchanges): passing an error into the internal server error message

---

.github/workflows/sub-cd.yml
terraform/README.md
terraform/ecs/README.md
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR removes the repository ofac variable usage in favor of using the `ofac_countries` terraform cloud variable.

feat: removing a repository OFAC variable usage in favor of the terraform cloud

---

src/handlers/onramp/multi_quotes.rs

This PR adds a new `excludeProviders` optional query parameter for quotes to exclude providers from the quotes list, since the Meld API doesn't have this type of filtering.
Manual testing.

feat(OnRamp): adding an `excludeProviders` filter for quotes

---

src/handlers/proxy.rs
src/utils/crypto.rs

This PR fixes the check for the presence of server error codes in the JSON-RPC provider response. The current implementation has a bug that uses the `body` variable for the deserialization and a search, which is actually a request body. That results in no data for the metrics, since the pattern never matches.
Additional optimization was added due to the required deserialization for each response. We should make a deserialization only when there is an `"error"` inside the body of the bytes to avoid deserializing every response. 
The `contains_bytes` util function was created to quickly search the pattern through the bytes by using a window scrolling (the fastest way to search).
Unit test was added.

fix(RPC): fixing the check for server error codes

---

src/handlers/proxy.rs

This PR adds a response deserialization check only when the response is successful, because there is no reason to check the schema and the error in case of unsuccessful responses. Adding error message logging for unhandled error codes.

feat(proxy): adding an error check only when the response is success and debugging message

---

terraform/monitoring/panels/proxy/rpc_server_error_codes.libsonnet

This PR fixes the Prometheus query for the JSON-RPC error codes panel and alert. 
The hidden percentage panel became a single one since we should observe the percentage of requests and not the amount. Decreasing the alerting period to one minute to catch possible rate-limited error messages.
Tested manually by updating the query in Grafana.

fix(o11y): fixing the JSON-RPC error codes Prometheus query

---

src/handlers/proxy.rs
src/metrics.rs
src/state.rs
src/utils/json_rpc_cache.rs
src/utils/mod.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/proxy/rpc_methods_cache.libsonnet

This PR adds an RPC responses caching scaffold based on the chainId and methods.
The `eth_chainId` RPC method request now returns the value based on the local calculation instead of the RPC call to providers to save on latency and quota, since we can calculate bytes on our side for this type of request. 
The `chainId` bytes local calculation is cached in a local instance in-memory Moka cache to avoid recalculations on every request.
The new metrics for cached RPC responses per chain and method were added, and a new Grafana panel for the cached responses percentage per method was also implemented.
Tested manually, and current integration tests must pass.

feat(proxy): implementing RPC caching scaffold and adding `chainId` server-side calculation

---

terraform/monitoring/panels/proxy/rpc_methods_cache.libsonnet

This PR fixes the Prometheus query for the RPC cache Grafana panel by adding the `on()` to tell PromQL to join each “method” series against that lone total series (matching on zero labels) and explicitly setting the label to fix the `Value` label instead of the cached method.
Tested manually by putting the updated query into Grafana.

fix(o11y): fixing Prometheus query and label for RPC caching

---

src/env/mod.rs
src/env/server.rs
src/handlers/proxy.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR implements skipping the RPC quota chains list by using the terraform `proxy_skip_quota_chains` variable contains the comma-separated CAIP-2 chains to skip. 
Only projectId validation is applied, and no quota check for chains in the whitelist.
Manual testing.

feat(proxy): implementing skip the quota chains list

---

integration/onramp.test.ts
src/handlers/onramp/properties.rs
src/providers/meld.rs

This PR fixes the `excludeProviders` query parameter for the properties endpoint. The parameter is expected to be a comma-separated value. Since the vector of strings is working when the request type is POST, it's not in GET and throwing an error: `sequence is expected`. This PR changes the type to `String` and handles the extraction of parameters.
The integration test for the `excludeProviders` query parameter was added.

fix(Meld): fixing the `excludeProviders` properties query parameter

---

src/providers/mod.rs

This PR extends the known list of JSON-RPC messages based on the metrics and current alerts.

feat(proxy): extending the known list of json-rpc error messages

---

Cargo.lock
Cargo.toml
deny.toml
src/handlers/sessions/list.rs
src/handlers/wallet/exchanges/binance.rs
src/project/mod.rs
src/project/storage/mod.rs
src/state.rs

This PR updates the Cerberus client to add a new project with limits instead of the project with quota schema to use the new  `https://api.reown.com` endpoint to check if the project quota is reached due to moving to plans schema instead of the quotas schema. Instead of the quota check, we must check the `is_above_rpc_limit` boolean now.
The full [context in Slack](https://reown-inc.slack.com/archives/C0890LE26AH/p1752835884365379).
Unit test was updated, tested manually, and must pass the current integration tests.

feat: using the updated Cerberus which uses a new limits to check the quota

---

src/json_rpc/mod.rs
src/json_rpc/tests.rs
src/utils/json_rpc_cache.rs

This PR fixes the bug in the `json_rpc` request and response by preserving the type of the `id`. 
We are converting any `id` types (number, string) to the string instead of preserving the exact `id` type and responding with the same type.
According to the [JSON-RPC specification](https://www.jsonrpc.org/specification) `id` can contain any of the string, number, or null types. Force conversion to the string type leads to client deserialization errors where it uses a number in the request and expects the number in the response. 
This PR changes to use a `serde_json::Value`, same as in the [jsonrpc crate](https://docs.rs/jsonrpc/0.18.0/src/jsonrpc/lib.rs.html#75) to preserve the type for the response.
Unit tests were updated and tested manually.

fix: preserving JSON-RPC `id` type

---

src/error.rs

This PR changes the error message when requests per second limit exceeded from `Rate limited` to `Requests per second limit exceeded` for clarity between the quota and RPS limit error messages.
Not tested.

feat: better rate-limited error message

---

terraform/monitoring/panels/proxy/chains_unavailability.libsonnet

This PR changes the chart and alert name for no providers found for the chain from `ChainID Unavailability` to `No provider for chain` to make it clear.
Not tested.

fix(o11y): fixing the no provider for chain alert name.

---

terraform/ecs/cluster.tf

This PR removes setting the network backlog size from the Terraform due to the Fargate container can't start.

fix: removing setting of the network syn in the terraform

---

terraform/monitoring/panels/lb/error_5xx.libsonnet

This PR changes the alerting threshold for 502s from 0 to 15 for 15 minutes, to avoid being always fired and alerting when we don't have a single occasion.
Not tested.

fix(o11y): tune the 502 alert

---

Cargo.lock
Cargo.toml
src/lib.rs

This PR reverts the custom listener with the backlog from #1179 due to the degraded performance in production.
Not tested.

fix: reverting of adding axum custom listener with the backlog size

---

terraform/ecs/cluster.tf

This PR fixes the `ulimit` size for the ECS instances to the `1,048,576` max, since the maximum value for the Fargate is `1024 x 1024 = 1,048,576` and we shouldn't exceed this.
Also, setting the soft value the same as hard because we don't need warnings since we are already using a maximum value.
Tested manually on staging.

fix: fixing the ulimit to the Fargate maximum

---

terraform/monitoring/panels/ecs/availability.libsonnet

This PR makes a change to the SLA Availability chart to include `HTTP 503` errors (include all 5xx errors).

fix(o11y): including 503 errors in the availability chart

---

terraform/redis/main.tf
terraform/redis/variables.tf

This PR updates the Elasticache Redis engine version from 6 to 7 on the staging environment and keep the current version for the prod.
Not tested.

feat(redis): updating the Redis cache engine version to 7 on staging environment

---

terraform/ecs/variables.tf

This PR removes the duplication of default values for the autoscaling variables for the ECS Terraform module.
We already have defaults set for these variables [in the main variables](https://github.com/reown-com/blockchain-api/blob/72007829e8062e1ed8ca510b9f540c953206bd28/terraform/variables.tf#L35), and they are [passed down to the ECS module](https://github.com/reown-com/blockchain-api/blob/72007829e8062e1ed8ca510b9f540c953206bd28/terraform/res_ecs.tf#L36). So these defaults create confusion and must be removed.
Not tested, but CI/CD plan should pass.

fix(terraform): removing duplicated ECS defaults for variables

---

src/lib.rs

This PR fixes Axum query parameters to use `:param` schema (for 0.7) instead of the `{param}` from Axum 0.8.
This was initially missed because limited integration tests were run locally and [caught during the CI/CD full test](https://github.com/reown-com/blockchain-api/actions/runs/17067982526/job/48397623603). 
Now it has been tested locally for all tests.

fix: fixing the axum query parameters

---

integration/jestconfig.integration.json
terraform/ecs/cluster.tf

This PR increases the otel collector memory for staging from 64 Mb to 128 Mb, because the otel collector stops by OOM at staging after tests running, making the staging flaky.
The Jest test timeout was increased from 30 seconds to 60 seconds to cover new proxy tests, because testing each chain for the `eth_getBalance` sometimes takes longer and causes a flaky test.
Tested manually by adjusting these values.

fix: increasing otel memory for staging and jest test timeout

---

src/analytics/message_info.rs
src/handlers/wallet/handler.rs
src/handlers/wallet/mod.rs
src/handlers/wallet/pos/build_transaction.rs
src/handlers/wallet/pos/check_transaction.rs
src/handlers/wallet/pos/evm.rs
src/handlers/wallet/pos/mod.rs

- Add POS transaction RPC methods `reown_pos_buildTransaction` and `reown_pos_checkTransaction`
- Implement EVM transaction builder with support for native ETH and ERC20 transfers
- Add CAIP validation for asset, sender, and recipient addresses with proper namespace/chain ID matching
- Extensible `TransactionBuilder` trait for multi-chain support 
- Add transaction status checking. Implementation is querying transaction confirmation status via receipt lookup
- Added WalletBuildPosTx and WalletSendPosTx message sources
Manually
Current version of `alloy` that we use doesn't support mocked transport unfortunately. I'll be upgrading `alloy` across the implementation and implementing mocked transport testing in the follow up pr.

feat: pos transaction builder

---

terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds `validate_project_id` boolean variable to the Terraform to pass this parameter from the TFC.
The default value is `true`.
Tested by manually applying this variable in ECS task.

feat: adding validate project ID as TFC variable

---

integration/pos.test.ts
integration/types/pos.ts
src/handlers/wallet/pos/check_transaction.rs
src/handlers/wallet/pos/mod.rs

Changing the `txid` field in the `reown_pos_checkTransaction` to `sendResult` instead.
For EVM chains the result of the send RPC (`eth_sendTransaction`) is going to be the TXID, but for other chains like Tron for example its going to be a signed transaction. In that case we will broadcast it and we will handle all the logic server side. The client should only forward the response from the RPC sent to the wallet and obtained by `reown_pos_buildTransaction`
Changed the test to cover this

chore: change check transaction field

---

.github/workflows/sub-validate.yml

This PR adds a delay before TS tests run to get some time for old ECS instances to decommission. The delay can be organically added by the requirements to wait until Rust integration tests are built.
Not tested.

fix(CD): adding a delay before TS tests by waiting Rust tests to compile

---

terraform/ecs/cluster.tf
terraform/ecs/network.tf

This PR makes the following changes to the ECS tasks deployment process:
* Decreasing the task deregistration default timeout from 5 minutes to 30 seconds. We have a 5-second SIGTERM timeout in the app, so 30 seconds is x5 sufficient for the app to stop, and we shouldn't wait 5 minutes to deregister the task.
* Enabling `deployment_circuit_breaker`. In case the new app can't start or stops during the deployment check it will be rolled back to the previous task.
* Decreases the health check interval to 10 seconds to get the unhealthy status as fast as possible if the problem occurs.
Not tested.

feat(ECS): decreasing deregistration delay and health check timeout, enabling  deployment rollback

---

src/project/error.rs
src/project/metrics/mod.rs
src/project/mod.rs
src/state.rs

This PR implements a circuit breaker for the projects registry API fetcher by adding a cooldown period of 1 second and not checking the project access and quota during the cooldown period (permissive behavior by default).
The circuit opens if there is an internal error response from the registry API.
Tested manually on the local instance.

feat(projects): implementing projects registry fetcher circuit breaker

---

src/error.rs
src/providers/one_inch.rs

This PR fixes the response in case the asset is not supported for the token price request in 1Inch.
The 1inch price endpoint returns `HTTP 404` if the asset is not supported. We are catching this case and responding correctly.

fix(1Inch): respond with the asset is not supported instead of provider is not available

---

integration/pos.test.ts
integration/types/pos.ts
src/handlers/wallet/pos/build_transaction.rs
src/handlers/wallet/pos/check_transaction.rs
src/handlers/wallet/pos/evm.rs
src/handlers/wallet/pos/mod.rs
src/handlers/wallet/pos/solana.rs
src/handlers/wallet/pos/tron.rs
src/utils/crypto.rs

- Added Tron support to the POS flow, including building TRC20 transfers and checking transaction status.
- Extended the JSON-RPC response to return `tron_signTransaction` with strongly typed params and transaction payload (`raw_data_hex`, `txID`, `visible`) and no signature pre-sign.
- Wired Tron into the transaction builder routing so Tron assets resolve via namespace to `TronTransactionBuilder`.
- Implemented a Tron-specific check path and hooked it into `reown_pos_checkTransaction`.
- Refactored the check pipeline to delegate status checks to chain modules and return a unified `CheckTransactionResult` with `check_in` when pending.
- Moved polling intervals into chain modules and set chain defaults (EVM: 1000ms, Solana: 400ms).
- Switched CAIP-10 parsing to the namespace-aware variant …

feat: pos tron

---

tests/functional/database.rs

This PR adds a second delay before inserting and checking for the new name to fix [the flaky tests](https://github.com/reown-com/blockchain-api/actions/runs/17576728308/job/49924047237#step:5:2036).
Not tested.

fix(tests): adding a small delay before check for names count

---

integration/pos.test.ts
src/handlers/wallet/pos/solana.rs

Currently we are expecting the wallets to provide the entire result in the check RPC, which for `solana_signAndSendTransaction` is `{"signature":"signatureValue"}` however we expected just the string, not the full object.
Updating implementation to parse the full object first, and then fallback to string.

fix(pos): update solana check rpc parsing

---

.github/workflows/sub-validate.yml
integration/ratelimiting.test.ts

This PR implements the use of the GitHub variable instead of the hardcoded value of the max tokens for the rate-limiting CI test.

fix(CI): fix rate-limiting test

---

.github/workflows/event_release.yml
Cargo.lock
Cargo.toml

This PR switches to the GitHub release-only workflow instead of the `Cargo.toml` release bump to avoid creating new commits during the release process and using the default `0.0.0` version. 
The build identification will be based only on the commit hash, which is already included in the `/health` endpoint response. 
Not tested.

feat(CI): switching to the GitHub release only and the commit hash only

---

src/handlers/json_rpc/exchanges/binance.rs
src/handlers/json_rpc/exchanges/coinbase.rs
src/handlers/json_rpc/wallet/prepare_calls.rs
src/utils/crypto.rs

This PR fixes Clippy [warnings in the recent Rust version](https://github.com/reown-com/blockchain-api/actions/runs/17914085948/job/50932040123?pr=1242#step:6:2014) by removing dead code parts.
* CI Clippy must pass.

fix: fixing clippy warnings

---

integration/fungible_price.test.ts
src/env/mod.rs
src/handlers/fungible_price.rs
src/providers/dune.rs
src/providers/lifi.rs
src/providers/mod.rs
src/utils/crypto.rs
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_ecs.tf
terraform/variables.tf

This PR adds support for Rootstock tokens price to the fungibles endpoint by using the [Lifi token info API](https://docs.li.fi/api-reference/fetch-information-about-a-token) because the current 1Inch API doesn't support the Rootstock chain, and we are making an exclusion for it.
The new integration test for the Rootstock token price was implemented.

feat: adding Rootstock tokens pricing by using Lifi

---

terraform/res_ecr.tf
terraform/variables.tf

This PR adds an ECR images retention policy for the `blockchain` repository to keep the last 30 images only.
Not tested.

fix(ECR): applying images retention policy

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/panels/rpc/availability.libsonnet
terraform/monitoring/panels/rpc/calls_by_method.libsonnet
terraform/monitoring/panels/rpc/latency_by_method.libsonnet

This PR adds the following o11y charts for the `/v1/json-rpc` endpoint for POS, Exchanges and Wallet service:
* Total % endpoint availability calculated by the successful responses divided by all requests;
* Endpoint latency by method;
* Total calls by method.
Not tested.

feat(o11y): adding exchanges, pos, wallet service o11y charts

---

tests/functional/database.rs

This PR adds ignoring the flaky names count test until the fix. 
We are already cross-checking names in [separate integration tests](https://github.com/reown-com/blockchain-api/blob/master/integration/names.test.ts).
Not tested.

fix(CD): ignoring the flaky test

---

integration/exchanges.test.ts
src/handlers/json_rpc/handler.rs
src/utils/cors.rs
src/utils/mod.rs

This PR fixes the CORS allowed domains check and header when the allowed domain contains a wildcard `*`.
In the current implementation, only an exact match for domains results in adding a CORS `allow-origins` header. This PR fixes the wildcard `https://*.domain.com` for the `https://some.domain.com` origin.
A new integration test has been created.

fix(json-rpc): fixing CORS wildcard

---

integration/proxy.test.ts
src/providers/quicknode.rs

This PR implements wrapping of the [Tron broadcast transaction HTTP API endpoint](https://www.quicknode.com/docs/tron/wallet-broadcasttransaction) into the custom `tron_broadcastTransaction` JSON-RPC method for the SDK compatibility.
HTTP API parameters: `txId, visible, raw_data, raw_data_hex, signature` are passed in the `params` JSON-RPC array in the same order.
A new integration test was created.

feat(rpc): wrapping Tron broadcast transaction API into the custom JSON-RPC method

---

integration/exchanges.test.ts
integration/fungible_price.test.ts

This PR fixes the integration tests flow by removing the FTM token from the test which is not supported anymore and temporarily skipping the CORS wildcard test until the testing ProjectId will be updated with the `https://*.vercel.app` wildcard domain.

fix: fixing integration tests

---

Cargo.toml
src/providers/quicknode.rs

This PR implements TON JSOn-RPC `ton_sendBoc` custom method wrapper to send request to the [TON HTTP API sendBoc](https://www.quicknode.com/docs/ton/sendBoc) endpoint to allow send transactions since TON native JSON-RPC methods are read-only.
The `boc` parameter is mapped to the first json-rpc's `param` value.

feat(TON): adding `ton_sendBoc` wrapped method
