reown-com/blockchain-api

- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/variables.tf
- terraform/vars/dev.tfvars
- terraform/vars/prod.tfvars
- terraform/vars/staging.tfvars
`curl -vvv -X POST -H "Content-Type:application/json" "https://dev.rpc.walletconnect.com/v1/?chainId=eth:1&projectId=someid" -d '{"id":"1660887896683","jsonrpc":"2.0","method":"eth_chainId","params":[]}'`
> feat: exposes app via rpc.walletconnect.com

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_terraform.yaml
Was already approved in other repos
> feat: deploys via ci/cd

- src/main.rs
> feat: configure CORS

- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
> feat: export metrics to prometheus

- .env.example
- terraform/backend.tf
- terraform/ecs/main.tf
- terraform/main.tf
- terraform/monitoring/main.tf
- terraform/monitoring/variables.tf
- terraform/provider.tf
- terraform/variables.tf
Applied locally
See https://g-49ef0030d2.grafana-workspace.eu-central-1.amazonaws.com/d/fczCCQM4k/dev_rpc-proxy?orgId=1&refresh=10s
> feat: add simple dashboard

- .env.example
- .github/workflows/cd.yaml
- .github/workflows/ci_terraform.yaml
- src/env.rs
- src/handlers/proxy.rs
- src/main.rs
- src/providers/infura.rs
- src/providers/mod.rs
- src/providers/pokt.rs
- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/variables.tf
Tested using `WalletConnect/solib`
> feat: add support for Solana/Avax

- Cargo.lock
- Cargo.toml
- src/env.rs
- src/error.rs
- src/handlers/mod.rs
- src/handlers/proxy.rs
- src/main.rs
- src/providers/infura.rs
- src/providers/mod.rs
- src/providers/pokt.rs
As discussed with @arein on slack, this removes a bunch of potential panics in provider code.
> fix: remove potential panics in providers

- terraform/monitoring/main.tf
Plots an availability graph. The idea is to install an alarm on this later.
Not tested
> feat(o11y): plot availability

- .github/workflows/cd.yaml
- .github/workflows/ci_terraform.yaml
- terraform/.tflint.hcl
- terraform/backend.tf
- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/monitoring/main.tf
- terraform/private_zone/main.tf
- terraform/private_zone/outputs.tf
- terraform/private_zone/variables.tf
- terraform/redis/main.tf
- terraform/redis/outputs.tf
- terraform/redis/variables.tf
- terraform/variables.tf
- terraform/vars/dev.tfvars
- terraform/vars/prod.tfvars
- terraform/vars/staging.tfvars
Add a redis instance for caching registry requests.
Resolves #34
> feat: Add global redis for registry cache

- .dockerignore
- .env.example
- .github/pull_request_template.md
- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- README.md
- src/env.rs
- src/error.rs
- src/handlers/mod.rs
- src/handlers/proxy.rs
- src/main.rs
- src/metrics.rs
- src/project/config.rs
- src/project/error.rs
- src/project/metrics/mod.rs
- src/project/mod.rs
- src/project/storage/config.rs
- src/project/storage/mod.rs
- src/state.rs
- src/storage/error.rs
- src/storage/mod.rs
- src/storage/redis/mod.rs
- terraform/monitoring/main.tf
Add project gating with optional caching.
Resolves #33 
WIP
> feat: Add project gating

- .github/workflows/cd.yaml
- README.md
- terraform/ecs/main.tf
Not sure if this fixes a bug bug should be done.
Not tested.
> fix(cd): secrets not modeled

- Cargo.lock
- Cargo.toml
- src/env.rs
- src/main.rs
Configures to log `INFO` and above to `stdout`.
`cargo run`
> feat: log to stdout

- .env.example
- terraform/ecs/main.tf
Step in the right direction. Will make issues for the TODOs in the code.
Not tested
> feat(infra): use data tag to retrieve image

- .github/workflows/ci.yaml
Using the recently released hosted runners feature and a 16core/64gb ram runner config. In my tests test/publish steps now only take 50% of the time.
Not tested
> feat(ci): use hosted runners

- Cargo.lock
- Cargo.toml
- src/main.rs
Change the logs format to JSON for compatibility with CloudTrail.
NA
> fix: set log format to json

- Cargo.lock
- Cargo.toml
- src/analytics/config.rs
- src/analytics/message_info.rs
- src/analytics/mod.rs
- src/handlers/proxy.rs
- terraform/analytics.tf
- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
Add native timestamps to analytics parquet files in a new bucket, keep legacy string timestamps in the current bucket
> feat: add native timestamp to analytics

- terraform/analytics.tf
- terraform/ecs/iam.tf
- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
Remove the legacy analytics bucket.
Deploy manually on `staging`
> fix: remove legacy analytics bucket

- terraform/analytics.tf
- terraform/logging/main.tf
- terraform/logging/outputs.tf
- terraform/logging/variables.tf
- terraform/main.tf
Enable "Server access logging" on the analytics bucket.
Deployed on staging.
> feat: bucket logs for analytics

- terraform/ecs/network.tf
Activate client IP forwarding in the network load balancer.
Deployed on staging.
> fix: activate client ip forwarding in load balancer

- terraform/monitoring/main.tf
> feat(o11y): install error alarms

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- src/analytics/message_info.rs
- src/analytics/mod.rs
- src/handlers/proxy.rs
- terraform/ecs/main.tf
- terraform/variables.tf
- tests/context/mod.rs
- tests/context/server.rs
- tests/functional/connection/binance.rs
- tests/functional/connection/infura.rs
- tests/functional/connection/pokt.rs
Runs integration tests on staging url to check if everything works after deployment
Resolves #81 
The integration tests are will be ran on staging endpoint before deploying to prod
> feat: gate prod with integ tests on staging url

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- Cargo.toml
- tests/context/mod.rs
- tests/context/server.rs
- tests/functional/connection/binance.rs
- tests/functional/connection/infura.rs
- tests/functional/connection/pokt.rs
Reverts WalletConnect/rpc-proxy#86
> Revert "feat: gate prod with integ tests on staging url"

- .github/workflows/ci.yaml
- src/handlers/proxy.rs
- src/lib.rs
- src/project/storage/mod.rs
- src/storage/redis/mod.rs
- tests/context/server.rs
Use the same `clippy` settings as the `rs-relay` repo uses (for consistency).
> feat(ci): update clippy checks

- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/monitoring/main.tf
- terraform/variables.tf
- terraform/vars/prod.tfvars
- terraform/vars/staging.tfvars
Adding memory and CPU scalling to ECS configuration.
Adding CPU and memory metrics to grafana.
Resolves #108
> feat: add scalling to ECS. better metrics

- .github/workflows/validate.yaml
Removing unnecessary variables from validate workflow.
Integ tests ran locally without removed vars, work properly.
> fix: remove unnecessary env vars

- Cargo.lock
- Cargo.toml
- src/env/binance.rs
- src/env/infura.rs
- src/env/pokt.rs
- src/env/zksync.rs
- src/handlers/proxy.rs
- src/lib.rs
- src/providers/binance.rs
- src/providers/infura.rs
- src/providers/mod.rs
- src/providers/pokt.rs
- src/providers/zksync.rs
- tests/functional/http/binance.rs
- tests/functional/http/infura.rs
- tests/functional/http/pokt.rs
- tests/functional/http/zksync.rs
- tests/functional/websocket/infura.rs
- tests/utils/mod.rs
Implementing failover, allowing for multiple providers to be defined;
Also aggregated tests together - seems like there was some race condition where github actions was trying to spawn so many async contexts. 
Resolves #29 
Ran tests, also ran locally with debugging, and called Binance multiple times, about 50% of them went to pokt (so according to setup)
> feat: failover routing

- terraform/main.tf
> feat: scale down elasticache

- src/env/binance.rs
- src/env/infura.rs
- src/env/mod.rs
- src/env/omnia.rs
- src/env/pokt.rs
- src/env/publicnode.rs
- src/env/zksync.rs
- src/error.rs
- src/handlers/proxy.rs
- src/lib.rs
- src/providers/infura.rs
- src/providers/mod.rs
- src/providers/omnia.rs
- src/providers/pokt.rs
- src/providers/publicnode.rs
- src/providers/zksync.rs
- tests/utils/mod.rs
Added two more providers that support our most used chains, so that failover will actually have targets to chose from.
Ran tests several times, also most crucial chains were verified by hand to make sure we get proper responses from all providers. Had to remove one potential provider (1rpc) as they were inconsistent in latency, sometimes reaching 3s.
> feat: add more providers

- src/env/infura.rs
- src/env/pokt.rs
We're getting throttled by Infura -> sent some traffic to Pokt
Not tested
> feat(tune): send some mainnet traffic to Pokt

- src/env/infura.rs
- src/env/publicnode.rs
> feat(tune): prioritize mainnet traffic for Infura

- .env.example
- .github/workflows/cd.yaml
- terraform/monitoring/main.tf
Moving to Grafana 9
Tested locally
> feat(o11y): upgrade to Grafana 9

- src/analytics/message_info.rs
- src/error.rs
- src/handlers/proxy.rs
- src/metrics.rs
- src/providers/binance.rs
- src/providers/omnia.rs
Adding more informative metrics, and exporting origin, if exists to data lake.
Resolves #121 
Ran tests, before deploying to prod will tests with staging and confirm with data team that they are receiving expected data.
> fix: better front facing information and logging

- .github/workflows/ci_terraform.yaml
- terraform/monitoring/main.tf
- terraform/monitoring/variables.tf
Improved grafana board
Deployed to staging
> feat: better grafana board

- terraform/monitoring/main.tf
> feat(o11y): tunes alarms

- .github/workflows/cd.yaml
Add deployment target to `cd` workflow
not tested (CI)
> feat: add deployment target to `cd` workflow

- .github/workflows/ci.yaml
Update the CI to run the functional tests individually per chain.
Not tested (CI)
> feat: run functional tests individually

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/intake.yml
- .github/workflows/issues.yaml
- Update the project ID for `intake`
- Add PR validation on linked issues.
Resolves #148
> feat: add project issues workflow, update project id

- terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
- terraform/monitoring/panels/proxy/errors_provider.libsonnet
Top-level P3 alerts.
Not yet tested
> feat(o11y): HTTP alerts

- src/error.rs
Adding warn! logs for each unhandled error, so we have at least some ability to see what;s happening internally and take action.
Resolves #151 
Not tested, only adds logging.
> fix: log internal errors

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
Fixing the workflow to deploy only to selected environments
Resolves #153 
Workflow changes, no way to test
> fix: properly deploy only to required enviornments

- terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
Fixing the alarm to trigger of the right query
Resolves #159 
Grafana change -no tests.
> fix: non-provider alarms

- terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
- terraform/monitoring/panels/proxy/errors_provider.libsonnet
> fix(o11y): alarms are firing when they shouldnt

- src/providers/mod.rs
- src/providers/pokt.rs
- src/providers/weights.rs
Adjusting the timeframe for quicker weight changes.
Resolves #198 
> fix: adjust timeframe for data lookup

- terraform/monitoring/panels/ecs/availability.libsonnet
- terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
- terraform/monitoring/panels/proxy/errors_provider.libsonnet
Adjusting alarms to be more relevant and not trigger all the time, with no action to be taken.
Resolves #204 
Deployed to staging
> fix: adjust alarms

- Cargo.lock
- Cargo.toml
- src/analytics/mod.rs
- src/debug/alloc.rs
- src/debug/mod.rs
- src/lib.rs
- src/main.rs
- src/providers/mod.rs
- src/providers/weights.rs
Add memory monitoring to identify source of memory leak.
Also fixing issues with old parquet:
https://github.com/WalletConnect/echo-server/pull/143/files
https://github.com/WalletConnect/rpc-proxy/actions/runs/5444086277/jobs/9901443341
Resolves #133 
Tests ran.
> feat: add memory stats monitoring for memory leak debugging

- Cargo.lock
- Cargo.toml
- src/debug/alloc.rs
- src/debug/profiler.rs
- src/handlers/identity.rs
- src/handlers/metrics.rs
- src/handlers/mod.rs
- src/handlers/proxy.rs
- src/handlers/ws_proxy.rs
- src/lib.rs
- src/metrics.rs
- src/project/metrics/mod.rs
- src/project/mod.rs
- src/providers/binance.rs
- src/providers/pokt.rs
- src/state.rs
This integrates the metrics from [`utils-rs`](https://github.com/WalletConnect/utils-rs/pull/1) and adds metrics to HTTP handlers to help identify the memory leak.
Untested.
> feat: handler metrics

- src/lib.rs
This temporarily disables middleware to help narrow down the memory leak source.
Untested.
> fix: temporarily disable middleware

- src/error.rs
- src/handlers/identity.rs
Fixes/correctly attributes two more errors
Resolves #262
Not tested
> chore: improve identity error handling

- .env.example
- .env.terraform.example
- .gitignore
- README.md
- justfile
- src/error.rs
- src/project/mod.rs
Make projectId validation optional. Some ID still needs to be provided, however.
Resolves #295 
Locally
> fix: optional projectId validation

- terraform/monitoring/panels/proxy/http_codes.libsonnet
This should be a count not a time unit
Resolves #313
Manual prod dashboard edit
> fix: HTTP status codes unit

- src/handlers/history.rs
- src/providers/mod.rs
- src/providers/zerion.rs
Finishes up the pagination work.
`curl -vvv "http://localhost:3000/v1/account/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63/history?projectId=10&cursor=WyIyMDIzLTAyLTI1VDE3OjE1OjUzWiIsIjNlNjM5YWIwYTI5YjVjOGRiMjFmMmQzM2RkOTRiYzBmIl0="`
> feat(tx-history): pagination

- .github/workflows/ci.yaml
- .github/workflows/ci_terraform.yaml
- Cargo.lock
- Cargo.toml
- src/error.rs
- src/handlers/history.rs
- src/handlers/proxy.rs
- src/handlers/ws_proxy.rs
- src/metrics.rs
- src/project/mod.rs
- src/project/storage/mod.rs
- src/providers/zerion.rs
- src/state.rs
- terraform/monitoring/dashboard.jsonnet
- terraform/monitoring/panels/panels.libsonnet
- terraform/monitoring/panels/proxy/quota_limited_projects.libsonnet
Resolves #320 
- bumps `cerberus` to 0.10.0
- adds Grafana dashboard for the amount of quota limited requests
- fixes ProjectData cache deserialization errors resulting in 500
- fixes missing secret in `ci_terraform.yaml`
Existing integration tests (staging)
> feat: quotas

- Cargo.lock
- Cargo.toml
- src/analytics/config.rs
- src/analytics/identity_lookup_info.rs
- src/analytics/message_info.rs
- src/analytics/mod.rs
- src/env/mod.rs
- src/env/server.rs
- src/lib.rs
- src/profiler/mod.rs
- terraform/ecs/main.tf
Integrates the geoblocking feature from utils-rs. Currently blocked countries: KP, IR, CU, SY.
> feat: geo-blocking, replace `gorgon` with `utils-rs`

- terraform/ecs/main.tf
Update the list of OFAC blocked countries to include Russia and Ukraine
Not tested
> chore: add Russia and Ukraine to list of OFAC blocked countries

- terraform/ecs/main.tf
Remove Ukraine from list of OFAC blocked countries
Not tested
> chore: remove Ukraine from list of OFAC blocked countries

- README.md
Adds more detail and link to documentation. Also making it clear this isn't the WalletConnect relay.
Resolves #345 
N/A
> chore: add more detail to README

- .github/workflows/cd.yaml
- .github/workflows/ci_terraform.yaml
- Cargo.lock
- Cargo.toml
- terraform/ecs/main.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/variables.tf
- Update the `utils` dependency to `0.7.0`
- Fetch CI vars from GHA
> chore: update `utils` version

- src/providers/zerion.rs
This PR exposes `is_spam` flag for the NFT in the transaction history.
The new `flags` object with the boolean flag `is_spam` is added to the `nft_info` object of the transaction history response.
The **updated** history example response is:
```
{
"data": [
{
"id": "50f3e12794875b59884ddff06629077e",
"metadata": {
"operationType": "mint",
"hash": "0x37f6313c5b0fe3efa4d61c340d6513c9884291a65e5b2f09ccc8e2769b1fe52e",
"minedAt": "2023-09-19T23:50:30Z",
"sentFrom": "0xa65f49f207fd07a5c3551d6eea8ab5c4ff977e1d",
"sentTo": "0xa76ffb17004bab6af34cdf3e0dec6b6215614128",
"status": "confirmed",
"nonce": 20667
},
"transfers": [
{
"fungible_info": null,
"nft_info": {
"name": "5 ETH Voucher by Base",
"content": {
"preview": {
"url": "https://lh3.googleusercontent.com/zrM3ThTK4fGQo4KjYSrCZtiGAExqEgFcYjBN …
```
> feat: exposing `is_spam` flag for the nft

- .github/codeowners
- src/analytics/config.rs
- src/analytics/mod.rs
- src/env/mod.rs
- src/env/server.rs
- src/lib.rs
- src/providers/mod.rs
- terraform/ecs/analytics.tf
- terraform/ecs/main.tf
- terraform/ecs/terraform.tf
- terraform/ecs/variables.tf
- terraform/main.tf
- terraform/vars/dev.tfvars
- terraform/vars/prod.tfvars
- terraform/vars/staging.tfvars
- tests/context/server.rs
Cleanup configuration and put all values into structures instead of ad-hoc reads from the environment.
> fix: cleanup and refactor configuration

- src/handlers/identity.rs
For the hackweek we are exploring a ENS resolver. Before I'm integrating an actual resolver I will ship this for us to demo. Planning on removing after hackweek.
Not tested
> feat(identity): hardcoding address for ENS demo

- src/handlers/identity.rs
Previously released this faulty in #366 . This has meanwhile been covered by tests. So now releasing the fixed version.
Covered by integration tests
> feat(ens): hardcoding address for ENS demo

- integration/integration.test.ts
- src/handlers/mod.rs
- src/handlers/portfolio.rs
- src/lib.rs
New portfolio API to support @dianeben's new designs
Resolves #379 
`curl -vvv "localhost:3000/v1/account/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63/portfolio?projectId=<hidden>"`
Also added integ tests.
> feat: scaffolds portfolio API

- integration/integration.test.ts
- src/error.rs
- src/handlers/mod.rs
- src/handlers/portfolio.rs
- src/providers/mod.rs
- src/providers/zerion.rs
Exposes data to the portfolio API.
Resolves #380 
Tested locally and covered by integ tests
> feat: expose portfolio

- src/handlers/identity.rs
Skipping the cache lookup for demo addresses
No test.
> fix: skipping caching for demo addresses

- integration/integration.test.ts
- src/env/mod.rs
- src/error.rs
- src/handlers/history.rs
- src/handlers/mod.rs
- src/providers/coinbase.rs
- src/providers/mod.rs
- src/providers/zerion.rs
- terraform/ecs/cluster.tf
- terraform/ecs/variables.tf
- terraform/res_ecs.tf
- terraform/variables.tf
Integrates Coinbase's transaction history behind feature flag. Allows us to show a prettier UI if a user onramped via Coinbase. Ultimately this should work for all on-/off-ramp providers and deserves some thought. But no harm in adding this behind a feature flag IMO.
Integration tests.
> feat(onramp): Coinbase transaction status

- src/providers/coinbase.rs
This PR removes the unnecessary logging of the Coinbase transactions response.
CI workflow tests.
> fix(logging): removing Coinbase response logging

- src/state.rs
The quota limit being hit was only logged and metered, but the error itself wasn't being returned. :clown_face: 
Unit
> fix: not returning quota limit error

- .github/workflows/sub-cd.yml
Fix the name of the dynamic Terraform variables
Not tested (CI)
> fix: correct name of dynamic terraform variables

- .github/workflows/dispatch_validate.yml
- .github/workflows/sub-providers.yml
- .github/workflows/sub-validate.yml
This PR introduces fixes to the GitHub Actions according to the [actionlint](https://github.com/rhysd/actionlint) founded issues.
Tested only by the linter.
> fix(ci): fixes to actions workflow files according to the `actionlint`

- SUPPORTED_CHAINS.md
This PR adds the following changes to the supported chains list:
* Sorting the list (ascending) by the chain ID,
* Making the list in a table.
Don't need testing.
> feat(docs): sorting supported chains list by the chainId

- src/providers/weights.rs
This PR removed `unwrap()` in the weights update. This should properly handle the removal of the provider when the provider was removed, but there is still the data for it in Prometheus.
Not tested.
> fix: removing `unwrap` in updating weights

- .github/workflows/dispatch_deploy.yml
- .github/workflows/dispatch_publish.yml
- .github/workflows/dispatch_validate.yml
- .github/workflows/event_intake.yml
- .github/workflows/event_pr.yml
- .github/workflows/event_release.yml
- .github/workflows/sub-cd.yml
- .github/workflows/sub-providers.yml
- .github/workflows/sub-validate.yml
- .gitignore
Downgrade runners as per this [Slack conversation](https://walletconnect.slack.com/archives/C04SYT4LU2W/p1710236835371879)
Not tested
> chore: downgrade runner

- src/project/storage/mod.rs
- src/providers/mod.rs
This PR adds minor changes for the proper `unwraps` handling where appropriate for adding additional error context and removing the possible app `panic`.
Not tested.
> fix: removing unwraps for proper handling and error context

- src/providers/zerion.rs
This PR improves error logging in the transactions history implementation.
Not tested.
> feat(logging): improving logging in the transactions history

- integration/identity.test.ts
- src/handlers/identity.rs
- src/handlers/mod.rs
Skip cache for integration tests. [Slack conversation](https://walletconnect.slack.com/archives/C03SCF66K2T/p1712723770547469?thread_ts=1712718581.866209&cid=C03SCF66K2T)
Not
> fix: disable cache for testing project ID

- src/handlers/identity.rs
- src/handlers/proxy.rs
This PR adds project quota and validation as a first step to the identity handler. In this case, we are returning the quota limiting or wrong project ID early and we don't need to handle these errors from RPC later. Also, this will make availability metrics fair by excluding quota-limited requests from failed.
Resolves: #264 
* Current integration tests are passed.
> fix(identity): adding project ID validation first in the handler

- SUPPORTED_CHAINS.md
- src/env/pokt.rs
- tests/functional/http/pokt.rs
This PR adds Polygon Amoy testnet to the supported chains.
Updated provider test.
> feat(providers): adding Polygon Amoy testnet

- Cargo.lock
- Cargo.toml
- justfile
- src/project/mod.rs
- src/project/storage/mod.rs
- src/state.rs
Update to latest cerberus version to keep requesting quotas.
https://github.com/WalletConnect/explorer-api/pull/233
Remaining work:
> fix: keep requesting quotas

- terraform/monitoring/dashboard.jsonnet
- terraform/monitoring/panels/irn/latency.libsonnet
- terraform/monitoring/panels/panels.libsonnet
This PR adds a new panel to the Grafana for the IRN client latency. Also, the new alert for the latency is > 1.5 sec. was added.
Not tested.
> feat(grafana): adding panel and alert for IRN client latency

- src/handlers/identity.rs
This PR adds proper handling of all possible JSON-RPC `execution reverted` error codes that occur during the ENS avatar lookup and lead to the `HTTP 500 errors` instead of an empty avatar.
Along with the `-32000` code the following codes were added:
* `-32015`: VM execution error: revert.
* `3`: ERC721: token does not exist.
This PR will fix all identity lookups for unexistent avatar errors.
* To test the handling of the `-32015` code the `0x82E7BbDf05DaaD0254160807590b58891B0cbeAA` address can be used:
* The current behavior is: `HTTP 500`.
* The response after this PR: an empty avatar.
* To test the handling of the `3` code the `0xF1cc2f3047CD31eDAd0b35dE19B45830d2a4E281` address can be used:
* The current behavior is: `HTTP 500`.
* The response after this PR: an empty avatar.
> fix(identity): handling of all execution reverted codes during the avatar lookup

- Cargo.lock
- Cargo.toml
- integration/history.test.ts
- src/providers/solscan.rs
- src/utils/crypto.rs
This PR fixes transaction history integration tests by making the following changes:
* Updating the address format checking function;
* Fixing the comparison in the tests;
* Removing the `next` cursor in case of empty data.
* Tested by running the integration test locally and passing tests.
> fix(tests): fixing transactions history integration tests

- src/providers/solscan.rs
This PR adds injecting SOL native token balance if not zero to the account balance response endpoint.
Currently, only SPL tokens are listed. To support the same Ethereum UI flow, this change injects the native token balance into the balance tokens list. 
To get the account SOL native tokens balance [SolScan Account details API](https://pro-api.solscan.io/pro-api-docs/v2.0/reference/v2-account-detail) is used and `lamports` field for the amount calculation.
* Current Solana specific integration tests.
> feat(providers): injecting SOL native token balance

- src/providers/solscan.rs
This PR fulfills Solana's transaction history with the token metadata from the recently implemented `get_token_info` method to fulfill missed UI elements.
* Covered by the current integration tests.
> feat(history): fulfills Solana's transaction history with the token metadata

- terraform/monitoring/panels/app/handlers_latency.libsonnet
This PR separates the handler's high execution time alert for all handlers and for the transactions history endpoint because Solana history takes longer and should have a higher alerting threshold.
* Only manual testing.
> feat(monitoring): separating the alert for transactions list handler

- src/providers/one_inch.rs
This PR adds proper handling of the HTTP 400 Bad Request response from OneInch provider.
* Updating the error object schema to the up-to-date to extract the error description and pass it through along with the HTTP 400 response,
* Responding with the HTTP 400 Bad Request even if the OneInch error schema was changed (currently we are responding with the HTTP 500 which is confusing) to reflect that this is a bad argument related issue and not the server error.
> fix(OneInch): proper handling of the bad request responses

- .github/workflows/event_pr.yml
- .github/workflows/sub-providers.yml
- .github/workflows/sub-validate.yml
- Cargo.lock
- Cargo.toml
- src/analytics/message_info.rs
- src/error.rs
- src/handlers/sessions/get.rs
- src/handlers/sessions/mod.rs
- src/handlers/wallet/mod.rs
- src/handlers/wallet/prepare_calls.rs
- src/handlers/wallet/send_prepared_calls.rs
- src/handlers/wallet/types.rs
- src/lib.rs
Implements paymaster on prepareCalls and implement sendPreparedCalls according to [the spec](https://www.notion.so/walletconnect/API-specs-for-Wallet-Services-0c4b70a397e2435691f9bb1f20bc652d?pvs=4).
Depends on https://github.com/reown-com/yttrium/pull/31
Not tested
> feat: send prepared calls

- .gitmodules
This PR updates the `irn` submodule path.
Not tested.
> fix: updating the `irn` submodule path

- .github/workflows/dispatch_deploy.yml
- .github/workflows/dispatch_publish.yml
- .github/workflows/dispatch_validate.yml
- .github/workflows/event_pr.yml
- .github/workflows/event_release.yml
- .github/workflows/sub-cd.yml
This PR bumps the `WalletConnect/ci_workflows` to the latest version.
Tested by running the build and dispatch action from the branch.
> fix(ci): bumping the `ci_workflows` to the latest version

- terraform/monitoring/dashboard.jsonnet
This PR adds missed Berachain provider Grafana panels.
* Not tested.
> feat(grafana): adding Berachain provider panels

- SUPPORTED_CHAINS.md
- src/env/mod.rs
- src/env/unichain.rs
- src/lib.rs
- src/providers/mod.rs
- src/providers/unichain.rs
- terraform/monitoring/dashboard.jsonnet
- tests/functional/http/mod.rs
- tests/functional/http/unichain.rs
This PR adds Unichain Sepolia support (eip155:1301):
* Adding Unichain native RPC endpoint and provider,
* Adding test case for the `eip155:1301`,
* Adding Grafana panels for Unichain provider for the native endpoint.
* New test for the Unichain provider.
> feat(providers): adding Unichain support

- src/providers/pokt.rs
This PR adds proper handling of the internal node error response for the Pokt/Groove provider.
When the node becomes unhealthy there are `HTTP 200 Ok` responses with different response schema: `request_id` and `error`. This PR adds proper handling of these cases as an HTTP 5xx error response depending on the error message.
* Tested manually on the unhealthy Arbitrum node responses.
> fix(providers): adding proper error handling for the Pokt(Groove) provider

- src/env/infura.rs
- src/env/publicnode.rs
- tests/functional/http/infura.rs
- tests/functional/http/publicnode.rs
This PR adds additional providers for:
* Mantle chain `eip155:5000` to the Infura provider,
* Gnosis chain `eip155:100` to the Publicnode provider.
> feat(providers): adding providers for Mantle and Gnosis chains

- integration/chain_orchestrator.test.ts
- src/handlers/chain_agnostic/route.rs
This PR adds minimal bridging fee coverage of `0.05` USDC/USDT to use it when the calculated top-up amount is less than the minimal possible bridging fees.
Currently, we have a 5% bridging amount multiplier that [adds to the top-up amount](https://github.com/reown-com/blockchain-api/blob/c36e88bc766b601774a1666967c2b3ab8f917d68/src/handlers/chain_agnostic/route.rs#L184). When small amounts less than 1 USDC/USDT that results that the final bridged amount is slightly less than expected. Using the minimal bridging coverage amount of `0.05` should fix this.
* New integration test was added.
> fix(CA): adds the minimal bridging fee coverage

- src/handlers/chain_agnostic/route.rs
- src/handlers/sessions/get.rs
- src/handlers/sessions/list.rs
- src/providers/bungee.rs
- src/providers/mod.rs
- src/storage/redis/mod.rs
- terraform/monitoring/dashboard.jsonnet
This PR adds latency and status code metrics for the Bungee provider and Grafana panels.
Not tested.
> feat(o11y): adding Bungee provider metrics and Grafana panels

- Cargo.lock
- Cargo.toml
- integration/chain_orchestrator.test.ts
- src/handlers/chain_agnostic/mod.rs
- src/handlers/chain_agnostic/route.rs
- src/handlers/chain_agnostic/status.rs
- src/providers/bungee.rs
This PR implements the use of the yttrium types for the chain abstraction endpoints.
Current integration tests.
> feat(CA): using yttrium types

- Cargo.lock
- Cargo.toml
- src/handlers/wallet/prepare_calls.rs
Refactors some functions into yttrium (functions used by [this PR](https://github.com/reown-com/yttrium/pull/90)).
Also upgrade alloy to Yttrium's version.
Depends on https://github.com/reown-com/yttrium/pull/90
Not tested
> chore: upgrade alloy & refactor functions into yttrium

- Cargo.lock
- Cargo.toml
- integration/chain_orchestrator.test.ts
- src/handlers/chain_agnostic/mod.rs
- src/handlers/chain_agnostic/route.rs
- src/utils/crypto.rs
Depends on https://github.com/reown-com/yttrium/pull/98
Not tested
> fix: refactor txn types

- src/env/drpc.rs
- src/env/mod.rs
- src/lib.rs
- src/providers/drpc.rs
- src/providers/mod.rs
- tests/functional/http/drpc.rs
- tests/functional/http/mod.rs
This PR adds the dRPC Solana endpoint for the Solana mainnet.
New integration test for provider was added.
> feat(providers): adding dRPC endpoint for Solana

- terraform/monitoring/dashboard.jsonnet
This PR adds Grafana panels for dRPC provider observability.
Not tested.
> feat(011y): adding dRPC Grafana panels

- src/providers/dune.rs
This PR changes when to call for the cached metadata in the Dune balance provider implementation. Currently, if metadata is not provided the asset is skipped as spam and then we check for the cached item. This PR changed this to check the cached asset metadata first to show the asset even if it's not present in the Dune response.
* Current balance integration tests.
> fix(Dune): checking for the cached metadata first

- src/env/drpc.rs
- src/env/infura.rs
- src/env/pokt.rs
- src/env/publicnode.rs
- tests/functional/http/drpc.rs
- tests/functional/http/pokt.rs
- tests/functional/http/publicnode.rs
This PR decreases RPC traffic from the Infura provider to other providers. 
Revising providers endpoints to the up-to-date and tests.
> feat(providers): decreasing traffic from Infura to other providers

- src/handlers/proxy.rs
- src/providers/mod.rs
Fixes the crash that the ID was lowercase instead of uppercase.
Not tested
> fix: sessionId hardcoded list

- src/analytics/mod.rs
As requested in [Slack conversation](https://reown-inc.slack.com/archives/C04HK47TNBB/p1739283975145939)
Not tested
> chore: fix CA analytics dirs

- src/analytics/balance_lookup_info.rs
- src/analytics/history_lookup_info.rs
- src/handlers/balance.rs
- src/handlers/history.rs
- src/providers/coinbase.rs
- src/providers/dune.rs
- src/providers/mod.rs
- src/providers/solscan.rs
- src/providers/zerion.rs
Adds `provider` for balance and history.
[Slack conversation](https://reown-inc.slack.com/archives/C03SCF66K2T/p1739373849722319)
Not tested
> feat: balance & history provider analytics

- funding.json
> chore: verifies repository ownership

- Cargo.lock
- Cargo.toml
- src/project/mod.rs
> fix: hardcode origin header for registry API

- Cargo.lock
- Cargo.toml
Forgot to pin cerberus in #960 
Not tested
> fix: pin cerberus

- src/analytics/message_info.rs
- src/handlers/balance.rs
- src/handlers/wallet/get_assets.rs
- src/handlers/wallet/get_calls_status.rs
- src/handlers/wallet/handler.rs
- src/handlers/wallet/mod.rs
Fixes WK-561
Implementation and tests copied from the code approximately at [this PR](https://github.com/reown-com/secure-appkit/pull/310).
[Slack conversation](https://reown-inc.slack.com/archives/C0816SK4877/p1740069394401809)
New automated tests
> feat: ERC-7811 support (wallet_getAssets)

- src/handlers/wallet/get_assets.rs
This PR ports this [JS PR](https://github.com/reown-com/secure-appkit/pull/313) and implements the same fix.
[Slack conversation](https://reown-inc.slack.com/archives/C0816SK4877/p1740180693431329)
Ported test cases
> fix: port fix from JS impl

- Cargo.lock
- Cargo.toml
- src/handlers/chain_agnostic/route.rs
This PR improves error responses with the `reason` field containing the detailed error messages for any of the CA error responses.
Not tested.
> feat(CA): improving error responses

- src/providers/pimlico.rs
This PR adds an exclusion for the `eth_estimateUserOperationGas` operation to inject a third parameter with the state overrides for the smart account during estimation to prevent AA21 errors while estimating.
The injected parameter should be like this according to the [Pimlico docs](https://docs.pimlico.io/infra/platform/api/upgrade#upgrade-to-the-raw-api):
```
{
// Sender address from the first parameter
"0xd9c9cd5f6779558b6e0ed4e6acf6b1947e7fa1f3": {
// Adding 100 ETH to the smart account during estimation to prevent AA21 errors while estimating
"balance": "0x56BC75E2D63100000"
},
```
The full context:
https://reown-inc.slack.com/archives/C03RVH94K5K/p1741175987671759?thread_ts=1741106163.611409&cid=C03RVH94K5K
Not tested.
> feat(Pimlico): adding an exclusion to the `eth_estimateUserOperationGas` operation

- Cargo.lock
This PR updates irn to the `0657696` commit and updates the `Cargo.lock` file.
Running the integration tests locally.
> feat(wcn): update the client version

- .github/workflows/sub-yttrium-integration.yml
Fixes [this pipeline failure](https://github.com/reown-com/blockchain-api/actions/runs/13933100305/job/38996617140)
Not tested
> fix: yttrium e2e tests

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/handlers/chain_agnostic/route.rs
- src/handlers/wallet/get_assets.rs
Resolves WK-623
Resolves WK-602
> fix: add custom metadata to wallet_getAssets response & remove unwraps()

- src/providers/mock_alto.rs
- src/providers/pimlico.rs
- src/utils/crypto.rs
> fix: forward bundler errors

- src/handlers/wallet/prepare_calls.rs
Resolves https://linear.app/reown/issue/CR-672/implement-7677-for-wallet-preparecalls
Not tested
> feat: ERC-7677 paymasterService capability

- terraform/ecs/cluster.tf
- terraform/ecs/variables.tf
- terraform/res_ecs.tf
- terraform/variables.tf
Adding env variables for Coinbase and Binance exchanges
> chore: add terraform exchanges env

- .github/workflows/sub-yttrium-integration.yml
- Cargo.lock
- Cargo.toml
- docker-compose.mock-bundler.yaml
- src/handlers/chain_agnostic/lifi.rs
- src/handlers/chain_agnostic/mod.rs
- src/handlers/chain_agnostic/route.rs
Adds a query param allowing clients to opt-in to using LiFi for EVM bridging transactions.
Resolves WK-637
Resolves WK-617
Depends on https://github.com/reown-com/yttrium/pull/160
New tests (wip)
> feat: LiFi feature flag

- src/handlers/balance.rs
This PR is a null change to trigger a new CI/CD release.
Don't need to be tested.
> fix: null changes to trigger a new release

- Cargo.lock
- Cargo.toml
- src/handlers/wallet/get_assets.rs
Bump yttrium to incorporate paymaster fix 
Depends on https://github.com/reown-com/yttrium/pull/165
Not tested
> chore: bump yttrium

- terraform/monitoring/data_sources.tf
- terraform/monitoring/terraform.tf
- terraform/providers.tf
- terraform/res_monitoring.tf
- terraform/variables.tf
This PR extends the Prometheus provider with the data source from a business workspace.
> feat: extending Prometheus provider to use a business workspace

- src/handlers/wallet/exchanges/coinbase.rs
Fix Coinbase transaction status not properly parsed
> fix: coinbase transaction status

- .github/workflows/event_pr.yml
- docker-compose.mock-bundler.yaml
- src/handlers/chain_agnostic/mod.rs
- src/handlers/chain_agnostic/nonce_manager.rs
- src/handlers/chain_agnostic/route.rs
- src/handlers/self_provider.rs
Fix failing nonce-related check: https://github.com/reown-com/blockchain-api/actions/runs/14777402543/job/41496849695#step:5:162
Not tested
> fix: nonce manager

- src/handlers/wallet/get_exchange_url.rs
> fix: buy url

- terraform/monitoring/data_sources.tf
- terraform/monitoring/terraform.tf
- terraform/monitoring/variables.tf
- terraform/providers.tf
- terraform/res_monitoring.tf
- terraform/variables.tf
This PR removes Grafana SLA workspace support.
Not tested.
> feat: removing Grafana SLA workspace support

- Cargo.lock
- Cargo.toml
This PR updates the Yttrium dependency to the latest.
Not tested.
> feat: updating yttrium

- src/error.rs
This PR distinguishes logging of the Internal server error `HTTP 500` and any other server errors (e.g. `HTTP 503`) for a faster search in case of the unhandled errors.
This PR also removes the client errors logging since there is no reason for logging (we haven't used it), and it creates excessive logging in case of the rate-limiting since it logs `HTTP 429` 
Not tested.
> fix(logs): distinguishing server errors and internal server errors

- src/env/drpc.rs
- src/env/publicnode.rs
This PR extends providers for the Celo mainnet chain.
Not tested.
> feat(providers): extending providers for the Celo chain

- src/handlers/wallet/exchanges/binance.rs
Adding two flags in order to improve the UX on the Binance side
> feat: enable binance flags

- src/providers/onerpc.rs
This PR adds a proper handling of the rate-limited response in the OneRpc provider: [Slack thread](https://reown-inc.slack.com/archives/C07C28F0ALX/p1749115597003109)
> fix(OneRpc): adding a proper handling of the rate-limited response

- src/providers/mod.rs
This PR changes the weighted balance providers selection algorithm to use balance providers with the `Minimal` priority only for a failover.
This should temporarily fix the balance providers' tokens list inconsistency.
The [Slack thread](https://reown-inc.slack.com/archives/C03SCF66K2T/p1748842766848099).
> fix(balance): using the minimal priority providers only for a failover

- src/providers/dune.rs
This PR removes the `exclude_spam_tokens` flag from the Dune balance request and adds filtering spam tokens by the minimal pool size (which is set to `10`) and by the `low_liquidity` flag.
Tested by the current integration tests and manually.
> fix(Dune): disabling `exclude_spam_tokens` and filtering by the pool size

- integration/exchanges.test.ts
- src/handlers/wallet/exchanges/mod.rs
Add integration tests for pay with exchange functionality
> chore: exchange tests

- src/handlers/wallet/exchanges/test_exchange.rs
Update test exchange implementation to reflect updates in the API. Send POST instead of GET for status checks
> chore: update test exchange implementation

- Cargo.lock
- Cargo.toml
- src/lib.rs
> fix: adding axum custom listener with the backlog size

- LICENSE
This PR updates the LICENSE file to the REOWN COMMUNITY LICENSE AGREEMENT.
Not tested.
> feat: updating the LICENSE

- integration/exchanges.test.ts
- src/handlers/json_rpc/exchanges/binance.rs
- src/handlers/json_rpc/exchanges/coinbase.rs
- src/handlers/json_rpc/exchanges/get_exchange_buy_status.rs
- src/handlers/json_rpc/exchanges/get_exchange_url.rs
- src/handlers/json_rpc/exchanges/mod.rs
- src/handlers/json_rpc/exchanges/test_exchange.rs
Adding a new `enabled` flag to every exchange type with Coinbase set to `false`
> feat: exchange enabled flag

- SUPPORTED_CHAINS.md
- src/chain_config.rs
- src/env/quicknode.rs
- terraform/monitoring/chain_config.json
- tests/functional/http/quicknode.rs
This PR removes the Berachain bArtio chain due to [the chain sunset](https://sunset.bartio.berachain.com/).
> fix(RPC): removing Berachain bArtio chain
